-------------------------------------------------------------------------------
---   Modular Simulator Controller System - Action Callbacks Script         ---
---                                                                         ---
---   Author:     Oliver Juwig (TheBigO)                                    ---
---   License:    (2025) Creative Commons - BY-NC-SA                        ---
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
---                           Public Modules Section                        ---
-------------------------------------------------------------------------------

Assistant = {}
Controller = {}
Function = {}
Rules = {}


-------------------------------------------------------------------------------
---                          Public Functions Section                       ---
-------------------------------------------------------------------------------

function Assistant.Ask(question)
	return __Assistant_Ask(question)
end

function Assistant.Speak(message, ...)
	assert(#... == 0 or (#... == 1 and type(...[1]) = "boolean"))
	
	return __Assistant_Speak(message, ...)
end

function Assistant.Raise(event, ...)
	for i, v in ipairs(...) do
		...[i] = tostring(v)
	end
	
	return __Assistant_Raise(event, ...)
end

function Assistant.Call(function, ...)
	for i, v in ipairs(...) do
		...[i] = tostring(v)
	end
	
	return __Assistant_Call(function, ...)
end

function Controller.Call(function, ...)
	for i, v in ipairs(...) do
		...[i] = tostring(v)
	end
	
	return __Controller_Call(function, ...)
end

function Function.Call(function, ...)
	for i, v in ipairs(...) do
		...[i] = tostring(v)
	end
	
	return __Function_Call(function, ...)
end

function Rules.GetValue(name, ...)
	local value = __Rules_GetValue(name)
	
	assert(#... <= 1)
	
	if (value == nil or value == __NotInitialized or value == __Undefined) and #... > 0 then
		value = table.unpack(...)
		
	return value
end

function Rules.SetValue(name, value)
	__Rules_SetValue(name, tostring(value))
end

function Rules.Execute()
	__Rules_Execute()
end
	