-------------------------------------------------------------------------------
---   Modular Simulator Controller System - Simulator Module                ---
---                                                                         ---
---   Author:     Oliver Juwig (TheBigO)                                    ---
---   License:    (2025) Creative Commons - BY-NC-SA                        ---
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
---                         Private Functions Section                       ---
-------------------------------------------------------------------------------

__call_simulator = extern("callSimulator")
__read_simulator= extern("readSimulator")


-------------------------------------------------------------------------------
---                        Public Topics Section                            ---
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
---                             Simulator                                   ---
-------------------------------------------------------------------------------

Simulator = {}

-------------------------------------------------------------------------------
---                             Functions                                   ---
-------------------------------------------------------------------------------

Simulator.Read = function (simulator, car, track)
	return __read_simulator(simulator, car, track. "Text")
end

Simulator.Call = function (simulator, command)
	return __call_simulator(simulator, command)
end