-------------------------------------------------------------------------------
---   Modular Simulator Controller System - Simulator Module                ---
---                                                                         ---
---   Author:     Oliver Juwig (TheBigO)                                    ---
---   License:    (2026) Creative Commons - BY-NC-SA                        ---
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
---                         Private Functions Section                       ---
-------------------------------------------------------------------------------

__call_simulator = extern("_callSimulator")
__read_simulator = extern("_readSimulator")
__read_session = extern("_readSession")
__read_standings = extern("_readStandings")
__read_pitstop = extern("_readPitstop")


-------------------------------------------------------------------------------
---                        Public Topics Section                            ---
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
---                             Simulator                                   ---
-------------------------------------------------------------------------------

Simulator = {}

-------------------------------------------------------------------------------
---                             Functions                                   ---
-------------------------------------------------------------------------------

Simulator.Read = function (simulator, ...)
	local arguments = table.pack(...)
	
	return __read_simulator(simulator, table.unpack(arguments))
end

Simulator.ReadSession = function (simulator, ...)
	local arguments = table.pack(...)
	
	return __read_session(simulator, table.unpack(arguments))
end

Simulator.ReadStandings = function (simulator, ...)
	local arguments = table.pack(...)
	
	return __read_standings(simulator, table.unpack(arguments))
end

Simulator.ReadPitstop = function (simulator, ...)
	local arguments = table.pack(...)
	
	return __read_pitstop(simulator, table.unpack(arguments))
end

Simulator.Call = function (simulator, ...)
	local arguments = table.pack(...)
	
	return __call_simulator(simulator, table.unpack(arguments))
end