var gvjs_OV="border: 0; padding: 0; margin: 0;";function gvjs_PV(a,b,c,d,e){gvjs_tn.call(this);this.da=a;this.fa=b;this.Ma=c;this.LL=new gvjs_bi({nb:gvjs_eu,fontSize:d,color:gvjs_$r,opacity:1,Ub:"",bold:!1,td:!1,Af:!1});this.rAa=new gvjs_bi({nb:gvjs_eu,fontSize:d,color:gvjs_6a,opacity:1,Ub:"",bold:!1,td:!1,Af:!1});this.rza=new gvjs_bi({nb:gvjs_eu,fontSize:0,color:gvjs_$r,opacity:1,Ub:"",bold:!1,td:!1,Af:!1});this.Hwa=e;this.Rg=this.Xa=this.C=null;this.Q1=[]}gvjs_p(gvjs_PV,gvjs_tn);
var gvjs_QV=new gvjs_B({fill:gvjs_ms,stroke:gvjs_$r,strokeWidth:1}),gvjs_RV=new gvjs_B({fill:"#f7f7f7",stroke:gvjs_ns,strokeWidth:2}),gvjs_Ija=new gvjs_B({stroke:gvjs_cs,strokeWidth:1}),gvjs_Jja=new gvjs_B({stroke:gvjs_$r,strokeWidth:2}),gvjs_Kja=new gvjs_B({fill:"#dc3912",fillOpacity:.7,stroke:"#c63310",strokeWidth:1}),gvjs_Lja=new gvjs_B({fill:"#4684ee",stroke:gvjs_cs,strokeWidth:1});gvjs_=gvjs_PV.prototype;gvjs_.cb=NaN;gvjs_.Ib=NaN;gvjs_.nca=NaN;gvjs_.UD=NaN;gvjs_.ne=0;gvjs_.rY=null;gvjs_.ML=null;
gvjs_.z4=null;gvjs_.K6=270;gvjs_.kda=0;gvjs_.jda=null;gvjs_.YJ=null;gvjs_.Jz=null;gvjs_.rg=null;gvjs_.Pf=function(){return this.cb};gvjs_.Pw=function(a){this.cb=a};gvjs_.Of=function(){return this.Ib};gvjs_.pu=function(a){this.Ib=a};
gvjs_.ab=function(a,b,c){this.ne=a;this.rY=b;this.wu();a=gvjs_SV(this,a);null!=this.YJ&&c?(this.rg=new gvjs_9D([this.YJ],[a],c.duration,c.easing),gvjs_Q(this.rg,["begin","animate",gvjs_0],this.rva,!1,this),gvjs_Q(this.rg,gvjs_0,this.qva,!1,this),this.rg.play(!1)):(this.YJ=a,gvjs_TV(this))};gvjs_.tT=function(a,b){this.nca=Math.max(1,a);this.UD=Math.max(1,b)};gvjs_.b3=function(a){this.Jz=a};function gvjs_UV(a,b,c,d){a.Q1.push({Lf:b,Ql:c,color:d})}gvjs_.setAnimation=function(){};
gvjs_.clear=function(){this.wu();gvjs_P(this.Xa);this.Xa=null;gvjs_pn(this)};gvjs_.draw=function(a,b){var c=new gvjs_w(this.fa,this.Ma);null!=this.Xa?this.Xa.update(c,a):this.Xa=new gvjs_QA(this.da,c,a,b);this.Xa.Yp(gvjs_o(this.Mo,this),a)};
gvjs_.Mo=function(){var a=this.Xa.gb(),b=a.rn(this.fa,this.Ma);a.Cc(b,gvjs_Yj,gvjs_3m);this.C=a;var c=this.Rg=a.Wa(!1);a.appendChild(b,c);b=Math.round(.45*Math.min(this.fa,this.Ma));var d=this.fa/2,e=this.Ma/2;a.df(d-.5,e-.5,b,gvjs_QV,c);b-=gvjs_QV.bc;b=Math.round(.9*b);a.df(d-.5,e-.5,b,gvjs_RV,c);b-=2*gvjs_RV.bc;var f=.75*b;for(var g=0;g<this.Q1.length;g++){var h=this.Q1[g],k=gvjs_VV(this,gvjs_SV(this,h.Lf)),l=gvjs_VV(this,gvjs_SV(this,h.Ql)),m=new gvjs_oA,n=d+gvjs_fd(k,b),p=e+gvjs_gd(k,b);m.move(n,
p);m.qg(d,e,b,b,k+90,l+90,!0);n=d+gvjs_fd(l,f);p=e+gvjs_gd(l,f);m.Aa(n,p);m.qg(d,e,f,f,l+90,k+90,!1);m.close();a.Oa(m,new gvjs_B({fill:h.color}),c)}if(this.ML||this.z4)this.ML&&(f=e-Math.round(.35*b),a.rj(this.ML,0,f,this.fa,f,gvjs__,gvjs__,this.LL,c)),this.z4&&(f=e+Math.round(.35*b),a.rj(this.z4,0,f,this.fa,f,gvjs__,gvjs__,this.LL,c));h=this.UD;k=.8*b;l=.9*b;n=this.nca*h;p=(this.Ib-this.cb)/n;var q=new gvjs_oA,r=new gvjs_oA,t=this.rza,u=Math.round(.14*b);t.fontSize=u;for(g=0;g<=n;g++){var v=gvjs_VV(this,
gvjs_SV(this,g*p+this.cb)),w=0==g%h,y=w?k:l;m=w?q:r;var x=d+gvjs_fd(v,y);f=e+gvjs_gd(v,y);m.move(x,f);x=d+gvjs_fd(v,b);f=e+gvjs_gd(v,b);m.Aa(x,f);w&&this.Jz&&(m=this.Jz[Math.floor(g/h)])&&(x=d+gvjs_fd(v,y-u/2),f=e+gvjs_gd(v,y-u/2),y=gvjs__,280<v||90>v?(y=gvjs_0,v=0):90<=v&&260>v?(y=gvjs_2,v=x,x=this.fa):(w=Math.min(x,this.fa-x),v=x-w,x+=w,f+=Math.round(u/4)),a.rj(m,v,f,x,f,y,gvjs__,t,c))}a.Oa(r,gvjs_Ija,c);a.Oa(q,gvjs_Jja,c);this.wu();this.kda=b;gvjs_TV(this);this.Hwa()};
gvjs_.rva=function(a){this.YJ=a.x;gvjs_TV(this)};gvjs_.qva=function(){this.wu()};gvjs_.wu=function(){this.rg&&(gvjs_pn(this.rg),this.rg.stop(!1),gvjs_P(this.rg),this.rg=null)};function gvjs_SV(a,b){a=(b-a.cb)/(a.Ib-a.cb);a=Math.max(a,-.02);return a=Math.min(a,1.02)}function gvjs_VV(a,b){return a.K6*b+gvjs_cd((360-a.K6)/2+90)}
function gvjs_TV(a){if(a.C){var b=a.kda,c=a.C,d=a.fa/2,e=a.Ma/2,f=gvjs_VV(a,a.YJ),g=Math.round(.95*b),h=Math.round(.3*b),k=gvjs_fd(f,g);g=gvjs_gd(f,g);var l=gvjs_fd(f,h);h=gvjs_gd(f,h);f=gvjs_cd(f+90);var m=.07*b,n=gvjs_fd(f,m);m=gvjs_gd(f,m);f=new gvjs_oA;f.move(d+k,e+g);f.bq(d+n,e+m,d-l+n/2,e-h+m/2,d-l,e-h);f.bq(d-l-n/2,e-h-m/2,d-n,e-m,d+k,e+g);k=Math.round(.15*b);(g=a.jda)?c.uc(g):g=a.jda=c.Wa();a.rY&&(b=e+Math.round(.75*b),c.rj(a.rY,0,b,a.fa,b,gvjs__,gvjs__,a.rAa,g));c.Oa(f,gvjs_Kja,g);c.df(d-
.5,e-.5,k,gvjs_Lja,g);c.appendChild(a.Rg,g)}};function gvjs_WV(a,b,c,d){this.da=a;this.fa=b;this.Ma=c;this.OO=d;this.Qy=[];this.Fc=[];this.Jz=[];this.sY=[];this.dr=[];this.cb=0;this.Ib=100;this.L6=this.W1=this.qS=this.pS=this.B5=this.OU=this.NU=this.jZ=this.xP=this.wP=null;this.Pr=!0;this.V0=0}gvjs_=gvjs_WV.prototype;gvjs_.UD=2;gvjs_.Pw=function(a){this.cb!=a&&(this.cb=a,this.Pr=!0)};gvjs_.Pf=function(){return this.cb};gvjs_.pu=function(a){this.Ib!=a&&(this.Ib=a,this.Pr=!0)};gvjs_.Of=function(){return this.Ib};
gvjs_.setAnimation=function(a){this.L6=a};gvjs_.setValues=function(a,b,c){this.Pr=this.Pr||this.Fc.length!=a.length||this.dr.length!=c.length||!gvjs_4c(this.dr,c);this.Fc=a;this.sY=b;this.dr=c};gvjs_.b3=function(a){1==a.length&&(a=["",a[0],""]);gvjs_4c(this.Jz,a)||(this.Jz=a,this.Pr=!0)};function gvjs_XV(a,b,c){return Math.min(Math.floor(a.fa/c),Math.floor(a.Ma/b))}
gvjs_.draw=function(a){if(this.Pr)gvjs_Mja(this,a);else for(a=0;a<this.Fc.length;a++){var b=this.Qy[a];b.ML=this.dr[a];b.ab(this.Fc[a],this.sY[a],this.L6)}};
function gvjs_Mja(a,b){a.clear();var c=a.Fc.length,d=1,e=1;if(1<c){var f=Math.floor(Math.sqrt(a.fa*a.Ma/c));e=Math.floor(a.fa/f);for(d=Math.floor(a.Ma/f);!(c<=Math.floor(a.fa/f)*Math.floor(a.Ma/f));){var g=gvjs_XV(a,d,e+1),h=gvjs_XV(a,d+1,e);g>=h&&(f=g,e++);h>=g&&(f=h,d++)}}f=gvjs_XV(a,d,e);f-=0;h=gvjs_7o();h.uc(a.da);a.Qy=[];if(0!=c){var k=h.G(gvjs_Qa,{style:gvjs_OV,cellpadding:0,cellspacing:0,align:gvjs__}),l=h.G(gvjs_Ra,null);h.appendChild(k,l);g=[];for(var m=0,n=0;n<d;n++){var p=h.G(gvjs_Ua,{style:gvjs_OV});
h.appendChild(l,p);for(var q=0;q<e;q++){var r=h.G(gvjs_Sa,{style:"border: 0; padding: 0; margin: 0; width: "+f+"px;"});g[m++]=r;h.appendChild(p,r)}}h.appendChild(a.da,k);d=Math.round(.1*f);a.V0=0;a.Pr=!0;for(e=0;e<c;e++)h=a.Qy[e]=new gvjs_PV(g[e],f,f,d,gvjs_o(function(){this.V0++;this.V0==this.Qy.length&&(this.Pr=!1)},a)),h.Pw(a.cb),h.pu(a.Ib),h.ML=a.dr[e],k=a.Jz,l=k.length,h.tT(1<l?l-1:4,a.UD),0<l&&h.b3(k),h.ab(a.Fc[e],a.sY[e],null),null!=a.wP&&null!=a.xP&&gvjs_UV(h,a.wP,a.xP,a.jZ),null!=a.NU&&null!=
a.OU&&gvjs_UV(h,a.NU,a.OU,a.B5),null!=a.pS&&null!=a.qS&&gvjs_UV(h,a.pS,a.qS,a.W1),h.draw(b,a.OO)}}gvjs_.clear=function(){for(var a=0;a<this.Qy.length;++a)this.Qy[a].clear();this.Qy=[]};function gvjs_YV(a){gvjs_Tq.call(this,a);this.H=gvjs_7o()}gvjs_p(gvjs_YV,gvjs_Tq);gvjs_=gvjs_YV.prototype;gvjs_.fa=0;gvjs_.Ma=0;gvjs_.OO=!0;
gvjs_.Qg=function(a,b,c){var d=new gvjs_oi([c||{}]);c=this.container;var e=gvjs_0o(c,d),f=gvjs_1o(c,d),g=gvjs_D(d,gvjs_0v);if(e!=this.fa||f!=this.Ma||g!=this.OO)this.sL&&this.sL.clear(),this.sL=new gvjs_WV(c,e,f,g),this.fa=e,this.Ma=f,this.OO=g;c=this.sL;e=gvjs_E(d,gvjs_ox,0);c.Pw(e);e=gvjs_E(d,gvjs_fx,100);c.pu(e);e=d.ga("majorTicks",[String(c.Pf()),"","","",String(c.Of())]);c.b3(e);e=gvjs_E(d,"minorTicks",2);c.UD!=e&&(c.UD=e,c.Pr=!0);e=d.Ga("greenFrom");f=d.Ga("greenTo");g=d.Ga("yellowFrom");var h=
d.Ga("yellowTo"),k=d.Ga("redFrom"),l=d.Ga("redTo"),m=gvjs_Oi(d,"greenColor",gvjs_8r),n=gvjs_Oi(d,"yellowColor",gvjs_js),p=gvjs_Oi(d,"redColor",gvjs_is);if(c.wP!=e||c.xP!=f||c.jZ!=m||c.NU!=g||c.OU!=h||c.B5!=n||c.pS!=k||c.qS!=l||c.W1!=p)c.wP=e,c.xP=f,c.jZ=m,c.NU=g,c.OU=h,c.B5=n,c.pS=k,c.qS=l,c.W1=p,c.Pr=!0;d=gvjs_IL(d,400,gvjs_Jw);c.setAnimation(d);d=[];e=[];f=[];if(2==b.Z()&&b.Y(0)==gvjs_f&&b.Y(1)==gvjs_e)for(g=0;g<b.ea();g++)null!=b.getValue(g,0)&&null!=b.getValue(g,1)&&(f.push(b.getValue(g,0)),d.push(b.getValue(g,
1)),e.push(b.Ta(g,1)));else for(h=0;h<b.Z();h++)if(b.Y(h)==gvjs_e)for(g=0;g<b.ea();g++)null!=b.getValue(g,h)&&(d.push(b.getValue(g,h)),e.push(b.Ta(g,h)),f.push(b.Ua(h)));c.setValues(d,e,f);c.draw(a);gvjs_T(this,gvjs_I,null)};gvjs_.Df=function(){this.sL&&this.sL.clear()};gvjs_k(gvjs_Hk,gvjs_YV,void 0);gvjs_YV.prototype.draw=gvjs_YV.prototype.draw;gvjs_YV.prototype.clearChart=gvjs_YV.prototype.Wb;gvjs_YV.prototype.getContainer=gvjs_YV.prototype.getContainer;
