var gvjs_YN="Invalid state: should be an array of values.",gvjs_ZN="No valid DataTable received from draw()",gvjs__N="Start and end points must be 2D",gvjs_0N="goog-combobox-active",gvjs_1N="goog-flat-button",gvjs_2N="goog-link-button",gvjs_3N="aside",gvjs_4N="belowStacked",gvjs_5N="blockIncrement",gvjs_6N="google-visualization-controls-rangefilter",gvjs_7N="placeholder",gvjs_8N="rangechange",gvjs_9N="uichange",gvjs_$N="useFormattedValue",gvjs_aO="yy/MM/dd hh:mma";
gvjs_iL.prototype.pZ=gvjs_V(71,function(){return this.ab});gvjs__C.prototype.pq=gvjs_V(58,function(a){this.bB=a});gvjs_1E.prototype.pq=gvjs_V(57,function(a){this.bB=a});gvjs_rB.prototype.xA=gvjs_V(53,function(){});gvjs_PB.prototype.xA=gvjs_V(52,function(a,b){a.setAttribute("y",b)});gvjs_TB.prototype.xA=gvjs_V(51,function(a,b){a.style.top=this.Ub(b)});gvjs_rB.prototype.tA=gvjs_V(50,function(){});gvjs_PB.prototype.tA=gvjs_V(49,function(a,b){a.setAttribute("x",b)});
gvjs_TB.prototype.tA=gvjs_V(48,function(a,b){a.style.left=this.Ub(b)});gvjs_F.prototype.fh=gvjs_V(11,function(){return this.xf});function gvjs_bO(a){return new gvjs_z(a.offsetLeft,a.offsetTop)}function gvjs_cO(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];gvjs_ne(d)?gvjs_cO.apply(null,d):gvjs_E(d)}}function gvjs_dO(a){gvjs_F.call(this);this.ma=a;this.ea=new gvjs_KA(this)}gvjs_t(gvjs_dO,gvjs_F);gvjs_=gvjs_dO.prototype;gvjs_.M=function(){this.clear();gvjs_dO.G.M.call(this)};
gvjs_.clear=function(){this.ea.removeAll();gvjs_E(this.ea);gvjs_hh(this.ma)};gvjs_.getContainer=function(){return this.ma};gvjs_.addEventListener=function(a,b,c,d,e){e?gvjs_LA(this.ea,a,b,c,d,e):this.ea.o(a,b,c,d)};gvjs_.draw=function(){};gvjs_.getState=function(){return{}};function gvjs_eO(a){gvjs_Qn.call(this,a);this.q9=[];this.Tv=this.K=this.R5=this.$L=this.Rc=this.m=this.su=this.ra=null}gvjs_o(gvjs_eO,gvjs_Qn);gvjs_=gvjs_eO.prototype;gvjs_.M=function(){this.clear();gvjs_Qn.prototype.M.call(this)};
gvjs_.clear=function(){this.He()};gvjs_.He=function(){this.$L&&(gvjs_ui(this.$L),gvjs_E(this.$L),this.$L=null);gvjs_E(this.Rc);this.Rc=null;gvjs_hh(this.container)};gvjs_.mb=function(){return this.ra};gvjs_.Zc=function(){return this.m};gvjs_.og=function(){return{}};gvjs_.Xl=function(a,b){return gvjs_my(b,"ui",{})};gvjs_.vv=function(){return""};gvjs_.zfa=function(a){this.q9=a};gvjs_.nP=function(){return this.q9};gvjs_.Mt=function(){};
gvjs_.getState=function(){return this.K?gvjs_Li(gvjs_Ii(this.K)):null};gvjs_.draw=function(a,b,c){gvjs_Kk(a);this.ra=a;this.su=b||{};this.R5=c||{};gvjs_Zg(this.Hg,this.D9,this)};gvjs_.Rd=function(){};
gvjs_.D9=function(){if(this.ra){this.K=this.R5||{};if(!gvjs_r(this.K))throw Error("Control state must be an object.");this.Tv=this.Tv||this.K;this.m=new gvjs_Aj([this.su,this.og()||{}]);this.Mt(this.ra,this.m,this.K);if(!this.Rc){var a=this.m.fa("ui.type",this.vv());a=typeof a===gvjs_d?new a(this.container):(a=gvjs_Gm(a))?new a(this.container):null;this.Rc=a;if(!this.Rc)throw Error("Invalid UI instance.");this.$L=gvjs_oi(this.Rc,gvjs_9N,this.Bya.bind(this))}this.Rc.draw(this.K,this.Xl(this.ra,this.m));
this.K=this.Rc.getState();gvjs_I(this,gvjs_i,null)}};gvjs_.Bya=function(a){this.K=this.Rc.getState();gvjs_I(this,gvjs_Hd,a)};gvjs_.Gw=function(){gvjs_Zg(this.Hg,this.Gva,this)};gvjs_.Gva=function(){this.Tv&&(this.R5=this.Tv,this.D9())};
function gvjs_bia(a){if(a.altKey&&!a.ctrlKey||a.metaKey||112<=a.keyCode&&123>=a.keyCode)return!1;if(gvjs_$A(a.keyCode))return!0;switch(a.keyCode){case 18:case 20:case 93:case 17:case 40:case 35:case 27:case 36:case 45:case 37:case 224:case 91:case 144:case 12:case 34:case 33:case 19:case 255:case 44:case 39:case 145:case 16:case 38:case 252:case 224:case 92:return!1;case 0:return!gvjs_sg;default:return 166>a.keyCode||183<a.keyCode}}
function gvjs_fO(a,b){var c=gvjs_Iy(a,b);if(0<=c)return b;c=-(c+1);if(0==c)return a[0];if(c==a.length)return gvjs_Ae(a);var d=a[c-1];a=a[c];return Math.abs(b-d)<=Math.abs(b-a)?d:a}var gvjs_gO={};function gvjs_hO(){gvjs_0E.call(this);this.cr=[]}gvjs_t(gvjs_hO,gvjs_0E);gvjs_hO.prototype.add=function(a){gvjs_He(this.cr,a)||(this.cr.push(a),gvjs_G(a,gvjs_vu,this.yda,!1,this))};gvjs_hO.prototype.remove=function(a){gvjs_Ie(this.cr,a)&&gvjs_ji(a,gvjs_vu,this.yda,!1,this)};
gvjs_hO.prototype.M=function(){this.cr.forEach(function(a){a.pa()});this.cr.length=0;gvjs_hO.G.M.call(this)};function gvjs_iO(){gvjs_hO.call(this);this.IY=0}gvjs_t(gvjs_iO,gvjs_hO);gvjs_iO.prototype.play=function(a){if(0==this.cr.length)return!1;if(a||this.Ef())this.IY=0,this.jK();else if(this.So())return!1;this.Jh("play");-1==this.K&&this.Jh("resume");var b=-1==this.K&&!a;this.startTime=gvjs_se();this.endTime=null;this.K=1;this.cr.forEach(function(c){b&&-1!=c.K||c.play(a)});return!0};
gvjs_iO.prototype.pause=function(){this.So()&&(this.cr.forEach(function(a){a.So()&&a.pause()}),this.K=-1,this.Jh("pause"))};gvjs_iO.prototype.stop=function(a){this.cr.forEach(function(b){b.Ef()||b.stop(a)});this.K=0;this.endTime=gvjs_se();this.Jh(gvjs__p);this.Xz()};gvjs_iO.prototype.yda=function(){this.IY++;this.IY==this.cr.length&&(this.endTime=gvjs_se(),this.K=0,this.Jh(gvjs_vu),this.Xz())};function gvjs_jO(a,b,c,d,e){gvjs_1E.call(this,b,c,d,e);this.element=a}gvjs_t(gvjs_jO,gvjs_1E);gvjs_=gvjs_jO.prototype;
gvjs_.aB=gvjs_ke;gvjs_.gh=function(){void 0===this.gr&&(this.gr=gvjs_Gz(this.element));return this.gr};gvjs_.M1=function(){this.aB();gvjs_jO.G.M1.call(this)};gvjs_.Xz=function(){this.aB();gvjs_jO.G.Xz.call(this)};gvjs_.jK=function(){this.aB();gvjs_jO.G.jK.call(this)};function gvjs_kO(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error(gvjs__N);gvjs_jO.call(this,a,b,c,d,e)}gvjs_t(gvjs_kO,gvjs_jO);
gvjs_kO.prototype.aB=function(){var a=this.bB&&this.gh()?gvjs_j:gvjs_$c;this.element.style[a]=Math.round(this.coords[0])+gvjs_T;this.element.style.top=Math.round(this.coords[1])+gvjs_T};function gvjs_lO(a,b,c,d,e){gvjs_jO.call(this,a,[b],[c],d,e)}gvjs_t(gvjs_lO,gvjs_jO);gvjs_lO.prototype.aB=function(){this.element.style.width=Math.round(this.coords[0])+gvjs_T};function gvjs_mO(a,b,c,d,e){gvjs_jO.call(this,a,[b],[c],d,e)}gvjs_t(gvjs_mO,gvjs_jO);
gvjs_mO.prototype.aB=function(){this.element.style.height=Math.round(this.coords[0])+gvjs_T};function gvjs_nO(){gvjs_H.call(this)}gvjs_t(gvjs_nO,gvjs_H);gvjs_=gvjs_nO.prototype;gvjs_.$d=0;gvjs_.$o=0;gvjs_.pn=100;gvjs_.Ll=0;gvjs_.sj=1;gvjs_.Wk=!1;gvjs_.Nz=!1;gvjs_.Wa=function(a){a=gvjs_oO(this,a);this.$d!=a&&(this.$d=a+this.Ll>this.pn?this.pn-this.Ll:a<this.$o?this.$o:a,this.Wk||this.Nz||this.dispatchEvent(gvjs_Kt))};gvjs_.getValue=function(){return gvjs_oO(this,this.$d)};
gvjs_.rT=function(a){a=gvjs_oO(this,a);this.Ll!=a&&(this.Ll=0>a?0:this.$d+a>this.pn?this.pn-this.$d:a,this.Wk||this.Nz||this.dispatchEvent(gvjs_Kt))};gvjs_.Tl=function(){var a=this.Ll;return null==this.sj?a:Math.round(a/this.sj)*this.sj};gvjs_.Ow=function(a){if(this.$o!=a){var b=this.Wk;this.Wk=!0;this.$o=a;a+this.Ll>this.pn&&(this.Ll=this.pn-this.$o);a>this.$d&&this.Wa(a);a>this.pn&&(this.Ll=0,this.bu(a),this.Wa(a));(this.Wk=b)||this.Nz||this.dispatchEvent(gvjs_Kt)}};
gvjs_.lf=function(){return gvjs_oO(this,this.$o)};gvjs_.bu=function(a){a=gvjs_oO(this,a);if(this.pn!=a){var b=this.Wk;this.Wk=!0;this.pn=a;a<this.$d+this.Ll&&this.Wa(a-this.Ll);a<this.$o&&(this.Ll=0,this.Ow(a),this.Wa(this.pn));a<this.$o+this.Ll&&(this.Ll=this.pn-this.$o);(this.Wk=b)||this.Nz||this.dispatchEvent(gvjs_Kt)}};gvjs_.kf=function(){return gvjs_oO(this,this.pn)};gvjs_.vI=function(){return this.sj};
gvjs_.ET=function(a){this.sj!=a&&(this.sj=a,a=this.Wk,this.Wk=!0,this.bu(this.kf()),this.rT(this.Tl()),this.Wa(this.getValue()),(this.Wk=a)||this.Nz||this.dispatchEvent(gvjs_Kt))};function gvjs_oO(a,b){return null==a.sj?b:a.$o+Math.round((b-a.$o)/a.sj)*a.sj}function gvjs_pO(a,b){gvjs_MC.call(this,a);this.T6=null;this.Qe=new gvjs_nO;this.Bsa=b||gvjs_ye;this.ioa=!0;gvjs_G(this.Qe,gvjs_Kt,this.zaa,!1,this)}gvjs_t(gvjs_pO,gvjs_MC);gvjs_=gvjs_pO.prototype;gvjs_.tb=gvjs_S;gvjs_.uQ=!1;gvjs_.j1=!1;
gvjs_.Dm=10;gvjs_.vR=0;gvjs_.Gba=!0;gvjs_.bda=0;gvjs_.aja=1E3;gvjs_.kg=!0;gvjs_.Ml=!1;gvjs_.J=function(){gvjs_pO.G.J.call(this);var a=this.wa().J(gvjs_b,this.sa(this.tb));this.vf(a)};
gvjs_.vf=function(a){gvjs_pO.G.vf.call(this,a);gvjs_VC(a,this.sa(this.tb));a=this.j();var b=this.wa().J(gvjs_b,"google-visualization-controls-slider-handle");gvjs_VB(b,gvjs_Bt);this.mC=b;a.appendChild(this.mC);this.Nd=gvjs_qO(this);a.appendChild(this.Nd);this.aj=gvjs_qO(this);a.appendChild(this.aj);a=this.j();gvjs_VB(a,"slider");gvjs_rO(this)};
gvjs_.Nb=function(){gvjs_pO.G.Nb.call(this);this.xm=new gvjs__C(this.Nd);this.qq=new gvjs__C(this.aj);this.xm.pq(this.Ml);this.qq.pq(this.Ml);this.xm.ky=this.qq.ky=gvjs_ke;this.Gf=new gvjs_uD(this.j());gvjs_sO(this,!0);this.j().tabIndex=0;gvjs_tO(this)};
function gvjs_sO(a,b){b?(a.hc().o(a.xm,gvjs_nt,a.JP).o(a.qq,gvjs_nt,a.JP).o(a.xm,[gvjs_2,gvjs_R],a.Jv).o(a.qq,[gvjs_2,gvjs_R],a.Jv).o(a.Gf,gvjs_kv,a.gn).o(a.j(),gvjs_Wt,a.NP).o(a.j(),gvjs_gd,a.NP),a.Gba&&gvjs_uO(a,!0)):(a.hc().Ab(a.xm,gvjs_nt,a.JP).Ab(a.qq,gvjs_nt,a.JP).Ab(a.xm,[gvjs_2,gvjs_R],a.Jv).Ab(a.qq,[gvjs_2,gvjs_R],a.Jv).Ab(a.Gf,gvjs_kv,a.gn).Ab(a.j(),gvjs_Wt,a.NP).Ab(a.j(),gvjs_gd,a.NP),a.Gba&&gvjs_uO(a,!1))}gvjs_.Le=function(){gvjs_pO.G.Le.call(this);gvjs_cO(this.xm,this.qq,this.Gf,this.qn)};
gvjs_.JP=function(a){var b=a.eY==this.xm?this.Nd:this.aj;if(this.tb==gvjs_U){var c=this.j().clientHeight-b.offsetHeight;c=(c-a.top)/c*(this.kf()-this.lf())+this.lf()}else c=this.j().clientWidth-b.offsetWidth,c=a.left/c*(this.kf()-this.lf())+this.lf();c=a.eY==this.xm?Math.min(Math.max(c,this.lf()),this.getValue()+this.Tl()):Math.min(Math.max(c,this.getValue()),this.kf());gvjs_vO(this,b,c)};
gvjs_.Jv=function(a){var b=a.type==gvjs_2;gvjs_ZC(this.j(),"goog-slider-dragging",b);gvjs_ZC(a.target.SC,"goog-slider-thumb-dragging",b);a=a.eY==this.xm;b?(this.dispatchEvent("e"),this.dispatchEvent(a?"a":"c")):(this.dispatchEvent("f"),this.dispatchEvent(a?"b":"d"))};
gvjs_.gn=function(a){var b=!0;switch(a.keyCode){case 36:gvjs_wO(this,this.lf());break;case 35:gvjs_wO(this,this.kf());break;case 33:gvjs_xO(this,this.Dm);break;case 34:gvjs_xO(this,-this.Dm);break;case 37:var c=this.Ml&&this.gh()?1:-1;gvjs_xO(this,a.shiftKey?c*this.Dm:c*this.ZA);break;case 40:gvjs_xO(this,a.shiftKey?-this.Dm:-this.ZA);break;case 39:c=this.Ml&&this.gh()?-1:1;gvjs_xO(this,a.shiftKey?c*this.Dm:c*this.ZA);break;case 38:gvjs_xO(this,a.shiftKey?this.Dm:this.ZA);break;default:b=!1}b&&a.preventDefault()};
gvjs_.NP=function(a){this.ioa&&this.j().focus&&this.j().focus();var b=a.target;gvjs_rh(this.Nd,b)||gvjs_rh(this.aj,b)||(b=a.type==gvjs_Wt,b&&Date.now()<this.bda+this.aja||(b||(this.bda=Date.now()),this.j1?gvjs_wO(this,gvjs_yO(this,a)):(this.O4(a),this.On=gvjs_zO(this,gvjs_yO(this,a)),this.lba=this.tb==gvjs_U?this.Bz<this.On.offsetTop:this.Bz>gvjs_AO(this,this.On)+this.On.offsetWidth,a=gvjs_5g(this.j()),this.hc().o(a,gvjs_md,this.M4,!0).o(this.j(),gvjs_jd,this.O4),this.Sv||(this.Sv=new gvjs_IA(200),
this.hc().o(this.Sv,gvjs_dx,this.Faa)),this.Faa(),this.Sv.start())))};gvjs_.vaa=function(a){gvjs_xO(this,(0<a.detail?-1:1)*this.ZA);a.preventDefault()};
gvjs_.Faa=function(){var a;if(this.tb==gvjs_U){var b=this.Bz,c=this.On.offsetTop;this.lba?b<c&&(a=gvjs_BO(this,this.On)+this.Dm):b>c+this.On.offsetHeight&&(a=gvjs_BO(this,this.On)-this.Dm)}else b=this.Bz,c=gvjs_AO(this,this.On),this.lba?b>c+this.On.offsetWidth&&(a=gvjs_BO(this,this.On)+this.Dm):b<c&&(a=gvjs_BO(this,this.On)-this.Dm);void 0!==a&&gvjs_vO(this,this.On,a)};gvjs_.M4=function(){this.Sv&&this.Sv.stop();var a=gvjs_5g(this.j());this.hc().Ab(a,gvjs_md,this.M4,!0).Ab(this.j(),gvjs_jd,this.O4)};
function gvjs_CO(a,b){b=gvjs_Az(b,a.j());return a.tb==gvjs_U?b.y:a.Ml&&a.gh()?a.j().clientWidth-b.x:b.x}gvjs_.O4=function(a){this.Bz=gvjs_CO(this,a)};function gvjs_yO(a,b){var c=a.lf(),d=a.kf();if(a.tb==gvjs_U){var e=a.Nd.offsetHeight,f=a.j().clientHeight-e;a=gvjs_CO(a,b)-e/2;return(d-c)*(f-a)/f+c}e=a.Nd.offsetWidth;f=a.j().clientWidth-e;a=gvjs_CO(a,b)-e/2;return(d-c)*a/f+c}
function gvjs_BO(a,b){if(b==a.Nd)return a.Qe.getValue();if(b==a.aj)return a.Qe.getValue()+a.Qe.Tl();throw Error("Illegal thumb element. Neither minThumb nor maxThumb");}function gvjs_xO(a,b){Math.abs(b)<a.vI()&&(b=gvjs_$y(b)*a.vI());var c=gvjs_BO(a,a.Nd)+b;b=gvjs_BO(a,a.aj)+b;c=gvjs_0g(c,a.lf(),a.kf()-a.vR);b=gvjs_0g(b,a.lf()+a.vR,a.kf());gvjs_DO(a,c,b-c)}
function gvjs_vO(a,b,c){var d=gvjs_oO(a.Qe,c);c=b==a.Nd?d:a.Qe.getValue();b=b==a.aj?d:a.Qe.getValue()+a.Qe.Tl();c>=a.lf()&&b>=c+a.vR&&a.kf()>=b&&gvjs_DO(a,c,b-c)}function gvjs_DO(a,b,c){a.lf()<=b&&b<=a.kf()-c&&a.vR<=c&&c<=a.kf()-b&&(b!=a.getValue()||c!=a.Tl())&&(a.Qe.Nz=!0,a.Qe.rT(0),a.Qe.Wa(b),a.Qe.rT(c),a.Qe.Nz=!1,a.zaa(null))}gvjs_.lf=function(){return this.Qe.lf()};gvjs_.Ow=function(a){this.Qe.Ow(a)};gvjs_.kf=function(){return this.Qe.kf()};gvjs_.bu=function(a){this.Qe.bu(a)};
function gvjs_zO(a,b){return b<=a.Qe.getValue()+a.Qe.Tl()/2?a.Nd:a.aj}gvjs_.zaa=function(){gvjs_tO(this);gvjs_rO(this);this.dispatchEvent(gvjs_Kt)};
function gvjs_tO(a){if(a.Nd&&!a.uQ){var b=gvjs_EO(a,gvjs_BO(a,a.Nd)),c=gvjs_EO(a,gvjs_BO(a,a.aj));if(a.tb==gvjs_U)a.Nd.style.top=b.y+gvjs_T,a.aj.style.top=c.y+gvjs_T,a.tg&&(b=gvjs_FO(c.y,b.y,a.Nd.offsetHeight),a.tg.style.top=b.offset+gvjs_T,a.tg.style.height=b.size+gvjs_T);else{var d=a.Ml&&a.gh()?gvjs_j:gvjs_$c;a.Nd.style[d]=b.x+gvjs_T;a.aj.style[d]=c.x+gvjs_T;a.tg&&(b=gvjs_FO(b.x,c.x,a.Nd.offsetWidth),a.tg.style[d]=b.offset+gvjs_T,a.tg.style.width=b.size+gvjs_T)}}}
function gvjs_FO(a,b,c){var d=Math.ceil(c/2);return{offset:a+d,size:Math.max(b-a+c-2*d,0)}}function gvjs_EO(a,b){var c=new gvjs_z;if(a.Nd){var d=a.lf(),e=a.kf();b=b==d&&d==e?0:(b-d)/(e-d);a.tb==gvjs_U?(d=a.Nd.offsetHeight,d=a.j().clientHeight-d,b=Math.round(b*d),c.x=a.j1?0:gvjs_AO(a,a.Nd),c.y=d-b):(d=a.j().clientWidth-a.Nd.offsetWidth,c.x=Math.round(b*d),c.y=a.j1?0:a.Nd.offsetTop)}return c}
function gvjs_wO(a,b){b=gvjs_0g(b,a.lf(),a.kf());a.uQ&&(a.tH.stop(!0),a.tH.pa());var c=new gvjs_iO,d=gvjs_zO(a,b),e=a.getValue(),f=a.Tl(),g=gvjs_BO(a,d),h=gvjs_EO(a,g);var k=a.vI();Math.abs(b-g)<k&&(b=gvjs_0g(g+(b>g?k:-k),a.lf(),a.kf()));gvjs_vO(a,d,b);g=gvjs_EO(a,gvjs_BO(a,d));k=a.tb==gvjs_U?[gvjs_AO(a,d),g.y]:[g.x,d.offsetTop];h=new gvjs_kO(d,[h.x,h.y],k,100);h.pq(a.Ml);c.add(h);a.tg&&gvjs_cia(a,d,e,f,g,c);a.T6&&a.T6.yCa(e,b,100).forEach(function(l){c.add(l)});a.tH=c;a.hc().o(c,gvjs_R,a.Lna);a.uQ=
!0;c.play(!1)}
function gvjs_cia(a,b,c,d,e,f){var g=gvjs_EO(a,c),h=gvjs_EO(a,c+d);c=g;d=h;b==a.Nd?c=e:d=e;a.tb==gvjs_U?(b=gvjs_FO(h.y,g.y,a.Nd.offsetHeight),g=gvjs_FO(d.y,c.y,a.Nd.offsetHeight),e=new gvjs_kO(a.tg,[gvjs_AO(a,a.tg),b.offset],[gvjs_AO(a,a.tg),g.offset],100),b=new gvjs_mO(a.tg,b.size,g.size,100),e.pq(a.Ml),b.pq(a.Ml),f.add(e),f.add(b)):(b=gvjs_FO(g.x,h.x,a.Nd.offsetWidth),g=gvjs_FO(c.x,d.x,a.Nd.offsetWidth),e=new gvjs_kO(a.tg,[b.offset,a.tg.offsetTop],[g.offset,a.tg.offsetTop],100),b=new gvjs_lO(a.tg,
b.size,g.size,100),e.pq(a.Ml),b.pq(a.Ml),f.add(e),f.add(b))}gvjs_.Lna=function(){this.uQ=!1;this.dispatchEvent("g")};gvjs_.setOrientation=function(a){if(this.tb!=a){var b=this.sa(this.tb),c=this.sa(a);this.tb=a;this.j()&&(a=this.j(),gvjs_UC(a,b)&&(gvjs_XC(a,b),gvjs_VC(a,c)),b=this.Ml&&this.gh()?gvjs_j:gvjs_$c,this.Nd.style[b]=this.Nd.style.top="",this.aj.style[b]=this.aj.style.top="",this.tg&&(this.tg.style[b]=this.tg.style.top="",this.tg.style.width=this.tg.style.height=""),gvjs_tO(this))}};
gvjs_.vi=function(){return this.tb};gvjs_.M=function(){gvjs_pO.G.M.call(this);this.Sv&&this.Sv.pa();delete this.Sv;this.tH&&this.tH.pa();delete this.tH;delete this.Nd;delete this.aj;this.tg&&delete this.tg;this.Qe.pa();delete this.Qe;this.Gf&&(this.Gf.pa(),delete this.Gf);this.qn&&(this.qn.pa(),delete this.qn);this.xm&&(this.xm.pa(),delete this.xm);this.qq&&(this.qq.pa(),delete this.qq)};gvjs_.ZA=1;gvjs_.vI=function(){return this.Qe.vI()};gvjs_.ET=function(a){this.Qe.ET(a)};gvjs_.getValue=function(){return this.Qe.getValue()};
gvjs_.Wa=function(a){gvjs_vO(this,this.Nd,a)};gvjs_.Tl=function(){return this.Qe.Tl()};gvjs_.rT=function(a){gvjs_vO(this,this.aj,this.Qe.getValue()+a)};gvjs_.setVisible=function(a){gvjs_6(this.j(),a);a&&gvjs_tO(this)};function gvjs_rO(a){var b=a.j();b&&(gvjs_WB(b,"valuemin",a.lf()),gvjs_WB(b,"valuemax",a.kf()),gvjs_WB(b,"valuenow",a.getValue()),gvjs_WB(b,"valuetext",a.Bsa(a.getValue())||""))}
function gvjs_uO(a,b){b?(a.qn||(a.qn=new gvjs_TE(a.j())),a.hc().o(a.qn,gvjs_Wv,a.vaa,{passive:!1})):a.hc().Ab(a.qn,gvjs_Wv,a.vaa,{passive:!1})}gvjs_.Gb=function(a){this.kg!=a&&this.dispatchEvent(a?gvjs_qu:gvjs_ju)&&(this.kg=a,gvjs_sO(this,a),a||this.M4(),gvjs_ZC(this.j(),"goog-slider-disabled",!a))};gvjs_.isEnabled=function(){return this.kg};function gvjs_AO(a,b){return a.Ml?gvjs_3A(b):b.offsetLeft}var gvjs_dia={MM:gvjs_U,IM:gvjs_S};
function gvjs_GO(a){gvjs_eO.call(this,a);this.GT=[]}gvjs_o(gvjs_GO,gvjs_eO);gvjs_GO.prototype.Mt=function(){this.clear();this.GT=this.Zc().fa("setters")||[]};gvjs_GO.prototype.apply=function(){return this.UV(this.mb(),this.Zc(),this.getState())};gvjs_GO.prototype.UV=function(a,b,c){gvjs_u(this.nP(),function(d){gvjs_u(this.GT,function(e){d.setProperty(e.output,c[e.input])},this)},this);return a};function gvjs_HO(a){gvjs_GO.call(this,a);this.Cb=this.Xa=null}gvjs_o(gvjs_HO,gvjs_GO);gvjs_HO.prototype.Xl=function(a,b){a=gvjs_GO.prototype.Xl.call(this,a,b);a.minValue=this.Xa;a.maxValue=this.Cb;null==a.label&&(a.label="");return a};gvjs_HO.prototype.Mt=function(a,b,c){this.Xa=gvjs_L(b,gvjs_ed);this.Cb=gvjs_L(b,gvjs_cd);this.GT=[{input:"lowValue",bg:gvjs_J(b,"lowKey")},{input:"highValue",bg:gvjs_J(b,"highKey")}];this.mM(c)};
gvjs_HO.prototype.mM=function(a){if(a.lowThumbAtMinimum)a.lowValue=this.Xa;else{var b=gvjs_jg(String(a.lowValue));isNaN(b)&&(b=Number.NEGATIVE_INFINITY);a.lowValue=gvjs_0g(b,this.Xa,this.Cb)}a.highThumbAtMaximum?a.highValue=this.Cb:(b=gvjs_jg(String(a.highValue)),isNaN(b)&&(b=Number.POSITIVE_INFINITY),a.highValue=gvjs_0g(b,this.Xa,this.Cb))};function gvjs_IO(a){gvjs_eO.call(this,a)}gvjs_o(gvjs_IO,gvjs_eO);gvjs_IO.prototype.xB=function(){return this.apply()};gvjs_IO.prototype.apply=function(){if(!this.mb())throw Error(gvjs_ZN);return this.pG(this.mb(),this.Zc(),this.getState())};gvjs_IO.prototype.pG=function(a){return new gvjs_N(a)};function gvjs_JO(a){gvjs_eO.call(this,a);this.ye=-1;this.Cb=this.Xa=this.sq=null}gvjs_o(gvjs_JO,gvjs_IO);gvjs_JO.prototype.yT=function(a){this.Xa=a};gvjs_JO.prototype.xT=function(a){this.Cb=a};function gvjs_KO(a,b){if(b.lowThumbAtMinimum)b.lowValue=a.Xa;else{var c=a.U5(b.lowValue);isNaN(c)&&(c=Number.NEGATIVE_INFINITY);b.lowValue=gvjs_0g(c,a.Xa,a.Cb)}b.highThumbAtMaximum?b.highValue=a.Cb:(c=a.U5(b.highValue),isNaN(c)&&(c=Number.POSITIVE_INFINITY),b.highValue=gvjs_0g(c,a.Xa,a.Cb))}
gvjs_JO.prototype.pG=function(a,b,c){a=new gvjs_N(a);b={column:this.ye,test:this.rZ(b,c.lowValue.valueOf(),c.highValue.valueOf())};a.pp(a.at([b]));return a};gvjs_JO.prototype.rZ=function(a,b,c){return function(d){return b<=d&&c>=d}};function gvjs_LO(a){gvjs_pO.call(this,a)}gvjs_o(gvjs_LO,gvjs_pO);gvjs_LO.prototype.sa=function(a){return a==gvjs_U?"google-visualization-controls-slider-vertical":"google-visualization-controls-slider-horizontal"};gvjs_LO.prototype.Nb=function(){gvjs_pO.prototype.Nb.call(this);this.hc().o(this,gvjs_Kt,gvjs_s(this.dha,this));this.dha()};
gvjs_LO.prototype.dha=function(){var a=gvjs_bO(this.Nd),b=gvjs_bO(this.aj);this.vi()==gvjs_U?(this.mC.style.height=gvjs_rz(Math.abs(b.y-a.y),!0),this.mC.style.top=Math.min(b.y,a.y)+gvjs_T):(gvjs_Bz(this.mC,Math.abs(b.x-a.x)),this.mC.style.left=Math.min(b.x,a.x)+gvjs_T)};function gvjs_qO(a){a=a.wa().J(gvjs_b,"google-visualization-controls-slider-thumb");gvjs_VB(a,gvjs_Bt);return a}gvjs_LO.prototype.mC=null;function gvjs_MO(a){gvjs_dO.call(this,a);this.Op=this.tm=0}gvjs_o(gvjs_MO,gvjs_dO);gvjs_=gvjs_MO.prototype;gvjs_.M=function(){gvjs_E(this.tm);gvjs_E(this.Fc);gvjs_dO.prototype.M.call(this)};gvjs_.getState=function(){if(!this.Fc)return{lowValue:null,highValue:null,lowThumbAtMinimum:null,highThumbAtMaxium:null};var a=this.Fc.getValue(),b=this.Fc.Tl();return{lowValue:a+this.Op,highValue:a+b+this.Op,lowThumbAtMinimum:a===this.Fc.lf(),highThumbAtMaximum:a+b===this.Fc.kf()}};
function gvjs_NO(){return gvjs_4(gvjs_6a,{"class":"google-visualization-controls-rangefilter-thumblabel"},"-")}gvjs_.uxa=function(){this.K5();this.tm&&gvjs_ql(this.tm);this.tm=gvjs_pl(function(){this.tm=0;gvjs_I(this,gvjs_9N,null)},200,this)};
function gvjs_OO(a,b,c,d,e){var f=gvjs_K(d,"showRangeValues");e=gvjs_J(d,gvjs_9v,e.orientation,gvjs_dia);var g=new gvjs_MC;b.addChild(g,!0);gvjs_VC(g.j(),gvjs_Y);f&&(e===gvjs_S?(a.hw=gvjs_NO(),g.ib().appendChild(a.hw)):(a.Pv=gvjs_NO(),g.ib().appendChild(a.Pv)));b=new gvjs_LO;gvjs_E(a.Fc);a.Fc=b;a.Ifa(d);b=a.xZ(d,gvjs_ed);var h=a.xZ(d,gvjs_cd);if(null==b||null==h)throw Error("minValue and maxValue must be specified");c=a.pea(b,h,c);b=c.minValue;h=c.maxValue;c=c.state;a.Op=b;h-=a.Op;c.lowValue-=a.Op;
c.highValue-=a.Op;a.Fc.Ow(0);a.Fc.bu(h);a.Fc.setOrientation(e);b=c.lowThumbAtMinimum?a.Fc.lf():c.lowValue;gvjs_DO(a.Fc,b,c.highThumbAtMaximum?a.Fc.kf():c.highValue-b);g.addChild(a.Fc,!0);f&&(e==gvjs_S?(a.Pv=gvjs_NO(),g.ib().appendChild(a.Pv)):(a.hw=gvjs_NO(),g.ib().appendChild(a.hw)),a.v2&&a.v2(d),a.K5());a.addEventListener(a.Fc,gvjs_Kt,a.uxa,!1,a)}gvjs_.hw=null;gvjs_.Pv=null;gvjs_.Fc=null;function gvjs_PO(a,b){var c=b.fa("filterColumnIndex");if(null!=c)return b=parseInt(c,10),a.Ne(b),b;if(b=gvjs_J(b,"filterColumnLabel")){a:{c=a.$();for(var d=0;d<c;d++)if(a.Ga(d)==b)break a;throw Error("Invalid column label:"+b);}return d}throw Error("Either filterColumnIndex or filterColumnLabel must be specified.");};function gvjs_QO(a){gvjs_eO.call(this,a);this.ye=-1}gvjs_o(gvjs_QO,gvjs_IO);gvjs_=gvjs_QO.prototype;gvjs_.og=function(){return{useFormattedValue:!1,values:null}};gvjs_.Xl=function(a,b){a=gvjs_IO.prototype.Xl.call(this,a,b);null==a.label&&(a.label=this.sq);a.values=this.mc;return a};
gvjs_.Mt=function(a,b,c){this.clear();this.ye=gvjs_PO(a,b);this.sq=a.Ga(this.ye);var d=b.fa("values");if(Array.isArray(d)&&d.length)this.mc=d;else{b=gvjs_K(b,gvjs_$N);d=new Set;for(var e=[],f=0;f<a.ca();f++){var g=b?a.Ha(f,this.ye):a.getValue(f,this.ye);null==g||d.has(g)||(d.add(g),e.push(g))}this.mc=e}this.mM(c)};
gvjs_.mM=function(a){var b=a.selectedValues;if(b){if(!Array.isArray(b))throw Error(gvjs_YN);var c=new Set;gvjs_u(this.mc,function(d){null!=d&&c.add(String(d))});a.selectedValues=gvjs_De(b,function(d){return c.has(String(d))})}};
gvjs_.pG=function(a,b,c){var d=new Set;c=c.selectedValues;if(Array.isArray(c))for(var e=0;e<c.length;e++)null!=c[e]&&d.add(String(c[e]));if(0==d.size)return new gvjs_N(a);c=gvjs_K(b,gvjs_$N);b=[];for(e=0;e<a.ca();e++){if(c)var f=a.Ha(e,this.ye);else f=a.getValue(e,this.ye),null!=f&&(f=String(f));d.has(f)&&b.push(e)}a=new gvjs_N(a);a.pp(b);return a};gvjs_.sq=null;gvjs_.mc=null;function gvjs_RO(a,b,c,d){gvjs_MC.call(this,d);this.Qb=a;this.qsa=b==gvjs_U;this.mwa=c||""}gvjs_t(gvjs_RO,gvjs_MC);gvjs_=gvjs_RO.prototype;gvjs_.Tba=null;gvjs_.iH=null;function gvjs_SO(a){if(!a.label)return null;var b=a.labelStacking==gvjs_U?gvjs_U:gvjs_S,c;a.labelSeparator&&(c=String(a.labelSeparator));return new gvjs_RO(String(a.label),b,c)}
gvjs_.J=function(){var a=this.D.J(gvjs_b);this.H=a;this.Tba=gvjs_4("LABEL","google-visualization-controls-label",this.Qb+this.mwa);a.appendChild(this.Tba);this.iH=gvjs_4(gvjs_b);this.qsa||gvjs_VC(this.iH,gvjs_Y);a.appendChild(this.iH)};gvjs_.Fh=function(){return!1};gvjs_.ib=function(){return this.iH};gvjs_.addElement=function(a){this.iH.appendChild(a)};function gvjs_TO(a,b){this.$d=a;this.Pca=b}gvjs_TO.prototype.Dd=function(){return this.Pca.Dd(this)};gvjs_TO.prototype.getId=function(){return this.Pca.getId(this)};gvjs_TO.prototype.get=function(){return this.$d};function gvjs_eia(a,b){return a.Dd().localeCompare(b.Dd())}function gvjs_UO(){}gvjs_UO.prototype.Dd=function(a){return String(a.get())};gvjs_UO.prototype.getId=function(a){return String(a.get())};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
function gvjs_VO(){this.Dca=null;this.Eh=!1;this.Z9=void 0;this.qa=new gvjs_aj;this.pc=new gvjs_WO("",void 0);this.pc.next=this.pc.Ji=this.pc}function gvjs_XO(a,b){(b=a.qa.get(b))&&a.Eh&&(b.remove(),gvjs_YO(a,b));return b}gvjs_=gvjs_VO.prototype;gvjs_.get=function(a,b){return(a=gvjs_XO(this,a))?a.value:b};gvjs_.set=function(a,b){var c=gvjs_XO(this,a);c?c.value=b:(c=new gvjs_WO(a,b),this.qa.set(a,c),gvjs_YO(this,c))};gvjs_.peek=function(){return this.pc.next.value};
gvjs_.shift=function(){return gvjs_ZO(this,this.pc.next)};gvjs_.pop=function(){return gvjs_ZO(this,this.pc.Ji)};gvjs_.remove=function(a){return(a=this.qa.get(a))?(this.removeNode(a),!0):!1};gvjs_.removeNode=function(a){a.remove();this.qa.remove(a.key)};gvjs_.Cd=function(){return this.qa.Cd()};gvjs_.isEmpty=function(){return this.qa.isEmpty()};gvjs_.cj=function(){return this.map(function(a,b){return b})};gvjs_.ob=function(){return this.map(function(a){return a})};
gvjs_.contains=function(a){return this.some(function(b){return b==a})};gvjs_.tf=function(a){return this.qa.tf(a)};gvjs_.clear=function(){gvjs__O(this,0)};gvjs_.forEach=function(a,b){for(var c=this.pc.next;c!=this.pc;c=c.next)a.call(b,c.value,c.key,this)};gvjs_.map=function(a,b){for(var c=[],d=this.pc.next;d!=this.pc;d=d.next)c.push(a.call(b,d.value,d.key,this));return c};gvjs_.some=function(a,b){for(var c=this.pc.next;c!=this.pc;c=c.next)if(a.call(b,c.value,c.key,this))return!0;return!1};
gvjs_.every=function(a,b){for(var c=this.pc.next;c!=this.pc;c=c.next)if(!a.call(b,c.value,c.key,this))return!1;return!0};function gvjs_YO(a,b){a.Eh?(b.next=a.pc.next,b.Ji=a.pc,a.pc.next=b,b.next.Ji=b):(b.Ji=a.pc.Ji,b.next=a.pc,a.pc.Ji=b,b.Ji.next=b);null!=a.Dca&&gvjs__O(a,a.Dca)}function gvjs__O(a,b){for(;a.Cd()>b;){var c=a.Eh?a.pc.Ji:a.pc.next;a.removeNode(c);a.Z9&&a.Z9(c.key,c.value)}}function gvjs_ZO(a,b){a.pc!=b&&a.removeNode(b);return b.value}function gvjs_WO(a,b){this.key=a;this.value=b}
gvjs_WO.prototype.remove=function(){this.Ji.next=this.next;this.next.Ji=this.Ji;delete this.Ji;delete this.next};function gvjs_0O(a){gvjs_H.call(this);this.Hc=null;this.H=a;a=gvjs_y||gvjs_rg||gvjs_tg&&!gvjs_Eg("531")&&a.tagName==gvjs_Vo;this.ea=new gvjs_KA(this);this.ea.o(this.H,a?[gvjs_lv,"paste","cut","drop",gvjs_fv]:gvjs_fv,this)}gvjs_t(gvjs_0O,gvjs_H);
gvjs_0O.prototype.handleEvent=function(a){if(a.type==gvjs_fv)gvjs_y&&gvjs_Eg(10)&&0==a.keyCode&&0==a.charCode||(gvjs_1O(this),this.dispatchEvent(gvjs_2O(a)));else if(a.type!=gvjs_lv||gvjs_bia(a)){var b=a.type==gvjs_lv?this.H.value:null;gvjs_y&&229==a.keyCode&&(b=null);var c=gvjs_2O(a);gvjs_1O(this);this.Hc=gvjs_pl(function(){this.Hc=null;this.H.value!=b&&this.dispatchEvent(c)},0,this)}};function gvjs_1O(a){null!=a.Hc&&(gvjs_ql(a.Hc),a.Hc=null)}
function gvjs_2O(a){a=new gvjs_5h(a.$i);a.type=gvjs_fv;return a}gvjs_0O.prototype.M=function(){gvjs_0O.G.M.call(this);this.ea.pa();gvjs_1O(this);delete this.H};function gvjs_3O(a,b,c){gvjs_1h.call(this,a,b);this.item=c}gvjs_t(gvjs_3O,gvjs_1h);function gvjs_4O(a,b){gvjs_MC.call(this,b);this.Qb=a||""}var gvjs_5O;gvjs_t(gvjs_4O,gvjs_MC);gvjs_=gvjs_4O.prototype;gvjs_.rq=null;gvjs_.Dsa=10;function gvjs_6O(){null==gvjs_5O&&(gvjs_5O=gvjs_7N in gvjs_dh(gvjs_Na));return gvjs_5O}gvjs_.WC=!1;gvjs_.J=function(){this.H=this.wa().J(gvjs_Na,{type:gvjs_m})};
gvjs_.vf=function(a){gvjs_4O.G.vf.call(this,a);this.Qb||(this.Qb=a.getAttribute(gvjs_8c)||"");gvjs_Tx(gvjs_5g(a))==a&&(this.WC=!0,a=this.j(),gvjs_XC(a,this.uJ));gvjs_6O()&&(this.j().placeholder=this.Qb);a=this.j();gvjs_WB(a,gvjs_8c,this.Qb)};
gvjs_.Nb=function(){gvjs_4O.G.Nb.call(this);var a=new gvjs_KA(this);a.o(this.j(),gvjs_xu,this.qaa);a.o(this.j(),gvjs_Yo,this.KP);if(gvjs_6O())this.ea=a;else{gvjs_sg&&a.o(this.j(),[gvjs_7c,gvjs_lv,gvjs_mv],this.aqa);var b=gvjs_5g(this.j());a.o(gvjs_3x(b),"load",this.gra);this.ea=a;gvjs_7O(this)}this.Wp();this.j().lj=this};gvjs_.Le=function(){gvjs_4O.G.Le.call(this);this.ea&&(this.ea.pa(),this.ea=null);this.j().lj=null};
function gvjs_7O(a){!a.ooa&&a.ea&&a.j().form&&(a.ea.o(a.j().form,"submit",a.bqa),a.ooa=!0)}gvjs_.M=function(){gvjs_4O.G.M.call(this);this.ea&&(this.ea.pa(),this.ea=null)};gvjs_.uJ="label-input-label";gvjs_.qaa=function(){this.WC=!0;var a=this.j();gvjs_XC(a,this.uJ);if(!gvjs_6O()&&!gvjs_8O(this)&&!this.Fra){var b=this;a=function(){b.j()&&(b.j().value="")};gvjs_y?gvjs_pl(a,10):a()}};gvjs_.KP=function(){gvjs_6O()||(this.ea.Ab(this.j(),gvjs_Wt,this.qaa),this.rq=null);this.WC=!1;this.Wp()};
gvjs_.aqa=function(a){27==a.keyCode&&(a.type==gvjs_lv?this.rq=this.j().value:a.type==gvjs_7c?this.j().value=this.rq:a.type==gvjs_mv&&(this.rq=null),a.preventDefault())};gvjs_.bqa=function(){gvjs_8O(this)||(this.j().value="",gvjs_pl(this.mpa,10,this))};gvjs_.mpa=function(){gvjs_8O(this)||(this.j().value=this.Qb)};gvjs_.gra=function(){this.Wp()};gvjs_.hasFocus=function(){return this.WC};function gvjs_8O(a){return!!a.j()&&""!=a.j().value&&a.j().value!=a.Qb}
gvjs_.clear=function(){this.j().value="";null!=this.rq&&(this.rq="")};gvjs_.reset=function(){gvjs_8O(this)&&(this.clear(),this.Wp())};gvjs_.Wa=function(a){null!=this.rq&&(this.rq=a);this.j().value=a;this.Wp()};gvjs_.getValue=function(){return null!=this.rq?this.rq:gvjs_8O(this)?this.j().value:""};gvjs_.In=function(a){var b=this.j();gvjs_6O()?(b&&(b.placeholder=a),this.Qb=a):gvjs_8O(this)||(b&&(b.value=""),this.Qb=a,this.Tea());b&&gvjs_WB(b,gvjs_8c,this.Qb)};gvjs_.Dd=function(){return this.Qb};
gvjs_.Wp=function(){var a=this.j();gvjs_6O()?this.j().placeholder!=this.Qb&&(this.j().placeholder=this.Qb):gvjs_7O(this);gvjs_WB(a,gvjs_8c,this.Qb);gvjs_8O(this)?(a=this.j(),gvjs_XC(a,this.uJ)):(this.Fra||this.WC||(a=this.j(),gvjs_VC(a,this.uJ)),gvjs_6O()||gvjs_pl(this.Tea,this.Dsa,this))};gvjs_.Gb=function(a){this.j().disabled=!a;var b=this.j();gvjs_ZC(b,this.uJ+gvjs_Gr,!a)};gvjs_.isEnabled=function(){return!this.j().disabled};
gvjs_.Tea=function(){!this.j()||gvjs_8O(this)||this.WC||(this.j().value=this.Qb)};function gvjs_9O(a,b,c){gvjs_MC.call(this,a);this.lj=c||new gvjs_4O;this.kg=!0;a=this.la=b||new gvjs_kE(this.wa());a.setVisible(!1);a.kG=!1;a.Z6=!0}gvjs_t(gvjs_9O,gvjs_MC);gvjs_=gvjs_9O.prototype;gvjs_.uc=null;gvjs_.rD=null;gvjs_.lj=null;gvjs_.la=null;gvjs_.gB=-1;gvjs_.zi=null;gvjs_.I0=gvjs_hf;gvjs_.LB=null;gvjs_.RX="";gvjs_.doa="";gvjs_.kq=null;gvjs_.iha=!1;
gvjs_.J=function(){this.zi=this.wa().J(gvjs_Na,{name:this.doa,type:gvjs_m,autocomplete:"off"});this.LB=this.wa().J(gvjs_6a,"goog-combobox-button");this.H=this.wa().J(gvjs_6a,"goog-combobox",this.zi,this.LB);this.iha&&(gvjs_th(this.LB,"\u25bc"),gvjs_Hz(this.LB,!0));this.zi.setAttribute(gvjs_8c,this.RX);this.lj.fb(this.zi);this.la.jp(!1);this.la.Bb||this.addChild(this.la,!0)};
gvjs_.Gb=function(a){this.kg=a;this.lj.Gb(a);gvjs_ZC(this.j(),"goog-combobox-disabled",!a)};gvjs_.isEnabled=function(){return this.kg};gvjs_.Nb=function(){gvjs_9O.G.Nb.call(this);var a=this.hc();a.o(this.j(),gvjs_gd,this.lua);a.o(this.wa().kc(),gvjs_gd,this.mua);a.o(this.zi,gvjs_Yo,this.tua);this.Gf=new gvjs_uD(this.zi);a.o(this.Gf,gvjs_kv,this.gj);this.uc=new gvjs_0O(this.zi);a.o(this.uc,gvjs_fv,this.uua);a.o(this.la,gvjs_Ss,this.wua)};
gvjs_.Le=function(){this.Gf.pa();delete this.Gf;this.uc.pa();this.uc=null;gvjs_9O.G.Le.call(this)};gvjs_.Fh=function(){return!1};gvjs_.M=function(){gvjs_9O.G.M.call(this);this.JN();this.lj.pa();this.la.pa();this.LB=this.zi=this.la=this.lj=null};gvjs_.eC=function(){this.JN();gvjs_$O(this);this.la.Tg(-1)};gvjs_.Bj=function(a){this.la.addChild(a,!0);this.gB=-1};gvjs_.Bu=function(a,b){this.la.zx(a,b,!0);this.gB=-1};gvjs_.removeItem=function(a){if(a=this.la.removeChild(a,!0))a.pa(),this.gB=-1};
gvjs_.od=function(a){return this.la.Ye(a)};gvjs_.bh=function(){return this.la.ze()};gvjs_.Td=function(){return this.la};gvjs_.Wa=function(a){this.lj.getValue()!=a&&(this.lj.Wa(a),this.MP())};gvjs_.getValue=function(){return this.lj.getValue()};
function gvjs_aP(a,b){var c=a.la.isVisible(),d;if(-1==a.gB){for(var e=d=0,f=a.la.ze();e<f;e++)a.la.Ye(e).isVisible()&&d++;a.gB=d}d=a.gB;c&&0==d?gvjs_$O(a):!c&&0<d&&(b&&(a.mL(""),a.vT(gvjs_kf(a.lj.getValue().toLowerCase()))),gvjs_pl(a.JN,1,a),a.la.setVisible(!0),gvjs_VC(a.j(),gvjs_0N));a.mS()}gvjs_.mS=function(){this.la&&this.la.isVisible()&&(new gvjs_1D(this.j(),9,!0)).Mf(this.la.j(),8)};function gvjs_$O(a){a.la.setVisible(!1);gvjs_XC(a.j(),gvjs_0N)}
gvjs_.JN=function(){this.kq&&(gvjs_ql(this.kq),this.kq=null)};gvjs_.lua=function(a){this.kg&&(a.target==this.j()||a.target==this.zi||gvjs_rh(this.LB,a.target))&&(this.la.isVisible()?this.eC():(gvjs_aP(this,!0),gvjs_qg&&this.zi.focus(),this.zi.select(),this.la.Uq=!0,a.preventDefault()));a.stopPropagation()};gvjs_.mua=function(a){gvjs_rh(this.la.j(),a.target)||this.eC()};
gvjs_.wua=function(a){var b=a.target;this.dispatchEvent(new gvjs_3O(gvjs_Ss,this,b))&&(b=b.bj(),this.lj.getValue()!=b&&(this.lj.Wa(b),this.dispatchEvent(gvjs_Kt)),this.eC());a.stopPropagation()};gvjs_.tua=function(){this.JN();this.kq=gvjs_pl(this.eC,250,this)};
gvjs_.gj=function(a){var b=this.la.isVisible();if(b&&this.la.gj(a))return!0;var c=!1;switch(a.keyCode){case 27:b&&(this.eC(),c=!0);break;case 9:b&&(b=gvjs_aE(this.la))&&(b.$h(a),c=!0);break;case 38:case 40:b||(gvjs_aP(this,!0),c=!0)}c&&a.preventDefault();return c};gvjs_.uua=function(){this.MP()};gvjs_.MP=function(){var a=gvjs_kf(this.lj.getValue().toLowerCase());this.mL(a);gvjs_Tx(this.wa().kc())==this.zi&&gvjs_aP(this,!1);var b=gvjs_aE(this.la);""!=a&&b&&b.isVisible()||this.vT(a);this.rD=a;this.dispatchEvent(gvjs_Kt)};
gvjs_.mL=function(a){for(var b=!1,c=0,d=!this.I0(a,this.rD),e=0,f=this.la.ze();e<f;e++){var g=this.la.Ye(e);if(g instanceof gvjs_ZD){if(!g.isVisible()&&!d)continue;var h=g.bj();h=typeof g.rsa==gvjs_d&&g.Pba||h&&this.I0(h.toLowerCase(),a);typeof g.sT==gvjs_d&&g.sT(a);g.setVisible(!!h);b=h||b}else b=g.isVisible()||b;g.isVisible()&&c++}this.gB=c};
gvjs_.vT=function(a){if(""!=a)for(var b=0,c=this.la.ze();b<c;b++){var d=this.la.Ye(b),e=d.bj();if(e&&this.I0(e.toLowerCase(),a)){this.la.Tg(b);d.sT&&d.sT(a);return}}this.la.Tg(-1)};function gvjs_bP(a,b,c,d){gvjs_ZD.call(this,a,b,c,d)}gvjs_t(gvjs_bP,gvjs_ZD);gvjs_HD("goog-combobox-item",function(){return new gvjs_bP(null)});gvjs_bP.prototype.Pba=!1;gvjs_bP.prototype.rsa=function(){return this.Pba};
gvjs_bP.prototype.sT=function(a){if(this.isEnabled()){var b=this.bj(),c=b.toLowerCase().indexOf(a);if(0<=c){var d=this.wa();this.setContent([d.createTextNode(b.substr(0,c)),d.J("B",null,b.substr(c,a.length)),d.createTextNode(b.substr(c+a.length))])}}};function gvjs_cP(){}gvjs_t(gvjs_cP,gvjs_2D);gvjs_le(gvjs_cP);gvjs_=gvjs_cP.prototype;gvjs_.J=function(a){var b=this.Rl(a);b=a.wa().J(gvjs_b,gvjs_Is+b.join(" "),a.getContent());this.il(b,a.en());return b};gvjs_.Qk=function(){return gvjs_Bt};gvjs_.Fh=function(a){return a.tagName==gvjs_b};gvjs_.fb=function(a,b){gvjs_VC(b,gvjs_Y);return gvjs_cP.G.fb.call(this,a,b)};gvjs_.getValue=function(){return""};gvjs_.sa=function(){return gvjs_1N};gvjs_HD(gvjs_1N,function(){return new gvjs_4D(null,gvjs_cP.Lc())});function gvjs_dP(){}gvjs_t(gvjs_dP,gvjs_cP);gvjs_le(gvjs_dP);gvjs_dP.prototype.sa=function(){return gvjs_2N};gvjs_HD(gvjs_2N,function(){return new gvjs_4D(null,gvjs_dP.Lc())});function gvjs_eP(a,b,c){gvjs_ZD.call(this,a,b,c);this.S3(!0)}gvjs_t(gvjs_eP,gvjs_ZD);gvjs_eP.prototype.$h=function(){return this.dispatchEvent(gvjs_Ss)};gvjs_HD(gvjs_Ms,function(){return new gvjs_eP(null)});function gvjs_fP(a){gvjs_dO.call(this,a);this.mc=[];this.ug=new gvjs_VO}gvjs_o(gvjs_fP,gvjs_dO);gvjs_=gvjs_fP.prototype;gvjs_.M=function(){gvjs_E(this.GH);gvjs_dO.prototype.M.call(this)};gvjs_.getState=function(){for(var a={selectedValues:[]},b=this.ug.ob(),c=0;c<b.length;c++)a.selectedValues.push(b[c].get());return a};
gvjs_.draw=function(a,b){b=gvjs_x(b||{});b.caption||(b.caption="Choose a value...");b.valuesMediator=b.valuesMediator||new gvjs_UO;b.cssClass=b.cssClass?String(b.cssClass):"google-visualization-controls-categoryfilter";"allowMultiple"in b||(b.allowMultiple=!0);"allowNone"in b||(b.allowNone=!0);"allowTyping"in b||(b.allowTyping=!0);"sortValues"in b||(b.sortValues=!0);var c=!1,d;for(d in gvjs_gP)if(b.selectedValuesLayout==gvjs_gP[d]){c=!0;break}c||(b.selectedValuesLayout=gvjs_3N);this.m=b;gvjs_fia(this,
a);(a=gvjs_SO(this.m))||(a=new gvjs_MC);a.R(this.getContainer());gvjs_VC(a.j(),this.m.cssClass);gvjs_E(this.GH);this.GH=this.m.allowTyping?this.m.allowMultiple?new gvjs_hP(this):new gvjs_iP(this):this.m.allowMultiple?new gvjs_jP(this):new gvjs_kP(this);this.GH.R(a);this.ug.isEmpty()||this.GH.AE()};
function gvjs_fia(a,b){b=b||{};var c=a.m.valuesMediator,d=new Set;if(null!=b.selectedValues){if(!Array.isArray(b.selectedValues))throw Error(gvjs_YN);a.m.allowMultiple?gvjs_u(b.selectedValues,function(g){d.add((new gvjs_TO(g,c)).getId())}):b.selectedValues.length&&d.add((new gvjs_TO(b.selectedValues[0],c)).getId())}b=Array.isArray(a.m.values)?a.m.values:[];for(var e=0;e<b.length;e++){var f=new gvjs_TO(b[e],c);a.mc.push(f);d.has(f.getId())&&a.ug.set(f.getId(),f)}a.m.sortValues&&gvjs_Qe(a.mc,gvjs_eia);
!gvjs_lP(a)&&0<a.mc.length&&0==a.ug.Cd()&&a.ug.set(a.mc[0].getId(),a.mc[0])}gvjs_.ru=function(){gvjs_I(this,gvjs_9N,null)};function gvjs_mP(a){return a.ug.Cd()==a.mc.length}function gvjs_lP(a){return!!a.m.allowNone}gvjs_.m=null;gvjs_.GH=null;var gvjs_gP={vza:gvjs_3N,Aza:gvjs_qt,Cza:"belowWrapping",Bza:gvjs_4N};function gvjs_nP(a){gvjs_F.call(this);this.bc=a;this.Ce=null}gvjs_o(gvjs_nP,gvjs_F);gvjs_=gvjs_nP.prototype;gvjs_.M=function(){gvjs_E(this.Ce);gvjs_F.prototype.M.call(this)};
gvjs_.R=function(a){gvjs_E(this.Ce);this.Ce=new gvjs_DE(this.bc.m.caption);this.sX();a.addChild(this.Ce,!0);this.bc.addEventListener(this.Ce,gvjs_Ss,this.No,!1,this);this.Ce.Gb(0<this.bc.mc.length)};gvjs_.sX=function(){for(var a=this.bc.mc,b=0;b<a.length;b++)this.Ce.Bj(new gvjs_eP(a[b].Dd(),a[b]))};gvjs_.AE=function(){};gvjs_.No=function(){this.bc.ru()};function gvjs_kP(a){gvjs_nP.call(this,a)}gvjs_o(gvjs_kP,gvjs_nP);
gvjs_kP.prototype.sX=function(){var a=this.bc;gvjs_lP(a)&&this.Ce.Bj(new gvjs_eP(a.m.caption));gvjs_nP.prototype.sX.call(this)};gvjs_kP.prototype.AE=function(){for(var a=this.bc.ug.ob()[0],b=0,c=this.Ce.bh();b<c;b++)if(this.Ce.od(b).Zh==a){this.Ce.rk(b);break}};gvjs_kP.prototype.No=function(a){this.bc.ug.clear();var b=this.Ce.Be().Zh;b&&this.bc.ug.set(b.getId(),b);gvjs_nP.prototype.No.call(this,a)};function gvjs_jP(a){gvjs_nP.call(this,a);this.pk=null}gvjs_o(gvjs_jP,gvjs_nP);gvjs_=gvjs_jP.prototype;
gvjs_.M=function(){gvjs_E(this.pk);gvjs_nP.prototype.M.call(this)};gvjs_.R=function(a){gvjs_nP.prototype.R.call(this,a);var b=this.bc.m.selectedValuesLayout;b==gvjs_3N&&this.Ce.Xr(gvjs_Y);gvjs_E(this.pk);this.pk=new gvjs_oP(b,gvjs_Dz(this.Ce.j()).width,gvjs_lP(this.bc)?0:1);a.addChild(this.pk,!0);this.bc.addEventListener(this.pk,gvjs_Ss,this.HI,!1,this)};
gvjs_.AE=function(){for(var a=this.bc.ug,b=0,c=this.Ce.bh();b<c;b++)a.tf(this.Ce.od(b).Zh.getId())&&this.Ce.od(b).setVisible(!1);gvjs_pP(this.pk,a.ob());this.Ce.gl(null);this.Ce.Gb(!gvjs_mP(this.bc))};gvjs_.No=function(a){var b=this.Ce.Be().Zh;this.Ce.Be().setVisible(!1);this.Ce.gl(null);this.bc.ug.set(b.getId(),b);this.Ce.Gb(!gvjs_mP(this.bc));gvjs_pP(this.pk,this.bc.ug.ob());gvjs_nP.prototype.No.call(this,a)};
gvjs_.HI=function(a){(a=a.item)&&this.bc.ug.remove(a.getId());this.Ce.Gb(!0);for(var b=0,c=this.Ce.bh();b<c;b++)if(this.Ce.od(b).Zh==a){this.Ce.od(b).setVisible(!0);break}this.bc.ru()};function gvjs_qP(a){gvjs_F.call(this);this.bc=a;this.ae=null}gvjs_o(gvjs_qP,gvjs_F);gvjs_=gvjs_qP.prototype;gvjs_.M=function(){gvjs_E(this.ae);gvjs_F.prototype.M.call(this)};
gvjs_.R=function(a){var b=this.bc.mc;gvjs_E(this.ae);this.ae=new gvjs_9O;this.ae.iha=!0;var c=this.ae;c.RX=this.bc.m.caption;c.lj&&c.lj.In(c.RX);for(c=0;c<b.length;c++)this.ae.Bj(new gvjs_bP(b[c].Dd(),b[c]));a.addChild(this.ae,!0);this.ae.Gb(0<b.length);this.bc.addEventListener(this.ae,gvjs_Ss,this.No,!1,this);a=gvjs_zh(gvjs_Oh(),gvjs_fv,null,this.ae.j())[0];this.bc.addEventListener(a,gvjs_Yo,this.PZ,!1,this)};gvjs_.AE=function(){};gvjs_.No=function(){this.bc.ru()};gvjs_.PZ=function(){};
function gvjs_iP(a){gvjs_qP.call(this,a)}gvjs_o(gvjs_iP,gvjs_qP);gvjs_iP.prototype.AE=function(){this.ae.Wa(this.bc.ug.ob()[0].Dd())};gvjs_iP.prototype.No=function(a){this.bc.ug.clear();var b=a.item.getValue();b&&this.bc.ug.set(b.getId(),b);gvjs_qP.prototype.No.call(this,a)};gvjs_iP.prototype.PZ=function(){var a=this.bc.ug;if(!this.ae.getValue()&&gvjs_lP(this.bc)){var b=!a.isEmpty();a.clear();b&&this.bc.ru()}else a.isEmpty()?this.ae.Wa(""):this.ae.Wa(a.ob()[0].Dd())};
function gvjs_hP(a){gvjs_qP.call(this,a);this.pk=null}gvjs_o(gvjs_hP,gvjs_qP);gvjs_=gvjs_hP.prototype;gvjs_.M=function(){gvjs_E(this.pk);gvjs_qP.prototype.M.call(this)};gvjs_.R=function(a){gvjs_qP.prototype.R.call(this,a);var b=this.bc.m.selectedValuesLayout;b==gvjs_3N&&gvjs_VC(this.ae.j(),gvjs_Y);gvjs_E(this.pk);this.pk=new gvjs_oP(b,gvjs_Dz(this.ae.j()).width,gvjs_lP(this.bc)?0:1);a.addChild(this.pk,!0);this.bc.addEventListener(this.pk,gvjs_Ss,this.HI,!1,this)};
gvjs_.AE=function(){for(var a=this.bc.ug,b=0,c=this.ae.bh();b<c;b++)a.tf(this.ae.od(b).Zh.getId())&&this.ae.od(b).Gb(!1);gvjs_pP(this.pk,a.ob());this.ae.Wa("");this.ae.Gb(!gvjs_mP(this.bc))};gvjs_.No=function(a){var b=a.item.getValue();a.item.Gb(!1);a.preventDefault();this.ae.eC();this.ae.Wa("");this.bc.ug.set(b.getId(),b);this.ae.Gb(!gvjs_mP(this.bc));gvjs_pP(this.pk,this.bc.ug.ob());gvjs_qP.prototype.No.call(this,a)};
gvjs_.HI=function(a){a=a.item;this.bc.ug.remove(a.getId());this.ae.Gb(!0);for(var b=0,c=this.ae.bh();b<c;b++)if(this.ae.od(b).Zh==a){this.ae.od(b).Gb(!0);break}this.bc.ru()};gvjs_.PZ=function(){this.ae.Wa("")};function gvjs_oP(a,b,c,d){gvjs_MC.call(this,d);this.EE=a;this.Pq=b;this.b1=c;this.Uz=0;this.gU=[]}gvjs_o(gvjs_oP,gvjs_MC);gvjs_oP.prototype.J=function(){var a=this.D.J("UL");this.H=a;this.vf(a)};gvjs_oP.prototype.Fh=function(a){return"UL"==a.tagName};
gvjs_oP.prototype.vf=function(a){gvjs_VC(a,"google-visualization-controls-categoryfilter-selected");this.EE==gvjs_3N?gvjs_VC(a,gvjs_Y):("belowWrapping"==this.EE||this.EE==gvjs_4N)&&gvjs_C(a,gvjs_Hv,this.Pq+gvjs_T)};
function gvjs_pP(a,b){a.qc(!0);a.gU=[];a.Uz=b.length;for(var c=0;c<a.Uz;c++){var d=a,e=b[c];var f=new gvjs_8D(gvjs_S,new gvjs_rP(d.EE));f.jp(!1);var g=new gvjs_4D("\u00d7",new gvjs_dP);gvjs_G(g,gvjs_Ss,gvjs_re(d.HI,e,f),!1,d);f.addChild(g,!0);g.j().setAttribute(gvjs_9w,0);g.Gb(d.Uz>d.b1);d=new gvjs_LD(e.Dd());d.Xr(gvjs_Y);f.addChild(d,!0);a.gU.push(f);a.addChild(f,!0)}}
gvjs_oP.prototype.HI=function(a,b,c){this.Uz<=this.b1||(this.removeChild(c.target.getParent(),!0),gvjs_Ie(this.gU,b),this.Uz--,this.Uz<=this.b1&&0<this.Uz&&gvjs_u(this.gU,function(d){d.Ye(0).Gb(!1)}),this.dispatchEvent(new gvjs_3O(gvjs_Ss,this,a)),c.stopPropagation())};function gvjs_rP(a){this.dN=void 0;this.EE=a}gvjs_o(gvjs_rP,gvjs_5D);gvjs_rP.prototype.J=function(a){var b=this.EE==gvjs_4N?"":gvjs_Y;return a.wa().J("LI",this.Rl(a).join(" ")+" "+b)};gvjs_rP.prototype.Fh=function(a){return"LI"==a.tagName};function gvjs_sP(a){gvjs_QO.call(this,a)}gvjs_o(gvjs_sP,gvjs_QO);gvjs_sP.prototype.vv=function(){return gvjs_fP};var gvjs_gia=gvjs_gO.eCa,gvjs_hia=gvjs_gO.fCa,gvjs_iia=gvjs_D.removeAll;function gvjs_tP(a){gvjs_Qn.call(this,a);this.Ai=this.fo=this.Ea=this.theme=this.Fa=null;this.QM=[];this.ly=this.Vp=this.pi=this.animation=this.sb=this.Ns=this.Ui=null;this.height=this.width=0;this.options=null;this.orientation=gvjs_S;this.tQ=new gvjs_H;this.Tu=new gvjs_8q(this);gvjs_6x(this,this.Tu)}gvjs_o(gvjs_tP,gvjs_Qn);gvjs_=gvjs_tP.prototype;
gvjs_.M=function(){this.He();gvjs_E(this.tQ);gvjs_E(this.pi);gvjs_E(this.Vp);gvjs_E(this.ly);gvjs_Qn.prototype.M.call(this)};gvjs_.us=function(a,b,c,d,e,f){if(this.Fa===gvjs_fw)throw Error("This should never happen.");a=this.Fa===gvjs_4u?new gvjs_QK(a,b,c,d,e):new gvjs_eJ(a,b,c,d,e);this.oQ(a,f);return a};gvjs_.oQ=function(a,b){a.init(this.BB,b)};gvjs_.hH=function(a,b,c,d,e,f,g){return new gvjs_jK(a,b,c,d,e,f,g)};gvjs_.gH=function(a,b,c,d){return new gvjs_WJ(a,b,c,d)};
gvjs_.Wx=function(a,b){return new gvjs_aH(a,b)};gvjs_.cc=function(a,b,c,d){this.Fa=a;null!=b&&(this.DH=b);null!=c&&(this.orientation=c);null!=d&&(this.theme=d)};gvjs_.draw=function(a,b,c){gvjs_Qn.prototype.draw.call(this,a,b,c)};
gvjs_.Rd=function(a,b,c,d){var e=this;c=void 0===c?{}:c;this.BB=a;c=gvjs_Li(gvjs_Ii(c));gvjs_jia(this,c);gvjs_kia(this,c);c.orientation=c.orientation||this.orientation;c.theme=c.theme||this.theme;this.Fa!==gvjs_f&&gvjs_lia(c);if(this.Fa!==gvjs_fw&&gvjs_Jj(c.reverseCategories)){var f=c.orientation===gvjs_U?gvjs_Ud:gvjs_Xu;c[f]=c[f]||{};c[f].direction=-1;delete c.reverseCategories}gvjs_mia(c);f=this.getContainer();gvjs_iia(f);if(!b)throw Error(gvjs_as);gvjs_Fe(gvjs_Ky(b.$()),function(k){return b.Jg(k)===
gvjs_3v})&&(c.isDiff=!0);b.W(0);b.ca();gvjs_uP(this);c=gvjs_nia(c);var g=[],h=gvjs_7K();gvjs_u(c,function(k){g.push.apply(g,gvjs_9d(gvjs_Vz(k,h)))});this.bfa=c;this.options=new gvjs_Aj(gvjs_Le(this.bfa));this.Fa=gvjs_J(this.options,gvjs_Sd,gvjs_f,gvjs_eC);this.width=this.La(this.options);this.height=this.getHeight(this.options);c=new gvjs_A(this.width,this.height);f=gvjs_K(this.options,gvjs_Eu);if(!this.sb||this.sb.xf)try{this.sb=new gvjs_3B(this.container,c,a,f)}catch(k){throw Error(gvjs_As);}else this.sb.update(c,
a);this.Ui=new gvjs_bG(d);this.Ta=b;g.length&&this.Lh?(this.Lh.promise.then(function(){e.sb.rl(e.hX.bind(e),a)}),gvjs_sy(this,function(){e.sb.rl(e.hX.bind(e),a)}),new gvjs_6K(g,this.Lh)):this.sb.rl(this.hX.bind(this),a)};
function gvjs_nia(a){if(a.isStacked&&a.vAxis&&a.vAxis.baseline)throw Error(gvjs_5r);var b=a.theme||[];b&&!Array.isArray(b)&&(b=[b]);for(var c=[a],d=0;d<b.length;d++){var e=b[d];if(typeof e===gvjs_l)e=gvjs_4F(e);else if(gvjs_r(e))e instanceof gvjs_Aj&&(e=gvjs_jq(e));else throw Error(gvjs_ws);e&&c.push(e)}a=a.type.toLowerCase();gvjs_PF[a]&&c.push(gvjs_PF[a]);c.push(gvjs_QF);return c}
gvjs_.hX=function(){var a=this,b=this.sb.Oa(),c=this.sb.yq(),d=this.options;this.us(this.Ta,d,b.me.bind(b),this.width,this.height,function(e){gvjs_vP(a);e=e.ti();var f=new gvjs_fL(d,a.Ui,a.Ql.bind(a),e);gvjs_E(a.pi);a.pi=new gvjs_MK(e,a.Ui,a.tQ,a.Tu,a.refresh.bind(a,!0),f);a.Ai=a.hH(a.options,new gvjs_A(a.width,a.height),{bb:e.Hj,fontSize:e.Dl},e.qz,e.Ig,e.C.length,a.Ai?a.Ai.le:void 0);gvjs_oia(a);a.fo=a.Wx(c,b);gvjs_pia(a,e)||(a.Ea=e,gvjs_wP(a),gvjs_xP(a));a.fY();a.Tu.dispatchEvent(gvjs_i);a.pi.Bq()})};
gvjs_.fY=function(){var a=this,b=this.sb.Oa();setTimeout(function(){if(b&&b.ws){var c=b.ws();if(c&&a.Ta){var d=gvjs_gL(a.Ta);gvjs_cg(c,d)}}},0)};gvjs_.Jm=function(a,b){if(this.Fa===gvjs_fw)return this.av(a,b);throw Error(gvjs_4r);};
gvjs_.av=function(a,b){if(!a||!b)throw Error("Old and New DataTables must exist.");var c=new gvjs_M,d=b.ca(),e=b.$(),f=a.W(0)!==gvjs_g;f&&c.xd(a.W(0),a.Ga(0));for(var g=f?1:0,h=g;h<e;++h)c.xd({type:a.W(h),label:a.Ga(h),role:gvjs_3v}),c.xd({type:b.W(h),label:b.Ga(h),role:gvjs_$t});c.Yn(d);for(h=0;h<d;++h){if(f){var k=b.getValue(h,0);c.Wb(h,0,k)}for(var l=k=g;l<e;++l){var m=a.getValue(h,l);c.Wb(h,k,m);k+=1;m=b.getValue(h,l);c.Wb(h,k,m);k+=1}}return c};
function gvjs_jia(a,b){switch(b.type){case gvjs_yP.LINE:a.cc(gvjs_d,gvjs_e,gvjs_S);b.type=null;break;case gvjs_yP.AREA:a.cc(gvjs_d,gvjs_at,gvjs_S);b.type=null;break;case gvjs_yP.cia:a.cc(gvjs_d,gvjs_lt,gvjs_S);b.type=null;break;case gvjs_yP.nV:a.cc(gvjs_d,gvjs_lt,gvjs_U);b.type=null;break;case gvjs_yP.wV:a.cc(gvjs_Dd);b.type=null;break;case gvjs_yP.z6:a.cc(gvjs_fw),b.type=null}a=a.Fa;a===gvjs_f&&(a=null);var c=b.type||gvjs_f;c===gvjs_f&&(c=null);if(!a&&!c)throw Error(gvjs_zs);if(a&&c&&a!==c)throw Error(gvjs_es);
b.type=a||c}function gvjs_kia(a,b){if(b.type===gvjs_d){a=a.DH;a===gvjs_f&&(a=null);var c=b.seriesType||gvjs_f;c===gvjs_f&&(c=null);if(a&&c&&a!==c)throw Error(gvjs_fs);b.seriesType=a||c}}
function gvjs_lia(a){a.hAxis=a.hAxis||{};a.vAxis=a.vAxis||{};var b=a.hAxis,c=a.vAxis,d=null;switch(a.type){case gvjs_Dd:d=c;break;case gvjs_d:a.targetAxis=a.targetAxis||{},d=a.targetAxis}d&&(gvjs_zP(a,gvjs_Ov,d,gvjs_ed),gvjs_zP(a,gvjs_Gv,d,gvjs_cd),gvjs_zP(a,gvjs_Cv,d,gvjs_Cv));b&&(gvjs_zP(a,"logScaleX",b,gvjs_Cv),gvjs_zP(a,"titleX",b,gvjs_fx));c&&gvjs_zP(a,gvjs_jx,c,gvjs_fx);a.smoothLine&&void 0===a.curveType&&(a.curveType=gvjs_d);gvjs_zP(a,"lineSize",a,gvjs_Bv);gvjs_zP(a,gvjs_ww,a,gvjs_xw);a.chartArea=
a.chartArea||{};gvjs_zP(a,gvjs_gt,a.chartArea,gvjs_ht)}
function gvjs_mia(a){gvjs_AP(a,gvjs_gx,gvjs_hx,gvjs_ix);gvjs_AP(a,gvjs_xv,gvjs_wv,gvjs_yv);gvjs_BP(a.hAxis);var b=a.hAxes||{},c;for(c in b)b.hasOwnProperty(c)&&gvjs_BP(b[c]);b=a.vAxes||{};gvjs_BP(a.vAxis);for(var d in b)b.hasOwnProperty(d)&&gvjs_BP(b[d]);d=a.tooltip;null==d&&(d={},a.tooltip=d);gvjs_AP(a,gvjs_sx,gvjs_rx,gvjs_tx);gvjs_zP(a,gvjs_tx,d,gvjs_bx);gvjs_zP(a,"tooltipText",d,gvjs_m);gvjs_zP(a,gvjs_ux,d,"trigger");"hover"===d.trigger&&(d.trigger=gvjs_xu);d=a.legend;null==d?(d={},a.legend=d):
typeof d===gvjs_l&&(b=d,d={},a.legend=d,d.position=b);gvjs_zP(a,gvjs_yv,d,gvjs_bx);d=a.animation;null==d?(d={},a.animation=d):typeof d===gvjs_g&&(b=1E3*d,d={},a.animation=d,d.duration=b);gvjs_zP(a,gvjs_Xs,d,"easing")}
function gvjs_BP(a){if(null!=a){gvjs_AP(a,"textColor","textFontSize",gvjs_bx);gvjs_AP(a,gvjs_gx,gvjs_hx,gvjs_ix);a.gridlines=a.gridlines||{};var b=a.gridlines,c=a.numberOfSections;void 0===b.count&&void 0!==c&&typeof c===gvjs_g&&(b.count=c+1);a=a.gridlineColor;void 0===b.color&&void 0!==a&&(b.color=a)}}function gvjs_AP(a,b,c,d){a[d]=a[d]||{};d=a[d];gvjs_zP(a,b,d,gvjs_1);gvjs_zP(a,c,d,gvjs_zp)}function gvjs_zP(a,b,c,d){void 0!==a[b]&&void 0===c[d]&&(c[d]=a[b])}
gvjs_.He=function(){gvjs_CP(this);gvjs_uP(this);gvjs_vP(this);gvjs_E(this.sb);gvjs_li(this)};function gvjs_uP(a){if(a.pi&&!a.pi.xf){var b=a.pi.zb;b.fq=Infinity;b.Hc.stop()}gvjs_E(a.pi);if(a.sb&&!a.sb.xf){b=a.sb.Oa();var c=a.sb.yq();a.ly=b;c.clear()}gvjs_E(a.Vp);gvjs_li(a.tQ)}function gvjs_vP(a){var b=a.ly||a.sb&&a.sb.Oa();a.ly=null;b&&b.clear()}function gvjs_oia(a){gvjs_u(a.QM,function(b){typeof b===gvjs_l?a.th(b):a.xh(b)});a.QM=[]}gvjs_.xh=function(a){null!=this.Ai?this.Ai.xh(a):this.QM.push(a)};
function gvjs_qia(a,b){var c=new gvjs_$n;c.setSelection(b);b=gvjs_co(c);c=!1;for(var d=0;d<b.length;d++){var e=b[d],f=e.column;e=e.row;f=a.Ea.Jk&&a.Ea.Jk[f];if(!f)return!1;var g=f.Vb,h=void 0,k=void 0;null!=g?k=a.Ea.C[g].points[e]:h=a.Ea.$a[e];if(!k&&!h)return!1;if(f.role===gvjs_Zs){if(c)return!1;c=!0;if(!(k||h).Bc)return!1}}return!0}
gvjs_.setSelection=function(a){if(gvjs_qia(this,a)){var b=null;if(this.Ea.Fa!==gvjs_fw){var c=new gvjs_$n;c.setSelection(a);c=gvjs_co(c);for(var d=0;d<c.length;d++){var e=c[d],f=this.Ea.Jk[e.column];if(f.role===gvjs_Zs){b={Vb:f.Vb,oO:e.row};break}}}this.refresh(!0);this.Ui.selected.setSelection(a);b&&(this.Ui.annotations.dI=b);this.refresh(!1)}};
gvjs_.refresh=function(a){if(this.Ns){var b=this.Ns;if(!this.Ai.xY(this.Ui,this.Ns)){var c=this.Ui.gm;if(c){this.options=new gvjs_Aj(gvjs_Le(this.bfa));gvjs_hq(this.options,0,c);c=this.sb.Oa();var d=this.us(this.Ta,this.options,c.me.bind(c),this.width,this.height).ti();this.pi.ha=d;this.ly&&(this.ly.clear(),this.ly=null);this.Vp&&this.Vp instanceof gvjs_WJ&&this.Vp.I5(d);c=gvjs_iK(this.Ai,d,this.Ui);this.Ea=d;this.fo.VK(this.Ea);gvjs_OG(this.fo,this.Ea,c);this.Ui.gm=null;this.Ns=this.Ui.clone()}else this.Ns=
this.Ui.clone(),c=gvjs_iK(this.Ai,this.Ea,this.Ui),gvjs_PG(this.fo,this.Ea,c)}a&&this.Tu.Is(b,this.Ns,this.Ea.Fa,this.Ea.C)}};gvjs_.getSelection=function(){return this.Ns?this.Ns.selected.getSelection():[]};gvjs_.ng=function(a){if(this.Ai)return this.Ai.ng(a)};gvjs_.th=function(a){null!=this.Ai?this.Ai.th(a):this.QM.push(a)};gvjs_.dump=function(){var a=this.sb.Oa();return a instanceof gvjs_PB?a.container.innerHTML:""};
function gvjs_wP(a){var b=gvjs_iK(a.Ai,a.Ea,a.Ui);a.fo.Fl(a.Ea,b);a.Ns=a.Ui.clone()}function gvjs_xP(a){var b=a.sb.Oa(),c=a.sb.yq();gvjs_E(a.Vp);a.Vp=a.gH(a.tQ,b,c,a.Ea);gvjs_QJ(a.Vp);gvjs_SJ(a.Vp);gvjs_TJ(a.Vp)}
function gvjs_pia(a,b){var c=gvjs_5K(a.options,0,gvjs_Hp);if(a.animation){var d=a.animation.zK;gvjs_CP(a)}else d=a.Ea;if(!c||!(c.iga||d&&d.Fa===b.Fa)||b.Fa===gvjs_4u||b.Fa===gvjs_fw)return!1;if(!d){var e=gvjs_Ky(a.Ta.$());d=a.Ta instanceof gvjs_N;var f=a.Ta.Do();if(!d){var g=a.Ta;f=gvjs_v(g.Do(),function(u){return typeof u===gvjs_h?u:{sourceColumn:u,properties:g.Rj(u)}})}var h=b.C;d=b.Jk;b.Fa===gvjs_yt&&(d=[{role:gvjs_5c},{role:gvjs_mu},{role:gvjs_$t,Vb:0}]);var k,l;gvjs_u(d,function(u,v){if(u.role===
gvjs_$t||u.role===gvjs_iv){var w=gvjs_x(f[v]);if(u.role===gvjs_$t){u=h[u.Vb];if(u.ag)return;u=u.Qc||0;if(null!=u){var x=b.orientation&&b.orientation!==gvjs_S?b.jd[u]:b.wc[u];k=function(){return x.baseline.za};l=x.dataType}}else w.role=gvjs_iv;w.calc=k;w.type=l;e[v]=w}});d=new gvjs_N(a.Ta);d.Hn(e);var m={},n=b.jd;if(n){var p=Object.keys(n);p=gvjs_8d(p);for(var q=p.next();!q.done;q=p.next()){var r=q.value;typeof r===gvjs_g&&(q=n[r],q.Tn&&(m[r]={viewWindow:{numericMin:q.Tn.min,numericMax:q.Tn.max}}))}}p=
{};if(n=b.wc)for(r=Object.keys(n),r=gvjs_8d(r),q=r.next();!q.done;q=r.next())if(q=q.value,typeof q===gvjs_g){var t=n[q];t.Tn&&(p[q]={viewWindow:{numericMin:t.Tn.min,numericMax:t.Tn.max}})}gvjs_hq(a.options,0,{hAxes:m,vAxes:p});m=a.sb.Oa();d=a.us(d,a.options,m.me.bind(m),a.width,a.height).ti()}a.Ea=null;m=Date.now();n=a.animation&&a.animation.iA||0;gvjs_CP(a);a.animation={bua:d,$J:b,interpolator:new gvjs_zK(d,b),zK:d,startTime:m,endTime:m+c.duration,iA:n,timer:new gvjs_IA(10),oY:c.easing,HD:c.HD,done:!1};
a.Kaa();gvjs_G(a.animation.timer,gvjs_dx,a.Kaa.bind(a));a.animation.timer.start();a.Ea=b;return!0}gvjs_.Kaa=function(){var a=this.animation;this.Ea=null;if(a.done)gvjs_CP(this),this.Ea=a.$J,gvjs_wP(this),gvjs_xP(this),this.Tu.dispatchEvent(gvjs_gia);else{var b=Date.now(),c=(b-a.startTime)/(a.endTime-a.startTime);if(1>c){if(b-a.iA<1E3/this.animation.HD)return}else c=1,a.done=!0;c=a.interpolator.interpolate(a.oY(c));a.zK=c;a.iA=b;this.fo.Fl(c,{});this.Tu.dispatchEvent(gvjs_hia)}this.Ea=a.$J};
function gvjs_CP(a){a.animation&&(gvjs_E(a.animation.timer),a.animation=null)}gvjs_.fZ=function(){var a=this.Ea.O;return{left:a.left,top:a.top,width:a.width,height:a.height}};gvjs_.Qj=function(a){return null==this.fo?null:(a=this.fo.Qj(a))?{left:a.left,top:a.top,width:a.right-a.left,height:a.bottom-a.top}:null};
gvjs_.Ql=function(){var a=this.Ea;if(null==a)throw Error("redundant error checking");return{getChartAreaBoundingBox:this.fZ.bind(this),getBoundingBox:this.Qj.bind(this),getXLocation:gvjs_5G.bind(null,a),getYLocation:gvjs_6G.bind(null,a),getHAxisValue:gvjs_7G.bind(null,a),getVAxisValue:gvjs_8G.bind(null,a),getPointDatum:gvjs_9G.bind(null,a)}};gvjs_.pZ=function(){return this.sb};gvjs_.ti=function(){return this.Ea};
gvjs_.ah=function(){if(!this.options||!this.Ea||!this.Ui)throw Error(gvjs_6r);var a=new gvjs_A(this.width,this.height),b=gvjs_3g(this.container).createElement(gvjs_Ob);a=gvjs_1B(b,a);a=new gvjs_rB(b,a);a=this.Wx(new gvjs_MB(b),a);var c=gvjs_iK(this.Ai,this.Ea,this.Ui);a.Fl(this.Ea,c);return b.childNodes[0].toDataURL(gvjs_bv)};var gvjs_yP={LINE:gvjs_e,AREA:gvjs_at,cia:"columns",nV:gvjs_lt,wV:gvjs_Dd,z6:gvjs_fw};function gvjs_DP(a){gvjs_tP.call(this,a);this.cc(gvjs_d,gvjs_at,gvjs_S)}gvjs_o(gvjs_DP,gvjs_tP);function gvjs_EP(a){gvjs_tP.call(this,a);this.cc(gvjs_d,gvjs_e,gvjs_S)}gvjs_o(gvjs_EP,gvjs_tP);function gvjs_FP(a){gvjs_tP.call(this,a);this.cc(gvjs_Dd)}gvjs_o(gvjs_FP,gvjs_tP);gvjs_FP.prototype.Jm=function(a,b){return this.av(a,b)};function gvjs_GP(a){gvjs_tP.call(this,a);this.cc(gvjs_d,gvjs_f,gvjs_S)}gvjs_o(gvjs_GP,gvjs_tP);function gvjs_HP(a){gvjs_Qn.call(this,a);this.Fd={};this.da=null;this.Ek={Cu:!1};this.aI=this.JK=this.ea=this.F=this.Ag=this.ha=this.wk=this.Z=null;this.FK=50;this.Tca=0;this.zR=1;this.HW=this.x4=this.fV=!1;this.gR=this.sR=this.WY=this.j4=null;this.Ff=!1;this.Cc=null;this.K={range:null,DO:null,eh:null};this.Dj={cl:{min:0,max:0},value:{min:0,max:0}};this.bW=null;this.jX=!1;this.Gu=null;this.ZO=!1}gvjs_o(gvjs_HP,gvjs_Qn);gvjs_=gvjs_HP.prototype;
gvjs_.draw=function(a,b,c){this.Jb();gvjs_Kk(a);this.Z=a;this.wk=gvjs_7H(a.W(0));null==this.JK&&(this.JK=new gvjs_KK(this.Nya.bind(this)));null==this.aI&&(this.aI=new gvjs_KK(this.t5.bind(this,!0)));b=new gvjs_Aj([b||{}]);this.Kt(b);this.Cc=this.J$(b);c=c||{};if(!this.da){switch(gvjs_J(b,gvjs_St,gvjs_ya,gvjs_ria)){case gvjs_na:b=new gvjs_DP(this.container);break;case gvjs_ya:b=new gvjs_GP(this.container);break;case gvjs_9a:b=new gvjs_FP(this.container);break;case gvjs_Va:b=new gvjs_EP(this.container);
break;default:b=new gvjs_GP(this.container)}this.da=b;gvjs_si(this.da,gvjs_i,this.iua.bind(this,c))}this.fV&&(this.sR=this.Z.getValue(0,0),this.gR=this.Z.getValue(Math.max(0,this.Z.ca()-1),0),b={min:this.sR,max:this.gR},c.range&&gvjs_IP(this,b,c.range),this.Cc.domainAxis=this.Cc.domainAxis||{},this.Cc.domainAxis.viewWindow=b);this.da.draw(a,this.Cc)};gvjs_.Rd=function(){};
gvjs_.Kt=function(a){this.FK=gvjs_Oj(a,"rangeChangeEventFiringRate",50);this.Tca=gvjs_Oj(a,"minRangeSize",0);this.ZO=gvjs_K(a,"fixedRangeSize",!1);this.fV=gvjs_K(a,"zoomAroundSelection",!1);this.x4=gvjs_K(a,"snapToData",!1);this.HW=gvjs_K(a,"centerSelectionAroundData",!1);this.j4=gvjs_qy(a,"sideScreenColor",new gvjs_3(gvjs_sia));this.WY=new gvjs_3(gvjs_iy);this.Ff=gvjs_J(a,gvjs_9v,gvjs_S,gvjs_iC)===gvjs_U};gvjs_.J$=function(a){a=gvjs_jj(a.pb("chartOptions"));a.theme=this.Ff?gvjs_tia:gvjs_uia;return a};
function gvjs_via(a,b){var c=gvjs_lA(a.ca(),function(d){return a.getValue(d,0)});c=gvjs_De(c,function(d){return null!=d});return gvjs_v(c,b)}gvjs_.iua=function(a){gvjs_vi(this.da);this.Ek={Cu:!0};gvjs_JP(this,a);gvjs_E(this.F);this.F=this.da.pZ().Oa(1);gvjs_E(this.ea);this.ea=new gvjs_KA;gvjs_wia(this)};gvjs_.Ada=function(a){gvjs_vi(this.da);gvjs_JP(this,a);gvjs_KP(this,gvjs_ut)};
function gvjs_JP(a,b){a.ha=a.da.ti();a.Ag=a.Ff?a.ha.wc[0]:a.ha.jd[0];a.Dj.cl={min:Math.min(a.Ag.Pf,a.Ag.ef),max:Math.max(a.Ag.Pf,a.Ag.ef)};var c=a.Dj,d=a.Ag.position.ol(a.Ag.Pf),e=a.Ag.position.ol(a.Ag.ef);c.value={min:Math.min(d,e),max:Math.max(d,e)};d=a.Tca;if(0>=d)a.zR=1;else{c=a.Dj.cl.min;e=a.Ag.position.ol(c);if(gvjs_oe(e)){var f=new Date;f.setTime(e.getTime()+d)}else f=e+d;d=a.Ag.position.hf(f);c=Math.max(Math.ceil(Math.abs(d-c)),1);a.zR=c<a.Dj.cl.max-a.Dj.cl.min?c:1}if(a.x4||a.HW)c=a.Ag,d=
gvjs_via(a.Z,c.position.hf),c=a.Ff?1===c.ro?d.reverse():d:1===c.ro?d:d.reverse(),a.bW=c;b&&(b=b.range,a.K.range=gvjs_LP(a,gvjs_r(b)?b.start:null,gvjs_r(b)?b.end:null))}
function gvjs_wia(a){var b=a.F,c=a.ha,d=b.Lm(c.width,c.height),e=b.Sa(!1);b.appendChild(d,e);d=c.O;b.yb(0,0,c.width,c.height,a.WY,e);c=b.yb(d.left,d.top,d.width,d.height,a.WY,e);var f=gvjs_MP(a);f=b.yb(f.left,f.top,f.width,f.height,a.j4,e);a.Fd.rangeSelectorMinScreen=f;f=gvjs_NP(a);f=b.yb(f.left,f.top,f.width,f.height,a.j4,e);a.Fd.rangeSelectorMaxScreen=f;f=gvjs_OP(a,a.K.range.Yh,d,b,e);a.Fd.rangeSelectorMinHandle=f;b=gvjs_OP(a,a.K.range.Xh,d,b,e);a.Fd.rangeSelectorMaxHandle=b;var g=gvjs_5g(a.container);
a.ea.o(g.body,gvjs_jd,a.Spa.bind(a,a.Ek));a.ea.o(g.body,gvjs_md,a.RP.bind(a,a.Ek));e=e.j();a.ea.o(e,gvjs_jd,a.Vqa.bind(a,a.Ek));a.ea.o(e,gvjs_kd,a.EI.bind(a,a.Ek,{type:gvjs_Fw,Ro:!1}));a.jX=gvjs_yh(e,function(h){return h===g.body});a.jX||a.ea.o(e,gvjs_md,a.RP.bind(a,a.Ek));a.ZO||(gvjs_PP(a,f,gvjs_Ov,gvjs_Ov),gvjs_PP(a,b,gvjs_Gv,gvjs_Gv));a.ea.o(c,gvjs_gd,a.UC.bind(a,a.Ek,{eh:gvjs_ut}));a.ea.o(c,gvjs_ld,a.EI.bind(a,a.Ek,{type:gvjs_Fw,Ro:!0}));a.ea.o(c,gvjs_kd,a.EI.bind(a,a.Ek,{type:gvjs_Fw,Ro:!1}));
gvjs_I(a,gvjs_i,null)}function gvjs_PP(a,b,c,d){a.ea.o(b,gvjs_gd,a.UC.bind(a,a.Ek,{eh:d}));a.ea.o(b,gvjs_ld,a.EI.bind(a,a.Ek,{type:c,Ro:!0}));a.ea.o(b,gvjs_kd,a.EI.bind(a,a.Ek,{type:c,Ro:!1}))}
function gvjs_OP(a,b,c,d,e){var f=gvjs_QP,g=gvjs_xia,h=gvjs_yia,k=d.Sa(!1);d.appendChild(e,k);e=.5*f.width;var l=.5*f.height,m=a.Ff?c.left:Math.floor(b-e)+.5;b=a.Ff?Math.floor(b-l)+.5:c.top;d.mp(k.j(),m,b);a.Ff?(b=Math.round(l),b=gvjs_UA(a.Ff?[{x:0,y:b},{x:0+c.width,y:b}]:[{x:0,y:b},{x:0,y:b+c.height}]),d.Ia(b,h,k),a.ZO||gvjs_RP(a,.5*(c.width-f.height),0,f.height,f.width,g,d,h,k)):(b=Math.round(e),b=gvjs_UA(a.Ff?[{x:b,y:0},{x:b+c.width,y:0}]:[{x:b,y:0},{x:b,y:0+c.height}]),d.Ia(b,h,k),a.ZO||gvjs_RP(a,
0,.5*(c.height-f.height),f.width,f.height,g,d,h,k));return k.j()}function gvjs_RP(a,b,c,d,e,f,g,h,k){d=b+d;e=c+e;var l=gvjs_UA([{x:b+f,y:c},{x:d-f,y:c},{x:d,y:c+f},{x:d,y:e-f},{x:d-f,y:e},{x:b+f,y:e},{x:b,y:e-f},{x:b,y:c+f}],!1);g.Ia(l,h,k);f+=1;a.Ff?(a=gvjs_UA([{x:b+f,y:c+f},{x:d-f,y:c+f}]),b=gvjs_UA([{x:b+f,y:e-f},{x:d-f,y:e-f}])):(a=gvjs_UA([{x:b+f,y:c+f},{x:b+f,y:e-f}]),b=gvjs_UA([{x:d-f,y:c+f},{x:d-f,y:e-f}]));g.Ia(a,h,k);g.Ia(b,h,k)}
function gvjs_MP(a){var b=a.ha.O,c=a.K.range.Yh;return a.Ff?new gvjs_5(b.left,b.top,b.width,c-b.top):new gvjs_5(b.left,b.top,c-b.left,b.height)}function gvjs_NP(a){var b=a.ha.O,c=a.K.range.Xh;return a.Ff?new gvjs_5(b.left,c,b.width,b.bottom-c):new gvjs_5(c,b.top,b.right-c,b.height)}
function gvjs_LP(a,b,c){var d=a.Dj.cl.min,e=a.Dj.cl.max,f=1===a.Ag.ro&&!a.Ff;null!=b&&(b=a.Ag.position.hf(b),f?d=Math.max(b,d):e=Math.min(b,e));null!=c&&(a=a.Ag.position.hf(c),f?e=Math.min(a,e):d=Math.max(a,d));return{Yh:d,Xh:e}}gvjs_.vP=function(){var a=this.K.range,b=this.Ag.position.ol(a.Yh);a=this.Ag.position.ol(a.Xh);var c=1===this.Ag.ro&&!this.Ff;return{start:c?b:a,end:c?a:b}};
gvjs_.Ewa=function(a,b){if(!this.Ek.Cu)return!1;var c=this.K.range;if(null==c.Yh||null==c.Xh)return!1;a=gvjs_LP(this,a,b);a=gvjs_SP(this,a.Yh,a.Xh,gvjs_ut);this.K.eh=null;return a};function gvjs_SP(a,b,c,d){var e=a.K.range;if(e.Yh===b&&e.Xh===c)return!1;a.K.range={Yh:b,Xh:c};gvjs_KP(a,d);return!0}
function gvjs_KP(a,b){var c=a.Ff?gvjs_QP.height:gvjs_QP.width,d=a.Ff?gvjs_QP.width:gvjs_QP.height;if(b!=gvjs_Gv){var e=gvjs_MP(a),f=a.Fd.rangeSelectorMinScreen,g=a.Fd.rangeSelectorMinHandle;a.Ff?(a.F.mp(g,0,Math.floor(e.top+e.height-.5*d)+.5),a.F.xA(f,e.top),a.F.fl(f,e.height)):(a.F.mp(g,Math.floor(e.left+e.width-.5*c)+.5,0),a.F.tA(f,e.left),a.F.Ug(f,e.width))}b!=gvjs_Ov&&(b=gvjs_NP(a),e=a.Fd.rangeSelectorMaxScreen,f=a.Fd.rangeSelectorMaxHandle,a.Ff?(a.F.mp(f,0,Math.floor(b.top-.5*d)+.5),a.F.xA(e,
b.top),a.F.fl(e,b.height)):(a.F.mp(f,Math.floor(b.left-.5*c)+.5,0),a.F.tA(e,b.left),a.F.Ug(e,b.width)))}gvjs_.Nya=function(){gvjs_KP(this,this.K.eh)};function gvjs_TP(a){var b=a.Dj.cl.max-a.Dj.cl.min,c=a.Ag.ro,d=(a.K.range.Yh-a.Dj.cl.min)/b;if(.1>d)return{direction:-1*c,ratio:d/.1};a=(a.Dj.cl.max-a.K.range.Xh)/b;return.1>a?{direction:1*c,ratio:a/.1}:null}
function gvjs_UP(a){if(a.fV){var b=!1;a.K.eh===gvjs_ut&&gvjs_TP(a)&&(b=!0);b&&!a.Gu?(a.Gu=new gvjs_IA(a.FK),a.ea.o(a.Gu,gvjs_dx,a.rpa.bind(a)),a.Gu.start(),gvjs_oi(a.da,gvjs_i,a.Ada.bind(a))):!b&&a.Gu&&(gvjs_E(a.Gu),a.Gu=null)}}
gvjs_.rpa=function(){if(this.Gu){var a=gvjs_TP(this),b=this.FK/gvjs_4y(1E3,6E4,a.ratio),c=this.wk.toNumber(this.sR),d=this.wk.toNumber(this.gR),e=(d-c)*b;b=this.Cc.domainAxis.viewWindow;var f=b.max,g=this.wk.toNumber(b.min);f=this.wk.toNumber(f);0>a.direction?(a=Math.max(g-e,c),c=f-(g-a)):(c=Math.min(f+e,d),a=g+(c-f));d=this.wk.Hy(a);e=this.wk.Hy(c);if(g!=a||f!=c)b.min=d,b.max=e,this.da.draw(this.Z,this.Cc),this.t5(!0)}};
gvjs_.Vqa=function(a,b){a.Cu&&null!=this.K.eh&&(this.jX||gvjs_VP(this,b),b.target.style.cursor=gvjs_Xv)};gvjs_.Spa=function(a,b){a.Cu&&null!=this.K.eh&&gvjs_VP(this,b)};
function gvjs_VP(a,b){var c=a.K;c.range&&null!=c.range.Yh&&null!=c.range.Xh||(c.range={Yh:a.Dj.cl.min,Xh:a.Dj.cl.max});b=gvjs_zz(b);var d=a.K.range,e=a.Dj.cl;switch(a.K.eh){case gvjs_ut:var f=e.min-d.Yh;var g=e.max-d.Xh;break;case gvjs_Ov:f=e.min-d.Yh;g=d.Xh-a.zR-d.Yh;break;case gvjs_Gv:f=d.Yh+a.zR-d.Xh,g=e.max-d.Xh}f=gvjs_0g((a.Ff?b.y:b.x)-(c.DO||0),f,g);c.DO+=f;c.eh!=gvjs_Gv&&(c.range.Yh+=f);c.eh!=gvjs_Ov&&(c.range.Xh+=f);gvjs_UP(a);gvjs_LK(a.JK,a.FK);gvjs_LK(a.aI,a.FK)}
gvjs_.UC=function(a,b,c){if(a.Cu&&gvjs_7x(c)){a=gvjs_zz(c);var d=this.K;d.DO=this.Ff?a.y:a.x;d.eh=b.eh;gvjs_UP(this);c.preventDefault();c.stopPropagation()}};
gvjs_.RP=function(a){if(a.Cu&&(a=this.K,null!==a.eh)){if(this.x4){var b=this.bW;var c=a.range.Xh,d=gvjs_fO(b,a.range.Yh);b=gvjs_fO(b,c);gvjs_SP(this,d,b,a.eh)}else if(this.HW){c=new gvjs_O(a.range.Yh,a.range.Xh);d=c.end-c.start;b=this.Dj.cl;var e=this.bW,f=gvjs_Bl.bind(null,c),g=gvjs_Yx(e,f);f=gvjs_Ey(e,f);if(null===g||null===f)g=gvjs_fO(e,c.start),e=gvjs_fO(e,c.end),f=g=e=Math.abs(c.start-g)<=Math.abs(c.end-e)?g:e;c=c.end-c.start;g=gvjs_bz(g,f)-c/2;c=new gvjs_O(g,g+c);c.start=Math.max(c.start,b.min);
c.end=c.start+d;c.end=Math.min(c.end,b.max);c.start=c.end-d;gvjs_SP(this,c.start,c.end,a.eh)}else this.fV&&a.eh!=gvjs_ut&&(b=this.Cc.domainAxis.viewWindow,d=this.vP(),b=gvjs_IP(this,b,d))&&(gvjs_oi(this.da,gvjs_i,this.Ada.bind(this,{range:d})),this.da.draw(this.Z,this.Cc));this.t5(!1);a.eh=null;gvjs_UP(this)}};
function gvjs_IP(a,b,c){var d=b.max,e=a.wk.toNumber(b.min);d=a.wk.toNumber(d);var f=d-e;0===f&&(--e,d+=1,f=2);var g=c.start;c=c.end;if(null==g||null==c)return!1;var h=a.wk.toNumber(g),k=a.wk.toNumber(c);c=k-h;g=.1*f;var l=.6*f;if(c>=g&&c<=l)return!1;h=(h+k)/2;f/=(c<g?.9*l:1.1*g)/c;f=new gvjs_O(h-f/2,h+f/2);c<g?gvjs_WP(f,new gvjs_O(e,d)):(c=a.wk.toNumber(a.sR),g=a.wk.toNumber(a.gR),gvjs_WP(f,new gvjs_O(c,g)));c=a.wk.Hy(f.start);a=a.wk.Hy(f.end);e=e!=f.start||d!=f.end;b.min=c;b.max=a;return e}
function gvjs_WP(a,b){a.start<b.start&&(a.end+=b.start-a.start,a.start=b.start);a.end>b.end&&(a.start-=a.end-b.end,a.end=b.end);a.start<b.start&&(a.start=b.start)}gvjs_.EI=function(a,b,c){a.Cu&&!this.K.eh&&(c.target.style.cursor=b.Ro?b.type===gvjs_Fw?gvjs_Xv:this.Ff?"row-resize":gvjs__t:gvjs_eu)};
gvjs_.t5=function(a){var b=this.K.eh,c=this.vP();if(null!=b&&null!=c){var d=this.Ag.ro;gvjs_I(this,gvjs_8N,{start:c.start,end:c.end,startChanged:b===(1===d?gvjs_Ov:gvjs_Gv)||b===gvjs_ut,endChanged:b===(1===d?gvjs_Gv:gvjs_Ov)||b===gvjs_ut,inProgress:a})}};gvjs_.Jb=function(){this.da&&(gvjs_vi(this.da),gvjs_E(this.JK),this.JK=null,gvjs_E(this.aI),this.aI=null,this.Ek.Cu=!1,gvjs_E(this.F),this.F=null,gvjs_E(this.ea),this.ea=null,this.da.Jb(),this.da=null,gvjs_li(this),this.Fd={})};
var gvjs_ria={Eia:gvjs_Va,Uha:gvjs_na,dia:gvjs_ya,sja:gvjs_9a},gvjs_sia={fill:gvjs_yr,fillOpacity:.5},gvjs_uia={chartArea:{top:"0",height:gvjs_So},enableInteractivity:!1,legend:{position:gvjs_f},hAxis:{textPosition:gvjs_Fp},vAxis:{textPosition:gvjs_f,gridlines:{color:gvjs_f}}},gvjs_tia={chartArea:{left:"0",width:gvjs_So},enableInteractivity:!1,legend:{position:gvjs_f},vAxis:{textPosition:gvjs_Fp},hAxis:{textPosition:gvjs_f,gridlines:{color:gvjs_f}}},gvjs_yia=new gvjs_3({stroke:gvjs_kr,fill:gvjs_Br}),
gvjs_QP=new gvjs_A(10,16),gvjs_xia=3;function gvjs_XP(a){gvjs_dO.call(this,a);this.Tv=this.GK=this.nE=null}gvjs_o(gvjs_XP,gvjs_dO);gvjs_=gvjs_XP.prototype;gvjs_.M=function(){this.nE&&this.nE.Jb();gvjs_dO.prototype.M.call(this)};gvjs_.getState=function(){function a(){return null===b.Tv?{}:{range:b.Tv.range}}var b=this;if(!this.nE)return a();var c=this.nE.vP();return null==c.start||null==c.end?a():{range:c}};
gvjs_.draw=function(a,b){this.Tv=a;this.GK||(this.GK=new gvjs_Q({chartType:gvjs_HP,dataTable:a.__data__,options:b,state:a,view:b.chartView}),gvjs_oi(this.GK,gvjs_i,this.zua.bind(this)));this.GK.draw(this.getContainer())};gvjs_.zua=function(){this.nE=this.GK.zf();gvjs_oi(this.nE,gvjs_8N,this.yua.bind(this))};gvjs_.yua=function(a){gvjs_I(this,gvjs_9N,{startChanged:a.startChanged,endChanged:a.endChanged,inProgress:a.inProgress})};function gvjs_YP(a){gvjs_eO.call(this,a);this.ye=null}gvjs_o(gvjs_YP,gvjs_IO);gvjs_YP.prototype.vv=function(){return gvjs_XP};gvjs_YP.prototype.Mt=function(a,b,c){this.clear();this.ye=gvjs_PO(a,b);b=a.W(this.ye);if(b==gvjs_l||b==gvjs_zb)throw Error("The filter cannot operate on a column of type "+b+". Column type must be one of: number, date, datetime or timeofday. Column role must be domain, and correlate to a continuous axis.");c.__data__=a};
gvjs_YP.prototype.pG=function(a,b,c){a=new gvjs_N(a);b=c.range;if(gvjs_me(b)!=gvjs_h)return a;c=b.start;b=b.end;if(null==c&&null==b)return a;a.pp(a.at([{column:this.ye,minValue:c,maxValue:b}]));return a};function gvjs_ZP(a){gvjs_GO.call(this,a);this.Sp=-1;this.ig=this.LW=this.eX=null}gvjs_o(gvjs_ZP,gvjs_GO);gvjs_=gvjs_ZP.prototype;gvjs_.og=function(){return{columns:null}};gvjs_.Xl=function(a,b){a=gvjs_GO.prototype.Xl.call(this,a,b);a.values=this.ig;b=a.label;null==b&&(b=this.nP(),1<=b.length&&(b=b[0].mb(),null!=this.Sp&&(b=b.Ga(this.Sp),a.label=b)));return a};
gvjs_.Mt=function(a,b,c){this.clear();this.Sp=b.Aa("chartColumnIndex");this.LW=b.cb("chartColumnId");if(null==this.Sp){if(null==this.LW)throw Error("Either chartColumnIndex or chartColumnId must be specified.");for(var d=a.$(),e=0;e<d;e++)a.Ne(e)===this.LW&&(this.Sp=e);if(null==this.Sp||0>this.Sp)throw Error("Invalid column id");}if(null==this.Sp||0>this.Sp)throw Error("Invalid column index");d=b.fa("columns");if(Array.isArray(d)&&d.length)this.ig=d;else{d={string:{string:!0},discrete:{string:!0},
number:{number:!0},dateortime:{date:!0,datetime:!0,timeofday:!0},continuous:{number:!0,date:!0,datetime:!0,timeofday:!0}};b=(b=gvjs_J(b,"columnType"))&&d[b];this.eX={};d=[];e=a.$();for(var f=0;f<e;f++){var g=a.Ga(f),h=a.Ne(f),k=a.W(f);if(!b||b[k])this.eX[g]={index:f,id:h,label:g},d.push(g)}this.ig=d}this.GT=[{input:"dataColumnIndex",bg:"view.columns."+this.Sp}];this.mM(c)};
gvjs_.mM=function(a){a=a.selectedValues;if(null!=a&&(!Array.isArray(a)||1<a.length))throw Error("Invalid selectedValues: should be an array of length zero or one.");};gvjs_.UV=function(a,b,c){var d=c.selectedValues;return Array.isArray(d)&&1===d.length?(c.dataColumnIndex=this.eX[d[0]].index,gvjs_GO.prototype.UV.call(this,a,b,c)):a};function gvjs__P(a){gvjs_ZP.call(this,a)}gvjs_o(gvjs__P,gvjs_ZP);gvjs__P.prototype.vv=function(){return gvjs_fP};var gvjs_zia={day:864E5,hour:36E5,minute:6E4,second:1E3,millisecond:1};function gvjs_0P(a){var b=gvjs_1P(a);var c=a.split(" ");if(2===c.length){if(c=Number(c[0]),typeof c!==gvjs_g||isNaN(c))throw Error('Invalid number for increment: "'+a+'".');}else c=1;b=gvjs_zia[b];if(!b)throw Error('Invalid number for increment "'+a+'".');return c*b}function gvjs_1P(a){var b=a.length-1;a="s"===a.charAt(b)?a.substring(0,b):a;a=a.split(" ");return 2===a.length?a[1]:a[0]}
function gvjs_2P(a,b,c){a=Number(a);b=(a-c)%gvjs_0P(b);return a=new Date(a-b)}function gvjs_3P(a,b,c){a=Number(a);c=a-c;b=gvjs_0P(b);c%=b;return a=0===c?new Date(a):new Date(a+b-c)};function gvjs_4P(a){gvjs_MO.call(this,a);this.sj=this.Yc=null}gvjs_o(gvjs_4P,gvjs_MO);gvjs_=gvjs_4P.prototype;gvjs_.K5=function(){var a=this.Fc.getValue()+this.Op,b=a+this.Fc.Tl();this.hw&&gvjs_th(this.hw,this.Yc.Ob(new Date(a)));this.Pv&&gvjs_th(this.Pv,this.Yc.Ob(new Date(b)))};gvjs_.v2=function(a){var b=a.pb(gvjs_Fu);(a=String(a.fa("step")))&&!b.pattern&&(b.pattern=gvjs_Aia[gvjs_1P(a)]);this.Yc=new gvjs_Tj(b)};
gvjs_.draw=function(a,b){b=b||{};var c=new gvjs_Aj([b,gvjs_5P]);(b=gvjs_SO(b))||(b=new gvjs_MC);b.R(this.getContainer());var d=gvjs_J(c,"cssClass");d&&gvjs_VC(b.j(),d);gvjs_OO(this,b,a,c,gvjs_5P)};gvjs_.Ifa=function(a){this.sj=String(a.fa("step",gvjs_5P.step));var b=gvjs_0P(this.sj);this.Fc.ET(b);b=gvjs_0P(String(a.fa("unitIncrement",gvjs_5P.unitIncrement)));this.Fc.ZA=b;a=gvjs_0P(String(a.fa(gvjs_5N,gvjs_5P.blockIncrement)));this.Fc.Dm=a};gvjs_.xZ=function(a,b){return a.Aa(b)};
gvjs_.pea=function(a,b,c){var d=String(this.sj);a=new Date(a);var e=gvjs_1P(d);a=gvjs_2P(a,e,Number(new Date(1970,0,1))).valueOf();b=gvjs_3P(new Date(b),d,a).valueOf();c.lowValue=gvjs_2P(new Date(c.lowValue),d,a).valueOf();c.highValue=gvjs_3P(new Date(c.highValue),d,a).valueOf();return{minValue:a,maxValue:b,state:c}};
gvjs_.getState=function(){var a=gvjs_MO.prototype.getState.call(this);a.lowValue&&(a.lowValue=new Date(a.lowValue.valueOf()));a.highValue&&(a.highValue=new Date(a.highValue.valueOf()));return a};var gvjs_Aia={year:"yyyy",month:"yyyy-MM",day:"yyyy-MM-dd",hour:gvjs_aO,minute:gvjs_aO,second:"yy/MM/dd hh:mm:ssa",millisecond:"yy/MM/dd hh:mm:ss:SSSSa"},gvjs_5P={showRangeValues:!0,minValue:null,maxValue:null,cssClass:gvjs_6N,step:"day",unitIncrement:"day",blockIncrement:"day",orientation:gvjs_S};function gvjs_6P(a){gvjs_JO.call(this,a)}gvjs_o(gvjs_6P,gvjs_JO);gvjs_=gvjs_6P.prototype;gvjs_.vv=function(){return gvjs_4P};gvjs_.Xl=function(a,b){a=gvjs_JO.prototype.Xl.call(this,a,b);a.minValue=this.Xa;a.maxValue=this.Cb;null==a.label&&(a.label=this.sq);return a};gvjs_.x_=function(a,b){this.yT(gvjs_L(b,gvjs_ed,gvjs_7P(this,a,gvjs_Ov)));this.xT(gvjs_L(b,gvjs_cd,gvjs_7P(this,a,gvjs_Gv)))};
gvjs_.Mt=function(a,b,c){this.clear();this.ye=gvjs_PO(a,b);this.sq=a.Ga(this.ye);var d=a.W(this.ye);if(d!=gvjs_Lb&&d!=gvjs_Mb)throw Error(gvjs_wa+this.ye+" is not a date");this.x_(a,b);gvjs_KO(this,c)};function gvjs_7P(a,b,c){a=b.Sj(a.ye)[c];return Number(a)}gvjs_.U5=function(a){return Number(a)};gvjs_.getState=function(){var a=gvjs_JO.prototype.getState.call(this);a.lowValue&&(a.lowValue=new Date(a.lowValue.valueOf()));a.highValue&&(a.highValue=new Date(a.highValue.valueOf()));return a};
gvjs_.rZ=function(a,b,c){(a=gvjs_my(a,"ui",{}).step)||(a="day");return function(d){d=Number(d);return b<=d&&c>=d}};function gvjs_8P(a){gvjs_dO.call(this,a);this.K={}}gvjs_t(gvjs_8P,gvjs_dO);gvjs_8P.prototype.draw=function(a){this.K=a};gvjs_8P.prototype.getState=function(){return this.K};function gvjs_9P(a){gvjs_MO.call(this,a);this.sj=this.Yc=null;this.wn=0}gvjs_o(gvjs_9P,gvjs_MO);gvjs_=gvjs_9P.prototype;gvjs_.K5=function(){var a=this.Fc.getValue()+this.Op,b=a+this.Fc.Tl();a/=this.wn;b/=this.wn;this.hw&&gvjs_th(this.hw,this.Yc.Ob(a));this.Pv&&gvjs_th(this.Pv,this.Yc.Ob(b))};gvjs_.v2=function(a){var b=a.pb(gvjs_Fu);(a=Number(a.Aa("step")))&&null==b.fractionDigits&&(b.fractionDigits=a);this.Yc=new gvjs_gk(b)};
gvjs_.draw=function(a,b){b=b||{};var c=new gvjs_Aj([b,gvjs_$P]);(b=gvjs_SO(b))||(b=new gvjs_MC);b.R(this.getContainer());var d=gvjs_J(c,"cssClass");d&&gvjs_VC(b.j(),d);gvjs_OO(this,b,a,c,gvjs_$P)};
gvjs_.Ifa=function(a){var b=gvjs_$P.step,c=a.Aa(gvjs_ex);null!=c&&(c=Math.max(2,c),b=(this.Fc.kf()-this.Fc.lf())/c);b=Number(gvjs_L(a,"step",b));c=gvjs_L(a,"unitIncrement",gvjs_$P.unitIncrement);a=gvjs_L(a,gvjs_5N,gvjs_$P.blockIncrement);this.wn=Math.pow(10,gvjs_pA(b));b=Math.round(b*this.wn);c=Math.round(c*this.wn);a=Math.round(a*this.wn);this.Fc.ET(b);this.Fc.ZA=c;this.Fc.Dm=a;this.sj=b};gvjs_.xZ=function(a,b){return a.Aa(b)};
gvjs_.pea=function(a,b,c){var d=this.sj;a=Math.floor(a*this.wn);a-=(a-0)%d;b=gvjs_aQ(Math.ceil(b*this.wn),d,a);var e=c.lowValue*this.wn;c.lowValue=e-(e-a)%d;c.highValue=gvjs_aQ(c.highValue*this.wn,d,a);return{minValue:a,maxValue:b,state:c}};
gvjs_.getState=function(){var a=this.Fc;if(!a)return{lowValue:null,highValue:null,lowThumbAtMinimum:null,highThumbAtMaxium:null};var b=a.getValue(),c=a.Tl();return{lowValue:(b+this.Op)/this.wn,highValue:(b+c+this.Op)/this.wn,lowThumbAtMinimum:b===a.lf(),highThumbAtMaximum:b+c===a.kf()}};function gvjs_aQ(a,b,c){c=(a-c)%b;return 0===c?a:a+b-c}var gvjs_$P={showRangeValues:!0,minValue:null,maxValue:null,ticks:null,cssClass:gvjs_6N,format:{},step:1,unitIncrement:1,blockIncrement:10,orientation:gvjs_S};function gvjs_bQ(a){gvjs_JO.call(this,a)}gvjs_o(gvjs_bQ,gvjs_JO);gvjs_=gvjs_bQ.prototype;gvjs_.vv=function(){return gvjs_9P};gvjs_.Xl=function(a,b){a=gvjs_JO.prototype.Xl.call(this,a,b);a.minValue=this.Xa;a.maxValue=this.Cb;null==a.label&&(a.label=this.sq);return a};gvjs_.x_=function(a,b){this.yT(gvjs_L(b,gvjs_ed,a.Sj(this.ye).min));this.xT(gvjs_L(b,gvjs_cd,a.Sj(this.ye).max))};
gvjs_.Mt=function(a,b,c){this.clear();this.ye=gvjs_PO(a,b);this.sq=a.Ga(this.ye);if(a.W(this.ye)!==gvjs_g)throw Error(gvjs_wa+this.ye+" is not numeric");this.x_(a,b);gvjs_KO(this,c)};gvjs_.U5=function(a){return gvjs_jg(String(a))};gvjs_.rZ=function(a,b,c){(a=gvjs_my(a,"ui",{}).step)||(a=1);return function(d){return b<=d&&c>=d}};function gvjs_cQ(a){gvjs_HO.call(this,a)}gvjs_o(gvjs_cQ,gvjs_HO);gvjs_cQ.prototype.vv=function(){return gvjs_9P};function gvjs_dQ(a,b){this.Pya=a;this.ig=b}gvjs_dQ.prototype.getUrl=function(){return this.Pya};gvjs_dQ.prototype.Ne=function(a){return this.ig[a].id};gvjs_dQ.prototype.W=function(a){return this.ig[a].type};gvjs_dQ.prototype.$=function(){return this.ig.length};function gvjs_eQ(a){gvjs_eO.call(this,a);this.ye=-1}gvjs_o(gvjs_eQ,gvjs_IO);gvjs_=gvjs_eQ.prototype;gvjs_.og=function(){return{matchType:gvjs_wd,caseSensitive:!1,useFormattedValue:!1}};gvjs_.Xl=function(a,b){a=gvjs_IO.prototype.Xl.call(this,a,b);null==a.label&&(a.label=this.sq);return a};gvjs_.Mt=function(a,b){this.clear();this.ye=gvjs_PO(a,b);this.sq=a.Ga(this.ye)};
gvjs_.pG=function(a,b,c){var d=gvjs_K(b,"caseSensitive"),e=gvjs_J(b,"matchType"),f=gvjs_K(b,gvjs_$N),g=this.ye;b=[];c=String(c.value);if(!c)return new gvjs_N(a);d||(c=c.toLowerCase());for(var h=0;h<a.ca();h++){var k=f?a.Ha(h,g):""+a.getValue(h,g);d||(k=k.toLowerCase());switch(e){case "exact":k==c&&b.push(h);break;case "any":-1!=k.indexOf(c)&&b.push(h);break;default:0==k.indexOf(c)&&b.push(h)}}a=new gvjs_N(a);a.pp(b);return a};gvjs_.sq=null;function gvjs_fQ(a){gvjs_dO.call(this,a);this.tm=0;this.zi=null}gvjs_o(gvjs_fQ,gvjs_dO);gvjs_fQ.prototype.getState=function(){return{value:this.zi?this.zi.value:null}};
gvjs_fQ.prototype.draw=function(a,b){b=b||{};var c=gvjs_SO(b);c||(c=new gvjs_MC);c.R(this.getContainer());var d=b.cssClass?String(b.cssClass):"google-visualization-controls-stringfilter";gvjs_VC(c.j(),d);d=gvjs_4(gvjs_Na);d.setAttribute(gvjs_5c,gvjs_pe(this.getContainer())+"-input");gvjs_Vd in a&&a.value&&(d.value=String(a.value));gvjs_7N in b&&d.setAttribute(gvjs_7N,b.placeholder);"realtimeTrigger"in b&&!b.realtimeTrigger?(this.addEventListener(d,gvjs_lv,this.rba,!1,this),this.addEventListener(d,
gvjs_Kt,this.ru,!1,this)):this.addEventListener(d,gvjs_mv,this.rba);this.zi=d;c.ib().appendChild(this.zi)};gvjs_fQ.prototype.rba=function(a){this.tm&&gvjs_ql(this.tm);13==a.keyCode?(this.ru(),a.preventDefault()):this.tm=gvjs_pl(function(){this.tm=0;this.ru()},200,this)};gvjs_fQ.prototype.ru=function(){gvjs_I(this,gvjs_9N,null)};function gvjs_gQ(a){gvjs_eQ.call(this,a)}gvjs_o(gvjs_gQ,gvjs_eQ);gvjs_gQ.prototype.vv=function(){return gvjs_fQ};function gvjs_hQ(a){gvjs_eO.call(this,a)}gvjs_o(gvjs_hQ,gvjs_eO);gvjs_hQ.prototype.i7=function(){return this.apply()};gvjs_hQ.prototype.apply=function(){if(!this.mb())throw Error(gvjs_ZN);this.Zc();this.getState();return this.mb()};gvjs_q("google.visualization.Choreographer",gvjs_ho,void 0);gvjs_ho.prototype.bind=gvjs_ho.prototype.bind;gvjs_ho.prototype.clear=gvjs_ho.prototype.clear;gvjs_ho.prototype.dispose=gvjs_ho.prototype.pa;gvjs_ho.prototype.isDisposed=gvjs_ho.prototype.fh;gvjs_ho.prototype.draw=gvjs_ho.prototype.draw;gvjs_q(gvjs_gc,gvjs_so,void 0);gvjs_so.prototype.bind=gvjs_so.prototype.bind;gvjs_so.prototype.getSelection=gvjs_so.prototype.getSelection;gvjs_so.prototype.clear=gvjs_so.prototype.clear;
gvjs_so.prototype.dispose=gvjs_so.prototype.pa;gvjs_so.prototype.isDisposed=gvjs_so.prototype.fh;gvjs_so.prototype.draw=gvjs_so.prototype.draw;gvjs_q("google.visualization.Control",gvjs_eO,void 0);gvjs_eO.prototype.draw=gvjs_eO.prototype.draw;gvjs_eO.prototype.getState=gvjs_eO.prototype.getState;gvjs_eO.prototype.resetControl=gvjs_eO.prototype.Gw;gvjs_eO.prototype.clear=gvjs_eO.prototype.clear;gvjs_eO.prototype.dispose=gvjs_eO.prototype.pa;gvjs_eO.prototype.isDisposed=gvjs_eO.prototype.fh;
gvjs_q(gvjs_kc,gvjs_IO,void 0);gvjs_IO.prototype.applyFilter=gvjs_IO.prototype.xB;gvjs_q(gvjs_Hc,gvjs_hQ,void 0);gvjs_hQ.prototype.applyOperator=gvjs_hQ.prototype.i7;gvjs_q("google.visualization.ControlUi",gvjs_dO,void 0);gvjs_dO.prototype.draw=gvjs_dO.prototype.draw;gvjs_dO.prototype.getState=gvjs_dO.prototype.getState;gvjs_dO.prototype.clear=gvjs_dO.prototype.clear;gvjs_dO.prototype.dispose=gvjs_dO.prototype.pa;gvjs_dO.prototype.isDisposed=gvjs_dO.prototype.fh;gvjs_q(gvjs_Sc,gvjs_gQ,void 0);
gvjs_gQ.prototype.draw=gvjs_gQ.prototype.draw;gvjs_gQ.prototype.applyFilter=gvjs_gQ.prototype.xB;gvjs_gQ.prototype.getState=gvjs_gQ.prototype.getState;gvjs_gQ.prototype.resetControl=gvjs_gQ.prototype.Gw;gvjs_gQ.prototype.clear=gvjs_gQ.prototype.clear;gvjs_gQ.prototype.dispose=gvjs_gQ.prototype.pa;gvjs_gQ.prototype.isDisposed=gvjs_gQ.prototype.fh;gvjs_q(gvjs_Tc,gvjs_fQ,void 0);gvjs_fQ.prototype.draw=gvjs_fQ.prototype.draw;gvjs_fQ.prototype.getState=gvjs_fQ.prototype.getState;
gvjs_fQ.prototype.clear=gvjs_fQ.prototype.clear;gvjs_fQ.prototype.isDisposed=gvjs_fQ.prototype.fh;gvjs_q(gvjs_Ec,gvjs_bQ,void 0);gvjs_bQ.prototype.draw=gvjs_bQ.prototype.draw;gvjs_bQ.prototype.applyFilter=gvjs_bQ.prototype.xB;gvjs_bQ.prototype.getState=gvjs_bQ.prototype.getState;gvjs_bQ.prototype.resetControl=gvjs_bQ.prototype.Gw;gvjs_bQ.prototype.clear=gvjs_bQ.prototype.clear;gvjs_bQ.prototype.dispose=gvjs_bQ.prototype.pa;gvjs_bQ.prototype.isDisposed=gvjs_bQ.prototype.fh;gvjs_q(gvjs_ic,gvjs_6P,void 0);
gvjs_6P.prototype.draw=gvjs_6P.prototype.draw;gvjs_6P.prototype.applyFilter=gvjs_6P.prototype.xB;gvjs_6P.prototype.getState=gvjs_6P.prototype.getState;gvjs_6P.prototype.resetControl=gvjs_6P.prototype.Gw;gvjs_6P.prototype.clear=gvjs_6P.prototype.clear;gvjs_6P.prototype.dispose=gvjs_6P.prototype.pa;gvjs_6P.prototype.isDisposed=gvjs_6P.prototype.fh;gvjs_q(gvjs_Gc,gvjs_9P,void 0);gvjs_9P.prototype.draw=gvjs_9P.prototype.draw;gvjs_9P.prototype.getState=gvjs_9P.prototype.getState;
gvjs_9P.prototype.clear=gvjs_9P.prototype.clear;gvjs_9P.prototype.dispose=gvjs_9P.prototype.pa;gvjs_9P.prototype.isDisposed=gvjs_9P.prototype.fh;gvjs_q(gvjs_jc,gvjs_4P,void 0);gvjs_4P.prototype.draw=gvjs_4P.prototype.draw;gvjs_4P.prototype.getState=gvjs_4P.prototype.getState;gvjs_4P.prototype.clear=gvjs_4P.prototype.clear;gvjs_4P.prototype.dispose=gvjs_4P.prototype.pa;gvjs_4P.prototype.isDisposed=gvjs_4P.prototype.fh;gvjs_q(gvjs_Fc,gvjs_cQ,void 0);gvjs_cQ.prototype.draw=gvjs_cQ.prototype.draw;
gvjs_cQ.prototype.apply=gvjs_cQ.prototype.apply;gvjs_cQ.prototype.getState=gvjs_cQ.prototype.getState;gvjs_cQ.prototype.resetControl=gvjs_cQ.prototype.Gw;gvjs_cQ.prototype.clear=gvjs_cQ.prototype.clear;gvjs_cQ.prototype.dispose=gvjs_cQ.prototype.pa;gvjs_cQ.prototype.isDisposed=gvjs_cQ.prototype.fh;gvjs_q(gvjs_dc,gvjs__P,void 0);gvjs__P.prototype.draw=gvjs__P.prototype.draw;gvjs__P.prototype.apply=gvjs__P.prototype.apply;gvjs__P.prototype.getState=gvjs__P.prototype.getState;
gvjs__P.prototype.resetControl=gvjs__P.prototype.Gw;gvjs__P.prototype.clear=gvjs__P.prototype.clear;gvjs__P.prototype.dispose=gvjs__P.prototype.pa;gvjs__P.prototype.isDisposed=gvjs__P.prototype.fh;gvjs_q(gvjs_9b,gvjs_sP,void 0);gvjs_sP.prototype.draw=gvjs_sP.prototype.draw;gvjs_sP.prototype.applyFilter=gvjs_sP.prototype.xB;gvjs_sP.prototype.getState=gvjs_sP.prototype.getState;gvjs_sP.prototype.resetControl=gvjs_sP.prototype.Gw;gvjs_sP.prototype.clear=gvjs_sP.prototype.clear;
gvjs_sP.prototype.dispose=gvjs_sP.prototype.pa;gvjs_sP.prototype.isDisposed=gvjs_sP.prototype.fh;gvjs_q(gvjs_Oc,gvjs_fP,void 0);gvjs_fP.prototype.draw=gvjs_fP.prototype.draw;gvjs_fP.prototype.getState=gvjs_fP.prototype.getState;gvjs_fP.prototype.clear=gvjs_fP.prototype.clear;gvjs_fP.prototype.dispose=gvjs_fP.prototype.pa;gvjs_fP.prototype.isDisposed=gvjs_fP.prototype.fh;gvjs_q(gvjs_$b,gvjs_YP,void 0);gvjs_YP.prototype.draw=gvjs_YP.prototype.draw;gvjs_YP.prototype.applyFilter=gvjs_YP.prototype.xB;
gvjs_YP.prototype.getState=gvjs_YP.prototype.getState;gvjs_YP.prototype.resetControl=gvjs_YP.prototype.Gw;gvjs_YP.prototype.clear=gvjs_YP.prototype.clear;gvjs_YP.prototype.dispose=gvjs_YP.prototype.pa;gvjs_YP.prototype.isDisposed=gvjs_YP.prototype.fh;gvjs_q(gvjs_ac,gvjs_XP,void 0);gvjs_XP.prototype.draw=gvjs_XP.prototype.draw;gvjs_XP.prototype.getState=gvjs_XP.prototype.getState;gvjs_XP.prototype.clear=gvjs_XP.prototype.clear;gvjs_XP.prototype.dispose=gvjs_XP.prototype.pa;
gvjs_XP.prototype.isDisposed=gvjs_XP.prototype.fh;gvjs_q(gvjs_pc,gvjs_8P,void 0);gvjs_8P.prototype.draw=gvjs_8P.prototype.draw;gvjs_8P.prototype.getState=gvjs_8P.prototype.getState;gvjs_8P.prototype.clear=gvjs_8P.prototype.clear;gvjs_8P.prototype.dispose=gvjs_8P.prototype.pa;gvjs_8P.prototype.isDisposed=gvjs_8P.prototype.fh;gvjs_q("google.visualization.RemoteDataSource",gvjs_dQ,void 0);gvjs_dQ.prototype.getUrl=gvjs_dQ.prototype.getUrl;gvjs_dQ.prototype.getColumnId=gvjs_dQ.prototype.Ne;
gvjs_dQ.prototype.getColumnType=gvjs_dQ.prototype.W;gvjs_dQ.prototype.getNumberOfColumns=gvjs_dQ.prototype.$;gvjs_q(gvjs_Lc,gvjs_HP,void 0);gvjs_HP.prototype.draw=gvjs_HP.prototype.draw;gvjs_HP.prototype.clearChart=gvjs_HP.prototype.Jb;gvjs_HP.prototype.getRange=gvjs_HP.prototype.vP;gvjs_HP.prototype.setRange=gvjs_HP.prototype.Ewa;