var gvjs_6X="ABCDEFGHIJKLMNOPQRSTUVWXYZ",gvjs_7X="allValuesSuffix",gvjs_8X="annotationsContainer",gvjs_9X="annotationsFilterContainer",gvjs_$X="background-color",gvjs_aY="chartContainer",gvjs_bY="containerTable",gvjs_cY="dateFormat",gvjs_dY="displayAnnotations",gvjs_eY="displayDateBarSeparator",gvjs_fY="displayLegendDots",gvjs_gY="displayLegendValues",gvjs_hY="displayRangeSelector",gvjs_iY="displayZoomButtons",gvjs_jY="numberFormats",gvjs_kY="outerChartContainer",gvjs_lY="zoomButtons.";
function gvjs_Eka(a){return void 0!==a.lastElementChild?a.lastElementChild:gvjs_nh(a.lastChild,!1)}function gvjs_mY(a,b,c){var d=a.W(c);if(d!==gvjs_Lb&&d!==gvjs_Mb)throw Error(gvjs_wa+c+" must be of type date or datetime, but is "+(d+"."));return a.getValue(b,c)}
var gvjs_Fka={annotationsWidth:25,annotationsFilter:"off",scaleValues:null,dateFormat:"MMMM dd, yyyy",displayRangeSelector:!0,displayAnnotations:!0,displayAnnotationsFilter:!1,displayZoomButtons:!0,zoomButtons:{"1-second":{label:"1s",offset:[0,0,1]},"5-seconds":{label:"5s",offset:[0,0,5]},"10-seconds":{label:"10s",offset:[0,0,10]},"15-seconds":{label:"15s",offset:[0,0,15]},"1-minute":{label:"1min",offset:[0,1,0]},"5-minutes":{label:"5min",offset:[0,5,0]},"10-minutes":{label:"10min",offset:[0,10,0]},
"15-minutes":{label:"15min",offset:[0,15,0]},"1-hour":{label:"1h",offset:[1,0,0]},"6-hours":{label:"6h",offset:[6,0,0]},"1-day":{label:"1d",offset:[1,0,0,0,0]},"5-days":{label:"5d",offset:[5,0,0,0,0]},"1-week":{label:"1w",offset:[7,0,0,0,0]},"1-month":{label:"1m",offset:[1,0,0,0,0,0]},"3-months":{label:"3m",offset:[3,0,0,0,0,0]},"6-months":{label:"6m",offset:[6,0,0,0,0,0]},"1-year":{label:"1y",offset:[1,0,0,0,0,0,0]},max:{label:gvjs_Gv,range:{start:null,end:null}}},zoomButtonsOrder:["1-hour","1-day",
"5-days","1-week","1-month","3-months","6-months","1-year",gvjs_Gv],displayLegendDots:!0,displayDateBarSeparator:!0,displayExactValues:!1,fill:0,lclt:0,labelColors:null,allowHtml:!1},gvjs_Gka={annotations:{textStyle:{fontSize:10,auraColor:gvjs_f},boxStyle:{stroke:"#888888",strokeWidth:.5,rx:2,ry:2,gradient:{color1:"#eeeeee",color2:"#dddddd",x1:gvjs_Ro,y1:gvjs_Ro,x2:gvjs_Ro,y2:gvjs_So,useObjectBoundingBoxUnits:!0}}},backgroundColor:gvjs_ea,chartArea:{width:gvjs_So,backgroundColor:gvjs_ea},height:200,
width:gvjs_So,hAxis:{baselineColor:gvjs_f,slantedText:!1,maxAlternation:1,gridlines:{count:-1},textStyle:{fontSize:9}},vAxis:{baselineColor:"#ababab",gridlines:{count:-1,color:"#ECECF7"},textPosition:gvjs_Fp,inTextPosition:"high",viewWindowMode:gvjs_Lv},legend:{position:gvjs_f,alignment:gvjs_R},colors:gvjs_MF,targetAxisIndex:1,focusTarget:gvjs_Ht,tooltip:{trigger:gvjs_f},candlestick:{hollowIsRising:!0},forceIFrame:!1,animation:{duration:0}},gvjs_Hka={filterColumnIndex:0,ui:{chartType:gvjs_na,chartOptions:{chartArea:{width:gvjs_So,
height:gvjs_So,backgroundColor:{fill:gvjs_ea,stroke:"#ababab",strokeWidth:.5}},height:40,width:gvjs_So,backgroundColor:gvjs_ea,areaOpacity:.1,lineWidth:1,forceIFrame:!1,hAxis:{baselineColor:gvjs_f,slantedText:!1,maxAlternation:1,gridlines:{},textPosition:gvjs_Fp,textStyle:{fontSize:9}},vAxis:{baselineColor:gvjs_f,scaleType:gvjs_Vv}},sideScreenColor:{fill:"#f2f2f2",fillOpacity:.75},zoomAroundSelection:!0,chartView:{columns:[0,1]}}},gvjs_Ika={width:gvjs_So,height:gvjs_So,allowHtml:!0,sortAscending:!1,
sortColumn:0};function gvjs_nY(a){gvjs_Qn.call(this,a);this.hb=null;this.IH=!0;this.ra=null;this.Gj=0;this.$M=this.RV=this.Eu=this.Ri=this.Dx=this.Du=this.rh=this.aa=this.mG=this.im=this.Cc=this.K=this.m=this.su=null;this.NI={};this.Wq=this.lO=this.IE=this.ig=null;this.ea=new gvjs_KA;this.zd=new gvjs_8q(this);this.e_=!1;this.D=gvjs_Oh()}gvjs_o(gvjs_nY,gvjs_Qn);gvjs_=gvjs_nY.prototype;
gvjs_.He=function(){this.ea.removeAll();gvjs_E(this.zd);this.zd=new gvjs_8q(this);gvjs_E(this.ea);this.ea=new gvjs_KA;this.e_=!1;this.Ri&&this.Ri.clear();this.rh&&this.rh.clear();this.aa&&this.aa.clear();this.container&&this.D.qc(this.container)};gvjs_.uv=function(){return this.aa.zf()};gvjs_.getSelection=function(){var a=this;return this.uv().getSelection().map(function(b){b=gvjs_oY(a,b.row,b.column);return{row:b.row,column:b.column}})};
gvjs_.setSelection=function(a){var b=this,c=this.uv();null==a||0===a.length?c.setSelection([]):(a=a.map(function(d){d=gvjs_pY(b,d.row,d.column);return{row:d.row,column:d.column}}),c.setSelection(a))};gvjs_.U$=function(){return this.rh.getState().range};gvjs_.setVisibleChartRange=function(a,b,c){this.rh.setState({range:{start:a,end:b}});this.rh.draw();gvjs_qY(this,null==c?!0:c)};gvjs_.Waa=function(a){gvjs_rY(this,a,!0)};gvjs_.Nfa=function(a){gvjs_rY(this,a,!1)};
function gvjs_rY(a,b,c){Array.isArray(b)||(b=[b]);for(var d=0;d<b.length;d++)a.NI[b[d]]=c;a.Qt()}gvjs_.Qt=function(){this.draw(this.ra,this.su,this.K)};
gvjs_.Rd=function(a,b,c,d){this.su=c||{};this.K=d||{};this.lM(b);this.z_(b);gvjs_Jka(this);a=this.Ni=new gvjs_N(this.ra);a.Hn(this.ig);b=a.at([{column:this.Gj,test:function(e){return null!=e}}]);a.pp(b);b=a.bn(this.Gj);a.pp(b);b=gvjs_mY(this.Ni,0,this.Gj);c=gvjs_mY(this.Ni,this.Ni.ca()-1,this.Gj);this.nO={min:b,max:c};this.VO();gvjs_Kka(this);gvjs_sY(this);gvjs_Lka(this);gvjs_Mka(this);gvjs_Nka(this);gvjs_Oka(this);gvjs_Pka(this);gvjs_Qka(this);this.aa.zh(a);this.rh.zh(a);this.rh.draw();gvjs_qY(this,
!1)};gvjs_.z_=function(a){this.ra=a;this.Kt()};gvjs_.lM=function(a){if(!a)throw Error(gvjs_as);var b=a.$();if(2>b)throw Error(gvjs_$r);if(a.W(0)!=gvjs_Lb&&a.W(0)!=gvjs_Mb)throw Error("First column must contain date, or date and time.");for(var c,d,e=!1,f=0,g=1;g<b&&!e;g++)c=a.W(g),c==gvjs_g?f=1:0==f?(e=!0,d=g):1==f?c==gvjs_l?f=2:(e=!0,d=g):2==f&&(c==gvjs_l?f=0:(e=!0,d=g));if(e)throw Error("Each values column may be followed by one or two annotation columns. column number "+d+gvjs_fr+c);};
function gvjs_Kka(a){var b=a.hb;b&&b.AS&&gvjs_C(b.AS,gvjs_ku,gvjs_f);var c=a.getHeight(a.m),d=a.La(a.m);if(b){gvjs_Cz(b.AS,d,c);gvjs_C(b.AS,gvjs_ku,"");var e=gvjs_Jh(b.GG);a.Pa=c-(e.top+e.bottom);a.ga=d-(e.left+e.right);gvjs_Cz(b.GG,a.ga,a.Pa)}else{b=a.hb={};var f=a.D;f.qc(a.container);gvjs_WC(a.container,["google-visualization-atl","container"]);var g=a.container.id+"_AnnotationChart_";e=function(l,m,n){var p=f.createElement(gvjs_Ob);l&&(p.id=g+l);p.className=m;n.appendChild(p);return p};var h=b.AS=
e("","",a.container);gvjs_C(h,gvjs_vd,gvjs_zd);gvjs_Cz(h,d,c);h=e("","",h);gvjs_C(h,gvjs_vd,gvjs_c);gvjs_sz(h,0,0);gvjs_Cz(h,gvjs_So,gvjs_So);h=b.GG=e("borderDiv","border",h);h=b.wCa=e(gvjs_bY,gvjs_bY,h);var k=gvjs_Jh(b.GG);a.Pa=c-(k.top+k.bottom);a.ga=d-(k.left+k.right);gvjs_Cz(b.GG,a.ga,a.Pa);a=b.rCa=e("chartTd","td chartTdContainer",h);c=b.SV=e("annotationsTd","td annotationsTdContainer",h);d=b.iEa=e(gvjs_kY,gvjs_kY,a);h=b.vla=e("chartControlsContainer","chartControls",d);b.KF=e("zoomControlContainer",
"zoomControls",h);b.Lsa=e("legendContainer",gvjs_rv,h);b.tla=e(gvjs_aY,gvjs_aY,d);b.L2=e("rangeControlContainer","rangeControl",a);b.nG=e(gvjs_9X,gvjs_9X,c);b.QV=b.QV=e(gvjs_8X,gvjs_8X,c)}}
function gvjs_Nka(a){var b=1+gvjs_Oj(a.Cc,["series.0.pointSize",gvjs_jw],6),c=gvjs_Gh(a.hb.vla).height,d=gvjs_K(a.m,gvjs_hY)?gvjs_L(a.im,"ui.chartOptions.height"):0;c=a.Pa-(c+d);var e=Math.max(b,gvjs_L(a.Cc,gvjs_2o,0)),f=Math.max(b,2+2*gvjs_L(a.Cc,"hAxis.textStyle.fontSize"));f=Math.max(f,gvjs_L(a.Cc,gvjs_Zo,0));gvjs_hq(a.Cc,1,{height:c,chartArea:{top:e,bottom:f,height:c-(e+f)}});gvjs_hq(a.im,1,{ui:{chartOptions:{chartArea:{height:d}}}});d=0;a.IH?(d=a.mG.fa(gvjs_Xd,gvjs_ub),gvjs_Bz(a.hb.SV,d),d=gvjs_Dz(a.hb.SV).width,
d=Math.max(0,d)):gvjs_Bz(a.hb.SV,0);d=a.ga-d;c=Math.max(b,gvjs_L(a.Cc,gvjs_0o,0));b=Math.max(b,gvjs_L(a.Cc,gvjs_1o,0));e=d-(c+b);gvjs_hq(a.Cc,1,{width:d,chartArea:{left:c,right:b,width:e}});gvjs_hq(a.im,1,{ui:{chartOptions:{width:d,chartArea:{left:c+1,right:b+2,width:e-3}}}})}
function gvjs_Oka(a){a.aa||(a.aa=new gvjs_Q({chartType:gvjs_GP,container:a.hb.tla}));a.rh||(a.rh=new gvjs_P({controlType:gvjs_YP,container:a.hb.L2}),gvjs_si(a.rh,gvjs_i,function(){gvjs_oi(a.rh,gvjs_Hd,a.Lqa.bind(a))}));if(a.IH){var b=gvjs_K(a.m,"displayAnnotationsFilter"),c=function(){var d=a.IH&&b?gvjs_Dz(a.hb.nG).height:0;a.hb.QV.style.height=gvjs_rz(a.Pa-d+gvjs_T,!0)};a.oG||(a.oG=new gvjs_P({controlType:gvjs_gQ,container:a.hb.nG,options:{filterColumnLabel:"Text",matchType:"any",useFormattedValue:!0,
ui:{label:"Filter",labelSeparator:": "}}}));gvjs_C(a.hb.nG,gvjs_ku,b?"":gvjs_f);a.Ri||(a.Ri=new gvjs_Q({chartType:gvjs_hM,container:a.hb.QV}),gvjs_si(a.Ri,gvjs_i,function(){gvjs_oi(a.Ri,gvjs_k,a.Uqa.bind(a))}));a.Du?c():(a.Du=new gvjs_so(a.hb.nG),a.Du.bind(a.oG,a.Ri),gvjs_si(a.Du,gvjs_i,c))}else gvjs_cg(a.hb.nG,gvjs_9f),a.Ri&&(a.Ri.clear(),a.Ri=null),a.oG&&(a.oG.clear(),a.oG=null),a.Du&&(a.Du.clear(),a.Du=null);a.e_||(a.e_=!0,gvjs_oi(a.aa,gvjs_i,a.w0.bind(a)),gvjs_si(a.aa,gvjs_i,function(){var d=
a.uv();gvjs_oi(d,gvjs_k,a.pqa.bind(a));gvjs_oi(d,gvjs_7v,a.rqa.bind(a));gvjs_oi(d,gvjs_6v,a.qqa.bind(a))}))}gvjs_.w0=function(){this.zd&&this.zd.dispatchEvent(gvjs_i)};gvjs_.Lqa=function(){var a=this.rh.getState();gvjs_qY(this,!1);this.zd.dispatchEvent(gvjs_8N,a.range)};function gvjs_qY(a,b){var c=a.rh.getState();a.aa.ba("hAxis.viewWindow",{min:c.range.start,max:c.range.end});c=a.aa.getOption(gvjs_Ws);b&&0===c&&a.aa.ba(gvjs_Ws,150);a.aa.draw();a.aa.ba(gvjs_Ws,c)}
function gvjs_Jka(a){a.ig=[{label:"Datetime",type:a.ra.W(a.Gj),calc:function(g,h){return{v:g.getValue(h,a.Gj),p:{dataRow:h}}}}];a.IE=[];for(var b=0,c=a.Gj+1,d=a.ra.$();c<d;){var e=c,f={label:a.ra.Ga(c)+"  ",sourceColumn:c,properties:{dataColumn:e,viewColumn:a.ig.length}};a.NI[b]&&(f.type=gvjs_g,f.calc=function(){return null});a.ig.push(f);a.IE.push(f);c++;c<d&&a.ra.W(c)===gvjs_l&&(c++,c<d&&a.ra.W(c)===gvjs_l&&c++,a.NI[b]||a.ig.push({calc:function(g){return function(h,k){return(h=gvjs_tY(a,k,g))?h.key:
null}}(e),type:gvjs_l,role:gvjs_Zs,properties:{dataColumn:e}}));b++}for(c=b=0;c<a.IE.length;c++)if(!a.NI[c]){b=c;break}gvjs_hq(a.im,1,{ui:{chartView:{columns:[0,a.IE[b].properties.viewColumn]}}});gvjs_hq(a.im,1,{ui:{chartOptions:{colors:[a.Kb[b%a.Kb.length]]}}})}
gvjs_.VO=function(){function a(){return("      "+b(f++)).substr(-e)}function b(n){return 26<=n?b(Math.floor(n/26)-1)+gvjs_6X[n%26]:gvjs_6X[n]}var c=this.ra.$(),d=this.ra.ca();this.Eu=[];this.RV={};for(var e=Math.ceil(Math.log(d)/Math.log(26)),f=0,g=0;g<d;g++)for(var h=this.Gj+1;h<c;){var k=h;h++;if(h<c&&this.ra.W(h)===gvjs_l){var l=h,m=null;h++;h<c&&this.ra.W(h)===gvjs_l&&(m=h,h++);(k=gvjs_Rka(this,this.Eu.length,g,k,l,m,a))&&gvjs_Ska(this,k)}}this.IH=gvjs_K(this.m,gvjs_dY)&&0<this.Eu.length};
function gvjs_Rka(a,b,c,d,e,f,g){e=e&&a.ra.getValue(c,e);f=f&&a.ra.getValue(c,f);return e||f?(g=g(),a=a.ra.getValue(c,a.Gj),{idx:b,key:g,title:e,text:f,date:a,EX:c,Bs:d}):null}
function gvjs_Tka(a){a.Dx=new gvjs_M;a.Dx.xd(gvjs_l,"Key");a.Dx.xd(gvjs_l,"Text");a.$M=[];for(var b=[],c=0;c<a.Eu.length;c++){var d=a.Eu[c],e='<button type="button" class="key">'+gvjs_dg(d.key)+"</button>",f=d.date;a.lO&&(f=gvjs_dg(a.lO.Ob(d.date)));var g=d.title||"";d=d.text||"";gvjs_K(a.m,gvjs_Us)||(g=gvjs_dg(g),d=gvjs_dg(d));b.push([e,'<span class="title">'+g+'</span> <span class="description">'+d+'</span> <span class="date">'+f+"</span> "])}a.Dx.Yn(b);var h=a.Dx.ca();b.forEach(function(k,l){a.Dx.Gfa(l,
"idx",h-l-1);a.$M[h-l-1]=l})}function gvjs_Pka(a){if(a.IH){gvjs_Tka(a);var b=gvjs_jq(a.mG);b.width=gvjs_So;b.height=gvjs_So;a.Ri.setOptions(b);a.Du.draw(a.Dx)}}
gvjs_.Kt=function(){this.m=new gvjs_Aj([this.su,gvjs_Fka]);this.Cc=new gvjs_Aj([gvjs_my(this.m,gvjs_Bb),gvjs_Gka]);this.im=new gvjs_Aj([gvjs_my(this.m,gvjs_sw),gvjs_Hka]);this.mG=new gvjs_Aj([gvjs_my(this.m,gvjs_Ld),gvjs_Ika]);var a=this.m.cb(gvjs_ht);a&&(gvjs_C(this.hb.GG,gvjs_$X,a),gvjs_hq(this.Cc,1,{backgroundColor:a}),gvjs_hq(this.im,1,{ui:{chartOptions:{backgroundColor:a}}}));gvjs_hq(this.Cc,1,{colors:this.m.fa(gvjs_2t)});this.Kb=this.Cc.fa(gvjs_2t);gvjs_hq(this.im,1,{ui:{chartOptions:{colors:[this.Kb[0]]}}});
typeof this.m.fa(gvjs_np)===gvjs_g&&gvjs_hq(this.Cc,1,{areaOpacity:gvjs_L(this.m,gvjs_np)/100,seriesType:gvjs_at});a=gvjs_K(this.m,gvjs_hv,!1);gvjs_hq(this.Cc,1,{interpolateNulls:a});gvjs_hq(this.im,1,{ui:{chartOptions:{interpolateNulls:a}}});gvjs_hq(this.Cc,1,{vAxis:{maxValue:this.m.fa(gvjs_Gv),minValue:this.m.fa(gvjs_Ov)}});if(a=this.m.fa("scaleColumns"))if(0===a.length)gvjs_hq(this.Cc,1,{vAxis:{textPosition:gvjs_f}});else{for(var b=1===a.length,c={},d=0;d<a.length;d++)c[a[d]]=b?{targetAxisIndex:1}:
{targetAxisIndex:d};gvjs_hq(this.Cc,1,{series:c})}else gvjs_hq(this.Cc,1,{vAxis:{targetAxisIndex:1}});this.m.fa(gvjs_Ew)&&(this.m.fa(gvjs_Ew)===gvjs_wu||"allfixed"===this.m.fa(gvjs_Ew))&&gvjs_hq(this.Cc,1,{vAxis:{baseline:0}});this.ra.W(this.Gj)===gvjs_Mb?gvjs_hq(this.m,1,{minDisplaySeconds:60,dateFormat:"HH:mm MMMM dd, yyyy",minTimelineGranularity:0}):gvjs_hq(this.m,1,{minDisplaySeconds:86400,dateFormat:"MMMM dd, yyyy",minTimelineGranularity:86400});a=this.m.fa(gvjs_cY);a=typeof a===gvjs_l?{pattern:gvjs_J(this.m,
gvjs_cY)}:gvjs_my(this.m,gvjs_cY);this.lO=new gvjs_Tj(a);a=this.m.fa(gvjs_jY);if(typeof a===gvjs_l)a={pattern:gvjs_J(this.m,gvjs_jY)},this.Wq=new gvjs_gk(a);else if(gvjs_r(a)){var e=[];this.Wq=e;gvjs_w(gvjs_my(this.m,gvjs_jY),function(f,g){f={pattern:f};g=parseInt(g,10);e[g]=new gvjs_gk(f)})}else gvjs_K(this.m,"displayExactValues")?this.Wq=null:this.Wq=new gvjs_gk({pattern:"#.##"});a=gvjs_J(this.m,"scaleFormat","#.########")+gvjs_J(this.m,gvjs_7X,"");gvjs_hq(this.Cc,1,{vAxis:{format:a}});a=this.m.Aa("thickness");
gvjs_hq(this.Cc,1,{lineWidth:null!=a?Math.max(1,a):1});a=this.m.fa("annotationsWidth");typeof a===gvjs_g?gvjs_hq(this.mG,1,{width:a+"%"}):a&&gvjs_hq(this.mG,1,{width:a});this.ula="newRow"===gvjs_J(this.m,"legendPosition","sameRow")?"twoRows":"oneRow";gvjs_hq(this.im,1,{ui:{chartOptions:{width:this.Cc.fa(gvjs_Xd)}}});gvjs_hq(this.im,1,{ui:{chartOptions:{chartArea:{width:this.Cc.fa(gvjs_3o)}}}});this.m.fa("async",!1)&&(gvjs_hq(this.Cc,1,{async:!0}),gvjs_hq(this.im,1,{ui:{chartOptions:{async:!0}}}))};
function gvjs_Qka(a){var b=a.rh.getState()||{};b.range=b.range||{};var c=a.m.fa("zoomEndTime");null!=c&&(b.range.end=c);c=a.m.fa("zoomStartTime");null!=c&&(b.range.start=c);a.rh.setState(b);gvjs_K(a.m,gvjs_hY)?a.hb.L2.style.display="":a.hb.L2.style.display=gvjs_f;b=gvjs_jq(a.Cc);a.aa.setOptions(b);b=gvjs_jq(a.im);a.rh.setOptions(b)}
function gvjs_Lka(a){if(gvjs_K(a.m,"displayAggregationButtons")){var b=[{id:"daily",label:"Daily",modCalc:function(g){if(null!=g)return new Date(g.getFullYear(),g.getMonth(),g.getDate(),0)}},{id:"weekly",label:"Weekly",modCalc:function(g){if(null!=g)return new Date(g.getFullYear(),g.getMonth(),g.getDate()-g.getDay())}},{id:"monthly",label:"Monthly",modCalc:function(g){if(null!=g)return new Date(g.getFullYear(),g.getMonth(),1)}},{id:"year",label:"Yearly",modCalc:function(g){if(null!=g)return new Date(g.getFullYear(),
0,1)}}],c=a.hb.KF.id;var d="Aggregate: ";for(var e=0;e<b.length;e++){var f=b[e];d+=' <button type="button" id="'+(c+"_"+f.id)+'" href="#">'+gvjs_dg(f.label)+"</button>"}d+="<br />";b=function(g){for(var h=0;h<g.length;h++)if(null!==g[h])return g[h]};c=[];d=a.ra.$();for(e=a.Gj+1;e<d;)c.push({column:e,type:gvjs_g,label:a.ra.Ga(e),aggregation:gvjs_Mo}),e++,e<d&&(c.push({column:e,type:gvjs_l,label:a.ra.Ga(e),aggregation:b}),e++,e<d&&(c.push({column:e,type:gvjs_l,label:a.ra.Ga(e),aggregation:b}),e++))}}
function gvjs_Mka(a){var b=a.hb.KF.id,c=gvjs_K(a.m,gvjs_iY),d=gvjs_Fj(a.m,gvjs_Ij,[],"zoomButtonsOrder",void 0,void 0),e=a.D;e.qc(a.hb.KF);if(c){e.append(a.hb.KF,"Zoom: ");c={};for(var f=0;f<d.length;c={XF:c.XF,hV:c.hV},f++){var g=d[f];if(!a.m.pb(gvjs_lY+g))break;var h=gvjs_J(a.m,gvjs_lY+g+".className","zoomButton"),k=gvjs_J(a.m,gvjs_lY+g+".label",g);h=gvjs_5f(gvjs_Bt,{type:gvjs_Bt,id:b+"_"+g,"class":h,href:"#"},k);c.XF=gvjs_4x(e.dd,h);e.append(a.hb.KF,c.XF);c.XF=gvjs_Eka(a.hb.KF);c.hV=gvjs_Uka(a,
g).bind(a);gvjs_si(a,gvjs_i,function(l){return function(){a.ea.o(l.XF,gvjs_Wt,l.hV)}}(c))}}}
function gvjs_Uka(a,b){var c=a.m.fa(gvjs_lY+b+".offset"),d;c&&(d=gvjs_pk(c));var e=a.m.pb(gvjs_lY+b+".range");return function(){var f=a.rh.getState();var g=f.range.end;null==g&&(g=a.nO.max);if(c&&null!=g){g=gvjs_zA(g,d);var h=a.nO.min;g=g.getTime()>h.getTime()?g:h;h={start:g}}else e&&(h=e);void 0!==h.start&&(f.range.start=h.start);void 0!==h.end&&(f.range.end=h.end);a.rh.setState(f);a.rh.draw();gvjs_qY(a,!0)}}
gvjs_.qqa=function(a){a=gvjs_oY(this,a.row,a.column);this.zd.dispatchEvent(gvjs_6v,{row:a.row,column:a.column});var b;a=this.getSelection();0<a.length&&(b=a[0].row);gvjs_sY(this,b||void 0)};gvjs_.rqa=function(a){var b=gvjs_oY(this,a.row,a.column);this.zd.dispatchEvent(gvjs_7v,{row:b.row,column:b.column});a=this.aa.mb().getProperty(a.row,this.Gj,"dataRow");gvjs_sY(this,a)};
function gvjs_sY(a,b){for(var c=gvjs_9f,d=0;d<a.IE.length;d++)if(!a.NI[d]){var e=a.IE[d],f=e.properties.dataColumn,g=a.Kb[d%a.Kb.length];g&&g.color&&(g=g.color);var h=gvjs_K(a.m,gvjs_fY)?gvjs_5f(gvjs_Ob,{"class":"legend-dot",style:gvjs_Hf({"background-color":g})}):gvjs_9f;c=gvjs_$f(c,gvjs_5f(gvjs_0w,{style:gvjs_Hf({color:g})},gvjs_$f(h,e.label)));null!=b&&gvjs_K(a.m,gvjs_gY,!0)&&(f=a.ra.getValue(b,f),null!==f&&(e=f,g=null,a.Wq&&(g=Array.isArray(a.Wq)?a.Wq[d]:a.Wq),g&&(e=g.Ob(f)),(f=a.m.cb(gvjs_7X))&&
(e+=f),c=gvjs_$f(c,": ",e)));c=gvjs_$f(c,gvjs__y("&nbsp;&nbsp;"))}if(null!=b){var k=a.ra.getValue(b,a.Gj);k=a.lO.Ob(k)}"oneRow"===a.ula?(b=a.m.fa(gvjs_eY),b=!0===b?"|&nbsp;":!1===b?"&nbsp; &nbsp;":b.toString(),c=k?gvjs_$f(c,gvjs__y(b),k):c):c=gvjs_$f(k?k:"",gvjs__y("&nbsp;&nbsp;"),gvjs_5f("br"),c);gvjs_cg(a.hb.Lsa,c)}function gvjs_oY(a,b,c){var d=a.aa.mb();return{row:null!=b?d.getProperty(b,a.Gj,"dataRow"):null,column:null!=c?d.Bd(c,"dataColumn"):null}}
function gvjs_pY(a,b,c){return{row:null==b?null:a.Ni.GZ(b),column:null==c?null:a.Ni.S$(c)}}gvjs_.pqa=function(){this.zd.dispatchEvent(gvjs_k);if(this.Ri&&!this.Laa){var a=this.Ri.zf();if(a){var b;if((b=this.uv().getSelection())&&b.length){b=b[0];var c=b.column;b=!c||1>c?null:b}else b=null;b?(b=gvjs_oY(this,b.row,b.column),(b=gvjs_tY(this,b.row,b.column))?(c=this.Ri.mb(),b=c.ca()-c.GZ(this.$M[b.idx])-1,a.setSelection([{row:b}])):a.setSelection([])):a.setSelection([])}}};
function gvjs_tY(a,b,c){b=[String(b),String(c)].join();return a.Eu[a.RV[b]]}function gvjs_Ska(a,b){var c=b.EX+","+b.Bs,d=b.idx;a.Eu.push(b);a.RV[c]=d}
gvjs_.Uqa=function(){var a=this,b=this.uv(),c=this.Ri.zf().getSelection()[0];if(c){this.Laa=!0;var d=this.Ri.mb();c=d.ca()-d.fj(c.row)-1;var e=this.Eu[this.$M[c]];c=function(){var f=a.aa.Zc().hAxis.viewWindow,g=f&&f.min&&f.min.getTime()||-Infinity;f=f&&f.max&&f.max.getTime()||Infinity;var h=e.date.getTime(),k=gvjs_pY(a,e.EX,e.Bs);return h>=g&&h<=f?(b.setSelection([{row:k.row,column:k.column+1}]),a.Laa=!1,!0):!1};c()||(d=gvjs_i,gvjs_Oj(this.Cc,gvjs_Ws)&&(d=gvjs_Ys),gvjs_si(b,d,c),gvjs_Vka(this,e.EX))}else b.setSelection([])};
function gvjs_Vka(a,b){var c=a.nO.min.getTime(),d=a.nO.max.getTime(),e=a.aa.Zc().hAxis.viewWindow,f=e&&e.min&&e.min.getTime()||c;e=e&&e.max&&e.max.getTime()||d;b=a.ra.getValue(b,a.Gj).getTime();f=e-f;b=Math.max(c,b-Math.round(f/2));d=Math.min(d,b+f);b=Math.max(c,d-f);a.setVisibleChartRange(new Date(b),new Date(d),!0)};gvjs_q(gvjs_3b,gvjs_nY,void 0);gvjs_nY.prototype.clearChart=gvjs_nY.prototype.Jb;gvjs_nY.prototype.draw=gvjs_nY.prototype.draw;gvjs_nY.prototype.getContainer=gvjs_nY.prototype.getContainer;gvjs_nY.prototype.getSelection=gvjs_nY.prototype.getSelection;gvjs_nY.prototype.getVisibleChartRange=gvjs_nY.prototype.U$;gvjs_nY.prototype.setVisibleChartRange=gvjs_nY.prototype.setVisibleChartRange;gvjs_nY.prototype.showDataColumns=gvjs_nY.prototype.Nfa;gvjs_nY.prototype.hideDataColumns=gvjs_nY.prototype.Waa;