function gvjs_lma(a){var b="maps";b=gvjs_Bj(a,b);var c=new gvjs_hj;gvjs_u(a.Gd,function(d){(d=gvjs_Dj(d,b))&&typeof d===gvjs_h&&c.addAll(Object.keys(d))});return c.ob()}
var gvjs_mma={TAa:gvjs_0v,SATELLITE:"satellite",TERRAIN:"terrain",HYBRID:gvjs_uT},gvjs_nma={mapType:gvjs_uT,icons:{"default":{normal:"//maps.google.com/mapfiles/ms/micons/red-dot.png",selected:"//maps.google.com/mapfiles/ms/micons/blue-dot.png"}},enableScrollWheel:!1,showTip:!1,showLine:!1,lineColor:"#0033ff",lineWidth:10,useMapTypeControl:!1,zoomLevel:null};function gvjs_S_(a){gvjs_Qn.call(this,a);this.Sd=new gvjs_wi(this,this.container,!0);this.er=new gvjs_LT;this.D1=this.dK=this.fK=0;this.m=this.Of=this.eR=this.vB=this.Nq=this.Ze=this.vF=this.UM=this.OQ=null;this.Qfa=this.Ln=!1}gvjs_o(gvjs_S_,gvjs_Qn);gvjs_=gvjs_S_.prototype;gvjs_.Rd=function(a,b,c){try{gvjs_JT(gvjs_s(this.jna,this,b,c))}catch(d){this.Sd.Sc(d.message||"error: cannot draw map")}};
gvjs_.jna=function(a,b){b=gvjs_Li(gvjs_Ii(b||{}));this.m=new gvjs_Aj([b,gvjs_nma]);b=this.container;this.er.cancel();this.Sd.removeAll();if(a){var c=0;gvjs_y&&(c=7>gvjs_Dg?50:6);b.offsetWidth<=c&&(b.style.width=this.La(this.m,400)+gvjs_T);b.offsetHeight<=c&&(b.style.height=this.getHeight(this.m,400)+gvjs_T);try{var d=a.$();if(0==d)throw Error(gvjs_nT);b=[];b.push(a.W(0));if(b[0]==gvjs_l){if(3<d)throw Error("Only 1-3 columns allowed in address mode.");}else{if(2>d)throw Error("At least 2 columns are required in lat/long mode");
b.push(a.W(1));if(b[0]!=gvjs_g)throw Error("First column must be numbers in lat/long mode.");if(b[1]!=gvjs_g)throw Error("Second column must be numbers in lat/long mode.");if(4<d)throw Error("Only 2-4 columns allowed in lat/long mode.");}}catch(g){this.Sd.Sc(gvjs_pT);return}this.Yj();this.dK=d=a.ca();400<d&&(this.dK=400,gvjs_8x(this.Sd,"Some of the data rows were truncated"));b=a.$();(d=a.W(0)==gvjs_l)?(c=1<b?1:0,b=2<b?2:-1):(c=2<b?2:-1,b=3<b?3:-1);if(d){d=c;for(c=0;c<this.dK;c++)this.UM[c]={address:a.getStringValue(c,
0)||""},this.vF[c]=-1!=d?a.Ha(c,d):a.Ha(c,0),this.Ze[c]=-1!==b?a.getStringValue(c,b)||gvjs_eu:gvjs_eu;null!=this.UM&&this.er.create(this.UM,gvjs_s(this.cqa,this))}else{d=c;for(c=0;c<this.dK;c++){var e=a.getValue(c,0),f=a.getValue(c,1);null!=e&&null!=f&&90>e&&-90<e&&180>f&&-180<f?(this.vF[c]=-1!=d?a.Ha(c,d):e+" "+f,this.Ze[c]=-1!==b?a.getStringValue(c,b)||gvjs_eu:gvjs_eu,e=new google.maps.LatLng(e,f,!0),this.OQ.push({point:e,title:this.vF[c]}),this.eR.push(c),this.vB.push(this.D1++)):this.vB.push(-1)}gvjs_oma(this)}}else this.Sd.Sc(gvjs_as)};
function gvjs_pma(a,b){switch(a){case gvjs_uT:return google.maps.MapTypeId.HYBRID;case gvjs_0v:return google.maps.MapTypeId.ROADMAP;case "satellite":return google.maps.MapTypeId.SATELLITE;case "terrain":return google.maps.MapTypeId.TERRAIN}return b}
gvjs_.Yj=function(){var a=this.m;this.Of=new gvjs_$n;var b=gvjs_K(a,"showTip");this.Ln=gvjs_K(a,"showInfoWindow",b);this.Qfa=gvjs_K(a,gvjs_Uw,b);this.OQ=[];this.UM=[];this.vF=[];this.Ze=[];this.Nq=[];this.vB=[];this.eR=[];this.D1=this.dK=this.fK=0;b={mapTypeControl:gvjs_K(a,gvjs_BT),mapTypeControlOptions:{},navigationControl:!0,scrollwheel:gvjs_K(a,gvjs_tT),navigationControlOptions:{style:gvjs_K(a,gvjs_AT)?google.maps.ZoomControlStyle.DEFAULT:google.maps.ZoomControlStyle.SMALL}};var c={},d={},e=gvjs_lma(a);
if(0<e.length){e.forEach(function(h){d[h]=a.view(gvjs_Cj("maps",h))});var f=0;gvjs_w(d,function(h,k){var l=h.cb(gvjs_Zv);null!=l&&(f++,c[k]=new google.maps.StyledMapType(gvjs_my(h,"styles"),{name:l}))});e=a.cD("mapTypeIds");null!=e?e=e.map(function(h){return gvjs_pma(h,h)},this):0<f&&(e=[google.maps.MapTypeId.ROADMAP,google.maps.MapTypeId.TERRAIN,google.maps.MapTypeId.SATELLITE,google.maps.MapTypeId.HYBRID].concat(gvjs_Ye(c)));b.mapTypeControlOptions.mapTypeIds=e}this.qa=new google.maps.Map(this.container,
b);gvjs_w(c,function(h,k){this.qa.mapTypes.set(k,h)},this);this.aJ=new google.maps.InfoWindow;b=this.qa;e=google.maps.MapTypeId.HYBRID;var g=a.cb(gvjs_vT);null!=g&&g in c?e=g:(g=gvjs_J(a,gvjs_vT,void 0,gvjs_mma),e=gvjs_pma(g,e));b.setMapTypeId(e)};gvjs_.cqa=function(a){for(var b=0;b<a.length;b++)a[b]&&a[b][0]?(this.OQ.push({point:a[b][0].geometry.location,title:this.Ln?this.vF[this.fK]:null}),this.eR.push(this.fK),this.vB.push(this.D1++)):this.vB.push(-1),this.fK+=1;gvjs_oma(this)};
function gvjs_oma(a){var b=a.OQ;if(0==b.length)gvjs_8x(a.Sd,"No data points to show on map");else{for(var c=a.qa,d=new google.maps.LatLngBounds,e,f,g=[],h=0;h<b.length;h++)if(e=b[h],f=e.point)g.push(f),d.extend(f);f=a.m;h=f.Aa("zoomLevel");null!=h?(c.setZoom(h),c.setCenter(d.getCenter())):c.fitBounds(d);for(h=0;h<b.length;h++)d=a.Ze[h],e=b[h],e.point&&(d={map:c,position:e.point,icon:gvjs_J(f,"icons."+d+".normal")},a.Qfa&&(d.title=e.title),a.Nq[h]=new google.maps.Marker(d),google.maps.event.addListener(a.Nq[h],
gvjs_Wt,gvjs_s(a.wqa,a,a.Nq[h],a.eR[h])));gvjs_K(f,gvjs_zT)&&(b=gvjs_J(f,"lineColor"),f=gvjs_L(f,"lineWeight"),(new google.maps.Polyline({path:g,strokeColor:b,strokeWeight:f})).setMap(c));google.maps.event.addListener(c,"tilesloaded",gvjs_s(gvjs_I,a,a,gvjs_i,null))}}
gvjs_.wqa=function(a,b){var c=gvjs_do(this.Of,b)?null:[{row:b}];this.setSelection(c);gvjs_I(this,gvjs_k,{});c&&this.Ln?(this.aJ.close(),b=this.vF[b],gvjs_K(this.m,gvjs_Us,!0)?(b=gvjs_OA(b),this.aJ.setContent(gvjs_4x(document,b))):this.aJ.setContent(document.createTextNode(String(b))),this.aJ.open(this.qa,a)):this.aJ.close()};
gvjs_.setSelection=function(a){var b=this.Of.setSelection(a);a=this.vB;for(var c=this.Nq,d=this.Ze,e,f,g=this.qa,h=gvjs_bo(b.An),k=0;k<h.length;k++)f=h[k],e=c[a[f]],f=d[a[f]],e&&e.setIcon(gvjs_J(this.m,"icons."+f+".normal"));b=gvjs_bo(b.uB);for(k=0;k<b.length;k++)f=b[k],e=c[a[f]],f=d[a[f]],e&&e.setIcon(gvjs_J(this.m,"icons."+f+".selected"));e&&g.panTo(e.getPosition())};gvjs_.getSelection=function(){return this.Of.getSelection()};gvjs_.Jb=function(){this.er.cancel()};gvjs_q(gvjs_Ac,gvjs_S_,void 0);gvjs_S_.prototype.draw=gvjs_S_.prototype.draw;gvjs_S_.prototype.setSelection=gvjs_S_.prototype.setSelection;gvjs_S_.prototype.getSelection=gvjs_S_.prototype.getSelection;