syntax = "proto3";

enum DirectInputBrand {
  DirectInputBrand_Unknown = 0;
  DirectInputBrand_Logitech = 1;
  DirectInputBrand_Fanatec = 2;
  DirectInputBrand_Thrustmaster = 3;
  DirectInputBrand_Moza = 4;
  DirectInputBrand_Simagic = 5;
}

enum InputAxis {
  InputAxis_Car_Steer = 0;
  InputAxis_Car_Gas = 1;
  InputAxis_Car_Brake = 2;
  InputAxis_Car_Clutch = 3;
  InputAxis_Car_Handbrake = 4;
  InputAxis_UI_LeftRight = 10;
  InputAxis_UI_UpDown = 11;
  InputAxis_Camera_PanY_Up = 100;
  InputAxis_Camera_PanY_Down = 101;
  InputAxis_Camera_PanY = 200;
  InputAxis_Camera_PanX_Left = 102;
  InputAxis_Camera_PanX_Right = 103;
  InputAxis_Camera_PanX = 202;
  InputAxis_Camera_PanZ_Forward = 104;
  InputAxis_Camera_PanZ_Backward = 105;
  InputAxis_Camera_PanZ = 204;
  InputAxis_Camera_PitchUp = 106;
  InputAxis_Camera_PitchDown = 107;
  InputAxis_Camera_Pitch = 206;
  InputAxis_Camera_YawLeft = 108;
  InputAxis_Camera_YawRight = 109;
  InputAxis_Camera_Yaw = 208;
  InputAxis_Camera_RollLeft = 110;
  InputAxis_Camera_RollRight = 111;
  InputAxis_Camera_Roll = 210;
}

enum InputAction {
  InputAction_Camera_Drone_Toggle = 0;
  InputAction_Editor_Quit = 5;
  InputAction_Editor_Undo = 6;
  InputAction_Editor_Redo = 7;
  InputAction_Editor_Save_Active = 8;
  InputAction_Editor_Save_All = 9;
  InputAction_Editor_Close_Active = 10;
  InputAction_Editor_Close_All = 11;
  InputAction_Editor_Gizmo_Translate = 12;
  InputAction_Editor_Gizmo_Rotate = 13;
  InputAction_Editor_Gizmo_Scale = 14;
  InputAction_Editor_Cut = 40;
  InputAction_Editor_Copy = 15;
  InputAction_Editor_Paste = 16;
  InputAction_Editor_Delete = 41;
  InputAction_Editor_Gizmo_Mode = 17;
  InputAction_Editor_VSyncToggle = 20;
  InputAction_Editor_CapFPSToggle = 21;
  InputAction_Editor_ViewPerspective = 22;
  InputAction_Editor_ViewOrthographic = 23;
  InputAction_Editor_ViewPhysics = 51;
  InputAction_Editor_FastOpen = 70;
  InputAction_Editor_TeleportCamera = 53;
  InputAction_Editor_ShowIrradianceVolume = 700;
  InputAction_Editor_ShowReflectionProbe = 701;
  InputAction_Editor_ShowGizmoSphere = 702;
  InputAction_Editor_RotationSpeedModifier = 704;
  InputAction_Editor_Spline_Move_Backward = 24;
  InputAction_Editor_Spline_Move_Forward = 25;
  InputAction_Editor_Spline_Delete = 26;
  InputAction_Editor_Spline_Insert_After = 27;
  InputAction_Editor_Spline_Insert_Before = 28;
  InputAction_Editor_Spline_Insert_At_Middle = 29;
  InputAction_Editor_Spline_Append_On_Click = 30;
  InputAction_Editor_Spline_Select_Next = 31;
  InputAction_Editor_Spline_Select_Previous = 32;
  InputAction_Editor_Spline_Cycle_Anchors = 33;
  InputAction_Editor_Spline_Add_Marker = 34;
  InputAction_Editor_Spline_Insert_Marker_After = 35;
  InputAction_Editor_Spline_Insert_Marker_Before = 36;
  InputAction_Editor_Spline_Toggle_Big_Nodes = 37;
  InputAction_Editor_Spline_Toggle_Lock_Anchor_Direction = 38;
  InputAction_Editor_Select_Closest_Pivot = 50;
  InputAction_Editor_Move_Selected_Here = 52;
  InputAction_Editor_Toggle_InstancePainting = 6897;
  InputAction_Editor_InstancePainting_BrushRadius_Plus = 7600;
  InputAction_Editor_InstancePainting_BrushRadius_Minus = 7601;
  InputAction_Editor_InstancePainting_BrushDensity_Plus = 7602;
  InputAction_Editor_InstancePainting_BrushDensity_Minus = 7603;
  InputAction_Editor_InstancePainting_MinDistance_Plus = 7604;
  InputAction_Editor_InstancePainting_MinDistance_Minus = 7605;
  InputAction_Editor_InstancePainting_MaxDistance_Plus = 7606;
  InputAction_Editor_InstancePainting_MaxDistance_Minus = 7607;
  InputAction_Editor_InstancePainting_ForceVertical = 7608;
  InputAction_Editor_InstancePainting_SingleInstance = 7609;
  InputAction_Editor_Favorite_X_10 = 60;
  InputAction_Editor_Show_Symbols = 61;
  InputAction_Editor_Renderer_Settings = 600;
  InputAction_Editor_Renderer_Debug = 601;
  InputAction_Editor_Renderer_Visualization = 602;
  InputAction_Editor_Renderer_Inspector = 605;
  InputAction_Editor_Renderer_HotReloadShaders = 606;
  InputAction_Editor_Switch_Preview_Source = 603;
  InputAction_Editor_Focus_On_Selected = 99;
  InputAction_Editor_Picking_Toggle = 1900;
  InputAction_Editor_Add_Coordinates_To_Procedural_Skip_List = 604;
  InputAction_Terrain_Recreate_Renderer = 200;
  InputAction_Terrain_Refresh_Vegetation = 201;
  InputAction_Terrain_Cycle_Debug_Visualization = 202;
  InputAction_Terrain_Toggle_Vegetation = 204;
  InputAction_Terrain_Pin_On_Terrain = 203;
  InputAction_Terrain_Build_Current_Quadrant = 205;
  InputAction_Editor_Road_Generate_Meshes_And_Linked_Intersections = 250;
  InputAction_Editor_Road_Generate_Meshes = 251;
  InputAction_Editor_Road_Compute_Camber = 252;
  InputAction_Reload_SelectedDevUiCar = 6666;
  InputAction_Weather_ForwardOneHour = 800;
  InputAction_Weather_BackOneHour = 801;
  InputAction_Car_Steer_Left = 100;
  InputAction_Car_Steer_Right = 101;
  InputAction_Car_Gas = 102;
  InputAction_Car_Brake = 103;
  InputAction_Car_Handbrake = 104;
  InputAction_Car_Clutch = 105;
  InputAction_Car_Paddle_Gear_X_2 = 110;
  InputAction_Car_Shifter_Gear_X_9 = 111;
  InputAction_Car_Shifter_Gear_Reverse = 113;
  InputAction_Car_Light_Cycle_X_2 = 120;
  InputAction_Car_Light_Direct_X_3 = 122;
  InputAction_Car_Flashing_Lights = 121;
  InputAction_Car_Rain_Lights = 131;
  InputAction_Car_Direction_Light_Left = 132;
  InputAction_Car_Direction_Light_Right = 133;
  InputAction_Car_Warning_Lights = 134;
  InputAction_Car_Retractable_HeadLights_Toggle = 135;
  InputAction_Car_Ignition_Toggle = 136;
  InputAction_Car_Starter = 137;
  InputAction_Car_Pit_Limiter_Toggle = 138;
  InputAction_Car_Horn = 139;
  InputAction_Car_TractionControl_Cycle_X_2 = 140;
  InputAction_Car_TractionControl_Direct_X_15 = 141;
  InputAction_Car_TractionControl_Cut_Cycle_X_2 = 142;
  InputAction_Car_TractionControl_Cut_Direct_X_15 = 143;
  InputAction_Car_ABS_Cycle_X_2 = 144;
  InputAction_Car_ABS_Direct_X_15 = 145;
  InputAction_Car_Engine_Map_Cycle_X_2 = 146;
  InputAction_Car_Engine_Map_Direct_X_10 = 147;
  InputAction_Car_Brake_Bias_Cycle_X_2 = 148;
  InputAction_Car_ESC_Cycle_X_2 = 149;
  InputAction_Car_ESC_Direct_X_10 = 150;
  InputAction_Car_Turbo_Level_Cycle_X_2 = 169;
  InputAction_Car_Ers_Recharge_Cycle_X_2 = 1700;
  InputAction_Car_Ers_Deployment_Cycle_X_2 = 1701;
  InputAction_Car_Ers_Heat_Charging_Toggle = 1702;
  InputAction_Car_Ers_Overtake = 1703;
  InputAction_Car_DRS_Toggle = 1704;
  InputAction_Car_PerformanceMode_Cycle_X_2 = 165;
  InputAction_Car_PerformanceMode_Direct_X_10 = 166;
  InputAction_Car_Display_Device_Cycle_X_2 = 123;
  InputAction_Car_Display_Device_Direct_X_5 = 124;
  InputAction_Car_Display_Page_Cycle_X_2 = 125;
  InputAction_Car_Display_Page_Direct_X_5 = 126;
  InputAction_Car_Front_Bump_Damper_Cycle_X_2 = 231;
  InputAction_Car_Front_Rebound_Damper_Cycle_X_2 = 232;
  InputAction_Car_Rear_Bump_Damper_Cycle_X_2 = 233;
  InputAction_Car_Rear_Rebound_Damper_Cycle_X_2 = 234;
  InputAction_Car_Ebb_Cycle_X_2 = 235;
  InputAction_Car_Diff_Power_Level_Cycle_X_2 = 236;
  InputAction_Car_Diff_Coast_Level_Cycle_X_2 = 237;
  InputAction_CarDev_WindshieldDirt_Inc = 151;
  InputAction_CarDev_WindshieldDirt_Dec = 152;
  InputAction_CarDev_WindshieldScratch_Inc = 153;
  InputAction_CarDev_WindshieldScratch_Dec = 154;
  InputAction_CarDev_Dirt_Inc = 171;
  InputAction_CarDev_Dirt_Dec = 172;
  InputAction_CarDev_Dust_Inc = 173;
  InputAction_CarDev_Dust_Dec = 174;
  InputAction_CarDev_Pickup_Inc = 175;
  InputAction_CarDev_Pickup_Dec = 176;
  InputAction_Car_Wipers_Cycle_X_2 = 155;
  InputAction_Car_Wipers_Direct_X_5 = 156;
  InputAction_UI_CycleNameplateVisibility = 159;
  InputAction_Car_Mirrors_Cycle_X_2 = 161;
  InputAction_Car_Mirrors_Pitch_X_2 = 162;
  InputAction_Car_Mirrors_Yaw_X_2 = 163;
  InputAction_Car_Mirrors_Fov_X_2 = 164;
  InputAction_UI_Toggle_Virtual_Mirror = 167;
  InputAction_Car_FFB_Gain_X_2 = 168;
  InputAction_Car_H_Shifter_Toggle = 299;
  InputAction_Dev_Toggle_Log_Bar = 300;
  InputAction_Dev_Toggle_Debug_Ui = 301;
  InputAction_Dev_Game_Quit = 302;
  InputAction_Camera_Drivable = 400;
  InputAction_Camera_OnBoardFree = 401;
  InputAction_Camera_Free = 402;
  InputAction_Camera_Track = 403;
  InputAction_Camera_Helicopter = 404;
  InputAction_Camera_Sequence = 405;
  InputAction_Camera_Onboard = 406;
  InputAction_Camera_PanUp = 410;
  InputAction_Camera_PanUp_Slow = 1410;
  InputAction_Camera_PanUp_Fast = 2410;
  InputAction_Camera_PanDown = 411;
  InputAction_Camera_PanDown_Slow = 1411;
  InputAction_Camera_PanDown_Fast = 2411;
  InputAction_Camera_PanLeft = 412;
  InputAction_Camera_PanLeft_Slow = 1412;
  InputAction_Camera_PanLeft_Fast = 2412;
  InputAction_Camera_PanRight = 413;
  InputAction_Camera_PanRight_Slow = 1413;
  InputAction_Camera_PanRight_Fast = 2413;
  InputAction_Camera_Forward = 414;
  InputAction_Camera_Forward_Slow = 1414;
  InputAction_Camera_Forward_Fast = 2414;
  InputAction_Camera_Backward = 415;
  InputAction_Camera_Backward_Slow = 1415;
  InputAction_Camera_Backward_Fast = 2415;
  InputAction_Camera_PitchUp = 420;
  InputAction_Camera_PitchUp_Slow = 1420;
  InputAction_Camera_PitchUp_Fast = 2420;
  InputAction_Camera_PitchDown = 421;
  InputAction_Camera_PitchDown_Slow = 1421;
  InputAction_Camera_PitchDown_Fast = 2421;
  InputAction_Camera_YawLeft = 416;
  InputAction_Camera_YawLeft_Slow = 1416;
  InputAction_Camera_YawLeft_Fast = 2416;
  InputAction_Camera_YawRight = 417;
  InputAction_Camera_YawRight_Slow = 1417;
  InputAction_Camera_YawRight_Fast = 2417;
  InputAction_Camera_RollLeft = 423;
  InputAction_Camera_RollLeft_Slow = 1423;
  InputAction_Camera_RollLeft_Fast = 2423;
  InputAction_Camera_RollRight = 422;
  InputAction_Camera_RollRight_Slow = 1422;
  InputAction_Camera_RollRight_Fast = 2422;
  InputAction_Camera_ResetView = 418;
  InputAction_Camera_CancelResetView = 419;
  InputAction_Camera_Zoom_Toggle = 424;
  InputAction_Camera_LookLeft = 425;
  InputAction_Camera_LookRight = 426;
  InputAction_Camera_LookBehind = 427;
  InputAction_Camera_Showroom_RotateCar = 430;
  InputAction_Camera_Showroom_InternalView = 431;
  InputAction_Camera_FovModifier = 435;
  InputAction_Dev_Replay_Save = 453;
  InputAction_Camera_Select_Next_Car = 501;
  InputAction_Camera_Select_Prev_Car = 502;
  InputAction_Camera_Select_Player_Car = 503;
  InputAction_UI_Up = 510;
  InputAction_UI_Down = 511;
  InputAction_UI_Left = 512;
  InputAction_UI_Right = 513;
  InputAction_UI_PageUp = 514;
  InputAction_UI_PageDown = 515;
  InputAction_UI_Confirm = 516;
  InputAction_UI_Cancel = 517;
  InputAction_UI_Menu = 518;
  InputAction_UI_ShowPoi = 519;
  InputAction_UI_ToggleHud = 520;
  InputAction_UI_Cycle_Mfd_Up = 521;
  InputAction_UI_Cycle_Mfd_Down = 522;
  InputAction_UI_Vr_Panel_Forward = 531;
  InputAction_UI_Vr_Panel_Backward = 532;
  InputAction_UI_Vr_Panel_ScaleUp = 533;
  InputAction_UI_Vr_Panel_ScaleDown = 534;
  InputAction_UI_Vr_Settings_Reset = 535;
  InputAction_AIDev_Possess_Focused_Car = 550;
  InputAction_AIDev_SaveSnapshot = 551;
  InputAction_AIDev_LoadSnapshot = 552;
  InputAction_AIDev_StartRecording = 553;
  InputAction_AIDev_SaveIdealLine = 554;
  InputAction_AIDev_SaveReferences = 555;
  InputAction_AIDev_Replay_Start = 556;
  InputAction_AIDev_Replay_Stop = 557;
  InputAction_AIDev_Replay_ResumeFromSnapshot = 558;
  InputAction_AIDev_Replay_ToggleReverse = 559;
  InputAction_AIDev_SaveGame = 560;
  InputAction_AIDev_RestoreGame = 561;
  InputAction_Showroom_Hood = 900;
  InputAction_Showroom_Tailgate = 901;
  InputAction_Showroom_Door_FL = 903;
  InputAction_Showroom_Door_FR = 904;
  InputAction_Showroom_Door_RL = 905;
  InputAction_Showroom_Door_RR = 906;
  InputAction_Showroom_Pedal_Accelerator = 907;
  InputAction_Showroom_Pedal_Brake = 908;
  InputAction_Showroom_Pedal_Clutch = 909;
  InputAction_Showroom_Gear_Shift_Up = 910;
  InputAction_Showroom_Gear_Shift_Down = 911;
  InputAction_Showroom_Hand_Brake = 912;
  InputAction_Car_Optional_Animation_X_5 = 913;
}

enum UIAxiiListenerMode {
  UIAxiiListenerMode_None = 0;
  UIAxiiListenerMode_VirtualMouseAxii = 1;
  UIAxiiListenerMode_InputControllerAxii = 2;
}

message UIActiveAxii {
  repeated string active_guid = 1;
}

message UIExInputsAction {
  InputAction action = 1;
  int32 action_payload = 2;
  int32 action_number = 3;
  string guid = 4;
}

message UIExInputsAxis {
  InputAxis axis = 1;
  float raw_value = 2;
  float current_value = 4;
  string guid = 3;
  int32 axis_index = 5;
}

message UIExInputsAxii {
  repeated UIExInputsAxis axii = 1;
}

message UIExInputShift {
  string guid = 4;
}
