;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;updated 2026.08 Game to patch 18/08/2026 								;;;
;;;FULL MATCH TO GAME														;;;
;;;																			;;;
;;;Wet (Black)																;;;
;;;Intermediate (Black)														;;;
;;;Dry (Black)																;;;
;;;Wet (S)																	;;;
;;;Wet (M)																	;;;
;;;Wet (H)																	;;;
;;;Intermediate (S)															;;;
;;;Intermediate (M)															;;;
;;;Intermediate (H)															;;;
;;;Dry (S+)																	;;;
;;;Dry (S)																	;;;
;;;Dry (M)																	;;;
;;;Dry (H)																	;;;
;;;Dry (H+)																	;;;
;;;Dry (Red)																;;;
;;;Dry (Yellow)																;;;
;;;Dry (White)																;;;
;;;Dry (Green)																;;;
;;;Dry (Blue)																;;;
;;;																			;;;
;;;Excludes following classes as no information in game						;;;
;;;																			;;;
;;;ADAC Esports GT Masters 													;;;
;;;ADAC Esports GT Masters 2021 											;;;
;;;DTM 2020 Esport 															;;;
;;;DTM Esports 2022 														;;;
;;;eSports WTCR 															;;;
;;;Esports WTCR Prologue 													;;;
;;;FRX-22 Esports 															;;;
;;;Mercedes-AMG Motorsport 													;;;
;;;Mercedes-AMG Motorsport 30 Years of DTM 									;;;
;;;RaceRoom Esports 														;;;
;;;Safety Cars 																;;;
;;;Shopping Cart 															;;;
;;;Super Racer 																;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[Compounds]
ADAC GT Masters 2013=Hard->Dry (H)
ADAC GT Masters 2014=Hard->Dry (H)
ADAC GT Masters 2015=Hard->Dry (H)
ADAC GT Masters 2018=Hard->Dry (H)
ADAC GT Masters 2020=Hard->Dry (H)
ADAC GT Masters 2021=Hard->Dry (H)
Alpine A110 Cup=Hard->Dry (H)
Aquila CR1 Cup=Hard->Dry (H)
Audi Sport TT Cup 2015=Hard->Dry (H)
Audi Sport TT Cup 2016=Hard->Dry (H)
Audi TT RS cup=Hard->Dry (H)
BMW M2 Cup=Hard->Dry (H)
BMW M235i Racing Cup=Hard->Dry (H)
Cayman GT4 Trophy by Manthey-Racing=Hard->Dry (H)
C-Klasse DTM 2005=Soft->Dry (S);Hard->Dry (H)
Crosslé 90F=Hard->Dry (H)
Crosslé 9S=Hard->Dry (H)
CUPRA Leon e-Racer=Hard->Dry (H)
Drift=Hard->Dry (H);Medium->Dry (M)
DTM 1992=Soft->Dry (S);Hard->Dry (H)
DTM 1995=Soft->Dry (S);Medium->Dry (M);Hard->Dry (H)
DTM 2002=Soft->Dry (S)
DTM 2003=Soft->Dry (S)
DTM 2013=Soft->Dry (S);Hard->Dry (H)
DTM 2014=Soft->Dry (S);Hard->Dry (H)
DTM 2015=Soft->Dry (S);Hard->Dry (H)
DTM 2016=Soft->Dry (S);Hard->Dry (H)
DTM 2020=Soft->Dry (S);Hard->Dry (H)
DTM 2021=Hard->Dry (H)
DTM 2023=Hard->Dry (H)
DTM 2024=Hard->Dry (H)
DTM 2025=Hard->Dry (H)
DTM 2026=Hard->Dry (H)
Ford Mustang Mach E=Hard->Dry (H)
FR US Cup=Alternate->Dry (S);Primary->Dry (H)
FR X-17 Cup=Soft->Dry (S);Medium->Dry (M);Hard->Dry (H)
FR X-22 Cup=Soft->Dry (S);Medium->Dry (M);Hard->Dry (H)
FR X-90 Cup=Soft->Dry (S);Medium->Dry (M);Hard->Dry (H)
FR2 Cup=Hard->Dry (H)
FR3 Cup=Hard->Dry (H)
FRJ Cup=Hard->Dry (H)
German Nationals=Hard->Dry (H)
Group 2=Hard->Dry (H)
Group 4=Soft->Dry (S);Hard->Dry (H)
Group 5=Soft->Dry (S);Medium->Dry (M);Hard->Dry (H)
Group C=Soft->Dry (S);Medium->Dry (M);Hard->Dry (H)
GT2=Hard->Dry (H)
GTE=Soft->Dry (S);Medium->Dry (M);Hard->Dry (H)
GTO Classics=Soft->Dry (S);Hard->Dry (H)
GTR 1=Hard->Dry (H)
GTR 2=Soft->Dry (S);Medium->Dry (M);Hard->Dry (H)
GTR 3=Hard->Dry (H)
GTR 4=Hard->Dry (H)
Hillclimb Icons=Supersoft->Dry (S+);Soft->Dry (S)
Hypercars=Soft->Dry (S);Medium->Dry (M);Hard->Dry (H)
KTM GTX=Hard->Dry (H)
KTM X-Bow RR Cup=Hard->Dry (H)
Mazda Dpi=Medium->Dry (M);Hard->Dry (H)
Mazda MX-5 Cup=Hard->Dry (H)
NSU TTS Cup=Hard->Dry (H)
NXT Gen Cup=Hard->Dry (H)
P1=Medium->Dry (M);Hard->Dry (H)
P2=Medium->Dry (M);Hard->Dry (H)
Porsche 944 Turbo Cup=Soft->Dry (S)
Porsche 964 Cup=Soft->Dry (S)
Porsche 991.2 GT3 Cup=Hard->Dry (H)
Porsche 992 GT3 Cup=Hard->Dry (H)
Porsche Carrera Cup Deutschland 2019=Hard->Dry (H)
Porsche Carrera Cup Deutschland 2023=Hard->Dry (H)
Porsche Carrera Cup North America 2024=Hard->Dry (H)
Porsche Carrera Cup Scandinavia=Hard->Dry (H)
Praga R1=Hard->Dry (H)
Procar=Soft->Dry (S);Hard->Dry (H)
Silhouette Series=Hard->Dry (H)
Super Touring=Soft->Dry (S);Medium->Dry (M);Hard->Dry (H)
Tatuus F4 Cup=Medium->Dry (M)
Touring Cars Cup=Hard->Dry (H)
Touring Classics=Soft->Dry (S);Hard
Truck Racing=Soft->Dry (S)
Volkswagen ID. R=Medium->Dry (M);Hard->Dry (H)
WTCC 2013=Hard->Dry (H)
WTCC 2014=Hard->Dry (H)
WTCC 2015=Hard->Dry (H)
WTCC 2016=Hard->Dry (H)
WTCC 2017=Hard->Dry (H)
WTCR 2018=Hard->Dry (H)
WTCR 2019=Hard->Dry (H)
WTCR 2020=Hard->Dry (H)
WTCR 2021=Hard->Dry (H)
WTCR 2022=Hard->Dry (H)
Zonda R Cup=Hard->Dry (H)

[Cars]
*;*=*->Dry
Audi R8 LMS Ultra;*=ADAC GT Masters 2013
BMW Z4 GT3;*=ADAC GT Masters 2013
Chevrolet Camaro GT3;*=ADAC GT Masters 2013
Chevrolet Corvette Z06.R GT3;*=ADAC GT Masters 2013
Ford GT GT3;*=ADAC GT Masters 2013
Mercedes-Benz SLS AMG GT3;*=ADAC GT Masters 2013
Nissan GT-R GT3;*=ADAC GT Masters 2013
Audi R8 LMS Ultra;*=ADAC GT Masters 2014
BMW Z4 GT3;*=ADAC GT Masters 2014
Chevrolet Camaro GT3;*=ADAC GT Masters 2014
Chevrolet Corvette Z06.R GT3;*=ADAC GT Masters 2014
McLaren MP4-12C GT3;*=ADAC GT Masters 2014
Mercedes-Benz SLS AMG GT3;*=ADAC GT Masters 2014
Audi R8 LMS Ultra;*=ADAC GT Masters 2015
Bentley Continental GT3;*=ADAC GT Masters 2015
BMW Z4 GT3;*=ADAC GT Masters 2015
Chevrolet Camaro GT3;*=ADAC GT Masters 2015
Chevrolet Corvette Z06.R GT3 GTM15;*=ADAC GT Masters 2015
Mercedes-Benz SLS AMG GT3;*=ADAC GT Masters 2015
Nissan GT-R GT3;*=ADAC GT Masters 2015
Audi R8 LMS;*=ADAC GT Masters 2018
BMW M6 GT3;*=ADAC GT Masters 2018
Callaway Corvette C7 GT3-R;*=ADAC GT Masters 2018
Mercedes AMG GT3;*=ADAC GT Masters 2018
Porsche 911 GT3 R;*=ADAC GT Masters 2018
Audi R8 LMS;*=ADAC GT Masters 2020
Audi R8 LMS GT3 EVO;*=ADAC GT Masters 2020
Bentley Continental GT3 EVO;*=ADAC GT Masters 2020
BMW M6 GT3;*=ADAC GT Masters 2020
Callaway Corvette C7 GT3-R;*=ADAC GT Masters 2020
Mercedes AMG GT3;*=ADAC GT Masters 2020
Mercedes-AMG GT3 2020;*=ADAC GT Masters 2020
Porsche 911 GT3 R (2019);*=ADAC GT Masters 2020
Audi R8 LMS GT3 EVO;*=ADAC GT Masters 2021
BMW M6 GT3;*=ADAC GT Masters 2021
Callaway Corvette C7 GT3-R;*=ADAC GT Masters 2021
Mercedes-AMG GT3 2020;*=ADAC GT Masters 2021
Porsche 911 GT3 R (2019);*=ADAC GT Masters 2021
Alpine A110 Cup;*=Alpine A110 Cup
Aquila CR1 Sports GT;*=Aquila CR1 Cup
Audi TT cup 2015;*=Audi Sport TT Cup 2015
Audi TT cup 2016;*=Audi Sport TT Cup 2016
Audi TT RS VLN;*=Audi TT RS cup
BMW M2 CS Racing 2021;*=BMW M2 Cup
BMW M235i Racing;*=BMW M235i Racing Cup
Porsche Cayman GT4 Clubsport;*=Cayman GT4 Trophy by Manthey-Racing
AMG-Mercedes C-Klasse DTM;*=C-Klasse DTM 2005
Crosslé 90F;*=Crosslé 90F
Crosslé 9S;*=Crosslé 9S
CUPRA Leon e-Racer;*=CUPRA Leon e-Racer
BMW E30 M3 Drift;*=Drift
BMW G82 M4 Drift;*=Drift
Audi V8 DTM;*=DTM 1992
BMW M3 Sport Evolution;*=DTM 1992
Ford Mustang GT DTM;*=DTM 1992
Mercedes 190E Evo II DTM;*=DTM 1992
Opel Omega 3000 Evo500;*=DTM 1992
Alfa Romeo 155 TI DTM 1995;*=DTM 1995
AMG-Mercedes C-Klasse DTM;*=DTM 1995
Opel Calibra V6 DTM;*=DTM 1995
Abt-Audi TT-R;*=DTM 2002
AMG-Mercedes CLK-DTM 2002;*=DTM 2002
Opel Astra V8 Coupé;*=DTM 2002
AMG-Mercedes CLK DTM;*=DTM 2003
Audi RS 5 DTM;*=DTM 2013
BMW M3 DTM ;*=DTM 2013
DTM Mercedes AMG C-Coupé;*=DTM 2013
Audi RS 5 DTM 2014;*=DTM 2014
BMW M4 DTM;*=DTM 2014
DTM Mercedes AMG C Coupe 14;*=DTM 2014
Audi RS 5 DTM 2015;*=DTM 2015
BMW M4 DTM 2015;*=DTM 2015
Mercedes-AMG C63 DTM;*=DTM 2015
Audi RS 5 DTM 2016;*=DTM 2016
BMW M4 DTM 2016;*=DTM 2016
Mercedes-AMG C 63 DTM 2016;*=DTM 2016
Audi RS 5 DTM 2020;*=DTM 2020
BMW M4 DTM 2020;*=DTM 2020
Audi R8 LMS GT3 EVO DTM;*=DTM 2021
BMW M6 GT3 DTM;*=DTM 2021
Ferrari 488 GT3 EVO 2020 DTM;*=DTM 2021
McLaren 720S GT3 DTM;*=DTM 2021
Mercedes-AMG GT3 2020 DTM;*=DTM 2021
Porsche 911 GT3 R (2019) DTM;*=DTM 2021
Audi R8 LMS GT3 EVO II DTM;*=DTM 2023
BMW M4 GT3 DTM;*=DTM 2023
Ferrari 296 GT3 DTM;*=DTM 2023
Mercedes-AMG GT3 2020 DTM;*=DTM 2023
Porsche 911 GT3 R (992) DTM;*=DTM 2023
Audi R8 LMS GT3 EVO II DTM;*=DTM 2024
BMW M4 GT3 DTM;*=DTM 2024
Ferrari 296 GT3 DTM;*=DTM 2024
Lamborghini Huracán GT3 EVO II DTM;*=DTM 2024
McLaren 720S GT3 EVO DTM;*=DTM 2024
Mercedes-AMG GT3 2020 DTM;*=DTM 2024
Porsche 911 GT3 R (992) DTM;*=DTM 2024
Audi R8 LMS GT3 EVO II DTM;*=DTM 2025
BMW M4 GT3 EVO DTM;*=DTM 2025
Ferrari 296 GT3 DTM;*=DTM 2025
Lamborghini Huracán GT3 EVO II DTM;*=DTM 2025
McLaren 720S GT3 EVO DTM;*=DTM 2025
Mercedes-AMG GT3 2020 DTM;*=DTM 2025
Porsche 911 GT3 R (992) DTM;*=DTM 2025
Aston Martin Vantage AMR GT3 EVO DTM;*=DTM 2026
BMW M4 GT3 EVO DTM;*=DTM 2026
Ford Mustang GT3 EVO DTM;*=DTM 2026
Lamborghini Temerario GT3 DTM;*=DTM 2026
McLaren 720S GT3 EVO DTM;*=DTM 2026
Mercedes-AMG GT3 2020 DTM;*=DTM 2026
Porsche 911 GT3 R (992.2) DTM;*=DTM 2026
Ford Mustang Mach-E 1400;*=Ford Mustang Mach E
Formula RaceRoom US;*=FR US Cup
Formula Raceroom X-17;*=FR X-17 Cup
Formula Raceroom X-22;*=FR X-22 Cup
Formula RR 90 V10;*=FR X-90 Cup
Formula RR 90 V12;*=FR X-90 Cup
Formula RR 90 V8;*=FR X-90 Cup
Formula RaceRoom 2;*=FR2 Cup
Formula RaceRoom 3;*=FR3 Cup
Formula RaceRoom Junior;*=FRJ Cup
Carlsson C25 GT;*=German Nationals
McLaren-Mercedes SLR 722 GT;*=German Nationals
Volkswagen Scirocco Gr2;*=Group 2
BMW M1 Gr. 4;*=Group 4
Porsche 934 Turbo RSR;*=Group 4
BMW 320 Turbo;*=Group 5
Chevrolet Corvette Greenwood 1977;*=Group 5
Chevrolet Dekon Monza;*=Group 5
Fabcar 935;*=Group 5
Nissan Silvia Turbo;*=Group 5
Nissan Skyline 2000RS;*=Group 5
Zakspeed Capri;*=Group 5
Nissan R90CK;*=Group C
Porsche 962 C Team Joest;*=Group C
Audi R8 LMS GT2 2019;*=GT2
KTM X-BOW GT2;*=GT2
Porsche 911 GT2 RS Clubsport;*=GT2
BMW M8 GTE;*=GTE
Porsche 911 RSR 2019;*=GTE
Audi 90 Quattro;*=GTO Classics
Ford Mustang IMSA GTO;*=GTO Classics
Nissan 300ZX Z32;*=GTO Classics
Ford GT GT1;*=GTR 1
Gumpert Apollo Sport;*=GTR 1
Koenigsegg CCGT;*=GTR 1
Nissan GT-R GT1;*=GTR 1
RUF CTR3;*=GTR 1
Saleen S7R;*=GTR 1
BMW M3 E92 GT;*=GTR 2
Cadillac CTS-V.R;*=GTR 2
Chevrolet Corvette C6.R ZR1;*=GTR 2
P4-5 Competizione GT2;*=GTR 2
RUF RT12R;*=GTR 2
Audi R8 LMS;*=GTR 3
Audi R8 LMS GT3 EVO;*=GTR 3
Audi R8 LMS GT3 EVO II;*=GTR 3
Audi R8 LMS Ultra;*=GTR 3
Bentley Continental GT3;*=GTR 3
Bentley Continental GT3 EVO;*=GTR 3
BMW Alpina B6 GT3;*=GTR 3
BMW M4 GT3;*=GTR 3
BMW M6 GT3;*=GTR 3
BMW Z4 GT3;*=GTR 3
Callaway Corvette C7 GT3-R;*=GTR 3
Chevrolet Camaro GT3;*=GTR 3
Chevrolet Corvette Z06.R GT3;*=GTR 3
Ferrari 296 GT3;*=GTR 3
Ferrari 488 GT3 EVO 2020;*=GTR 3
Ford GT GT3;*=GTR 3
Ford Mustang GT3;*=GTR 3
Lamborghini Huracán GT3 EVO II;*=GTR 3
McLaren 650S GT3;*=GTR 3
McLaren 720S GT3;*=GTR 3
McLaren MP4-12C GT3;*=GTR 3
Mercedes AMG GT3;*=GTR 3
Mercedes-AMG GT3 2020;*=GTR 3
Mercedes-Benz SLS AMG GT3;*=GTR 3
Nissan GT-R GT3;*=GTR 3
P4-5 Competizione GT3;*=GTR 3
Porsche 911 GT3 R;*=GTR 3
Porsche 911 GT3 R (2019);*=GTR 3
Porsche 911 GT3 R (992);*=GTR 3
Porsche 911 GT3 R (992.2);*=GTR 3
RUF RT12R GTR3;*=GTR 3
Alpine A110 GT4+;*=GTR 4
Audi R8 LMS GT4 2020;*=GTR 4
BMW M4 GT4 (F82);*=GTR 4
BMW M4 GT4 (G82);*=GTR 4
KTM X-Bow GT4;*=GTR 4
Lotus Evora GT4;*=GTR 4
McLaren 570s GT4;*=GTR 4
Mercedes AMG GT4 2020;*=GTR 4
Porsche 718 Cayman GT4 Clubsport;*=GTR 4
Porsche Cayman GT4 CS MR;*=GTR 4
BMW 134 Judd V8;*=Hillclimb Icons
Carlsson SLK 340 JUDD;*=Hillclimb Icons
E36 V8 JUDD;*=Hillclimb Icons
BMW M Hybrid V8;*=Hypercars
Lamborghini SC63;*=Hypercars
Porsche 963;*=Hypercars
KTM X-BOW GTX;*=KTM GTX
KTM X-Bow RR;*=KTM X-Bow RR Cup
Mazda RT24 P DPi;*=Mazda Dpi
Mazda MX-5 CUP 2019 ND2;*=Mazda MX-5 Cup
NSU TTS;*=NSU TTS Cup
LRT NXT1;*=NXT Gen Cup
Audi R18;*=P1
DMD P20;*=P1
Mistral M530;*=P1
Chevrolet Daytona Prototype;*=P2
DMD P21;*=P2
Mistral M531;*=P2
Radical SR9 AER;*=P2
Radical SR9 Judd;*=P2
Porsche 944 Turbo Cup;*=Porsche 944 Turbo Cup
Porsche 911 Carrera Cup (964);*=Porsche 964 Cup
Porsche 911 GT3 Cup (991.2) Endurance;*=Porsche 991.2 GT3 Cup
Porsche 911 GT3 Cup (992) Endurance;*=Porsche 992 GT3 Cup
Porsche 911 GT3 Cup;*=Porsche Carrera Cup Deutschland 2019
Porsche 911 GT3 Cup (992);*=Porsche Carrera Cup Deutschland 2023
Porsche 911 GT3 Cup (992);*=Porsche Carrera Cup North America 2024
Porsche 911 GT3 Cup (991.2);*=Porsche Carrera Cup Scandinavia
Praga R1;*=Praga R1
BMW M1 Procar;*=Procar
Canhard R51;*=Silhouette Series
Canhard R52;*=Silhouette Series
Cougar C14-1;*=Silhouette Series
Cougar C14-2;*=Silhouette Series
Alfa Romeo 156 Super Touring;*=Super Touring
Audi A4 Super Touring 1995;*=Super Touring
BMW 320i E36 Super Touring;*=Super Touring
Honda Accord Super Touring;*=Super Touring
Opel Vectra Super Touring;*=Super Touring
Renault Laguna Super Touring;*=Super Touring
Volvo 850 Super Touring;*=Super Touring
Volvo S40 Super Touring;*=Super Touring
Tatuus F4;*=Tatuus F4 Cup
Audi RS 3 LMS;*=Touring Cars Cup
CUPRA Leon Competición;*=Touring Cars Cup
Honda Civic TCR;*=Touring Cars Cup
Hyundai i30 N TCR;*=Touring Cars Cup
Lada Vesta;*=Touring Cars Cup
Lynk & Co 03 TCR;*=Touring Cars Cup
Opel Astra;*=Touring Cars Cup
Volkswagen Golf GTI TCR;*=Touring Cars Cup
BMW 635 CSI;*=Touring Classics
BMW M3 E30 Gr.A;*=Touring Classics
Nissan Skyline GTR R32 Group N;*=Touring Classics
Volvo 240 Turbo;*=Touring Classics
RaceRoom Truck;*=Truck Racing
Volkswagen ID. R;*=Volkswagen ID. R
BMW E90 320 TC;*=WTCC 2013
Chevrolet Cruze WTCC;*=WTCC 2013
Honda Civic WTCC;*=WTCC 2013
Lada Granta WTCC;*=WTCC 2013
SEAT León WTCC;*=WTCC 2013
Chevrolet RML Cruze TC1;*=WTCC 2014
Citroen C Elysee WTCC;*=WTCC 2014
Honda Civic WTCC 2014;*=WTCC 2014
LADA Granta 1.6T;*=WTCC 2014
Chevrolet RML Cruze TC1 2015;*=WTCC 2015
Citroen C Elysee WTCC 2015;*=WTCC 2015
Honda Civic WTCC 2015;*=WTCC 2015
Lada Vesta WTCC 2015;*=WTCC 2015
Chevrolet RML Cruze TC1 2016;*=WTCC 2016
Citroen C Elysee WTCC 2016;*=WTCC 2016
Honda Civic WTCC 2016;*=WTCC 2016
Lada Vesta WTCC 2016;*=WTCC 2016
Volvo S60 Polestar TC1;*=WTCC 2016
Chevrolet RML Cruze TC1 2017;*=WTCC 2017
Citroen C Elysee WTCC 2017;*=WTCC 2017
Honda Civic WTCC 2017;*=WTCC 2017
Lada Vesta WTCC 2017;*=WTCC 2017
Volvo S60 Polestar TC1;*=WTCC 2017
Alfa Romeo Giulietta TCR;*=WTCR 2018
Audi RS 3 LMS;*=WTCR 2018
CUPRA TCR;*=WTCR 2018
Honda Civic TCR;*=WTCR 2018
Hyundai i30 N TCR;*=WTCR 2018
Peugeot 308 TCR;*=WTCR 2018
Volkswagen Golf GTI TCR;*=WTCR 2018
Alfa Romeo Giulietta TCR;*=WTCR 2019
Audi RS 3 LMS;*=WTCR 2019
CUPRA TCR;*=WTCR 2019
Honda Civic TCR;*=WTCR 2019
Hyundai i30 N TCR;*=WTCR 2019
Lynk & Co 03 TCR;*=WTCR 2019
Volkswagen Golf GTI TCR;*=WTCR 2019
Alfa Romeo Giulietta TCR;*=WTCR 2020
Audi RS 3 LMS;*=WTCR 2020
CUPRA Leon Competición;*=WTCR 2020
Honda Civic TCR;*=WTCR 2020
Hyundai i30 N TCR;*=WTCR 2020
Lynk & Co 03 TCR;*=WTCR 2020
Renault Mégane RS TCR;*=WTCR 2020
Audi RS 3 LMS 2021;*=WTCR 2021
CUPRA Leon Competición;*=WTCR 2021
Honda Civic TCR;*=WTCR 2021
Hyundai Elantra TCR 2021;*=WTCR 2021
Lada Vesta TCR;*=WTCR 2021
Lynk & Co 03 TCR;*=WTCR 2021
Audi RS 3 LMS 2021;*=WTCR 2022
CUPRA Leon Competición;*=WTCR 2022
Honda Civic TCR;*=WTCR 2022
Hyundai Elantra TCR 2022;*=WTCR 2022
Lynk & Co 03 TCR;*=WTCR 2022
Pagani Zonda R;*=Zonda R Cup